### ISSUE TITLE
Re-transmit lost packets

### ISSUE THREAD

**Issue by tatsuhiro-t** [ngtcp2/ngtcp2#1]

**Comment by nickfajones** [comment]
Hello Tatsuhiro,
The quicwg First Implementation Draft only mentions re-transmission of handshake packets only through a fixed timer.  Is this as far as you intend to go with this milestone or are you intending to do more?

In my opinion, I would like this milestone to remain minimalist, as the First Implementation Draft and even the Second Implementation Draft suggest that implementations ignore loss recovery and performance issues for now.

An additional question: will you be adding more github milestones to match the list in the First Implementation Draft?  Even though you have likely implemented many of them already, it would be nice to be able to measure where this project stands.

And please let me say: excellent work so far!

**Comment by tatsuhiro-t** [comment]
My plan is add simplest re-transmission as suggested in first implementation draft wiki.  My knowledge is not good enough in this area unfortunately.

For milestones, I'll review the wiki page, and add the required but not implemented item.

**Comment by nickfajones** [comment]
In a conversation with @bagder a long time ago, we came up with these ideas about how to deal with timeouts:
Internally, the library will maintain an ordered structure of timeouts, probably something like a tree.  When an action happens in the library, that expects a timeout, the library will post the timeout time and a callback on to the timeout tree.  When the library returns from its event loop, the parent application will then query a function to check when the next timeout is, the parent application will then use the master event loop to measure a timeout, then return to the quic library to allow it to continue it's tasks.

I imagine the code may flow something like this:

`
int main() {
  ...
  ngtcp2_conn_send(...) {
  ...
    conn_encode_handshake_pkt(...) {
      // add a timeout to the ngtcp2 timeout tree
      set_timeout(&conn_handshake_timeout, 10, 0);
    }
  ...
  }

  // parent application sets a timeout natively
  struct timeval to_time;
  ngtcp2_get_next_timeout(&to_time);

  ev_timer_init(timer, &app_ngtcp2_timeout, to_time.tv_sec, to_time.tv_usec);
  ev_run(...)
}

void app_ngtcp2_timeout(...) {
  ngtcp2_loop(...) {
    ...
    // allow ngtcp2 to process any expired timeouts
    process_timeouts(...) {
      struct timeval now_time;
      gettimeofday(&now_time, NULL);

      struct ngtcp2_timeout* timeout = NULL;
      while ((timeout = head_timeout()) != NULL) {
        if (timeout_compare(&timeout->time, &now_time) > 0) {
          // stop processing as current timeout is yet to expire
          break;
        }

        timeout->callback(...);

        release_timeout(&timeout);
      }
    }
  }
}

void conn_handshake_timeout(...) {
  conn_retry_handshake_pkt(...);
}
`

**Comment by tatsuhiro-t** [comment]
Yeah, it would work.  I have also similar idea.  ngtcp2_conn_recv and ngtcp2_conn_send take microseconds resolution timestamp parameter, and it allows ngtcp2 functions to do any job related to timeout.
The idea is provide time point from application.  Getting time is still system dependent, and I'd like to remove such burden from ngtcp2 library.

**Comment by nickfajones** [comment]
Agreed, application should manage the actual delay, ngctp2 should only announce how long its shortest delay is, hence my suggestion for the "ngtcp2_get_next_timeout" function.  (sorry, I didn't mark that clearly with a comment, and sorry also for the strange pattern in my sample code of declaring and using functions inline)

**Comment by nickfajones** [comment]
oh, I get what you were saying now, not just timeouts handled by parent application, but also timestamps.  Maybe something like your mem structure where you have alloc, calloc, realloc and free function pointers, you also want some sort of timers interface for storing and comparing timestamps

**Comment by tatsuhiro-t** [comment]
#26 implements retransmission.  Currently, only the unprotected handshake packets are retransmitted.  It is fine because we only send encrypted packet with CONNECTION_CLOSE frame which we don't have to retransmit.

The idea is basically the same we discussed here.  ngtcp2_conn_earliest_expiry works like ngtcp2_get_next_timeout, and application sets timer based on that, and call ngtcp2 API to resend lost packets.
