### ISSUE TITLE
Absolute source paths leaking into the release binaries

### ISSUE THREAD

**Issue by vszakats** [ngtcp2/ngtcp2#1003]
Since 31fa4fe7446a8456fa1cca4c579334861fd5a069 #585, the
`ngtcp2_unreachable()` macro leaks the full path of the source files
it's used in, when building with CMake. (Haven't tried autotools, which
is less prone to referencing sources with their full path, but may be
affected nevertheless.)

The full path makes it difficult to make reproducible builds accross
environments and may also leak sensitive data.

IMO one possible fix is to reduce the macro to a generic message
for non-debug builds, or replace it with a no-op. The latter would also 
avoid using `abort()` in the library code, which may badly interfere
with apps using it (Ref:
https://infosec.exchange/@harrysintonen/111325261101468978).

The same applies to the nghttp3 library:
https://github.com/ngtcp2/nghttp3/commit/e9531116d8396834c5ec55ac8254013643d11610
https://github.com/ngtcp2/nghttp3/pull/93

**Comment by vszakats** [comment]
Thanks for your feedback @tatsuhiro-t!

I'm sorry if my report wasn't clear. The issue is that `__FILE__` (an absolute
path in CMake builds) ends up in the generated binary. For example any of 
these curl binaries from yesterday that are linking `libngtcp2.a`:
https://github.com/curl/curl-for-win/actions/runs/6724793262.

They have paths like this in them:
![Screen Shot](https://github.com/ngtcp2/ngtcp2/assets/1446897/7fe1bbaf-04e6-4de1-8cb2-1f05360be094)

#1005 strips this before outputting it in case of an error, but at that point the 
full path already leaked with the binary itself. And because it's present in the
binary, it breaks creating reproducible/deterministic binaries when building
from a different root path.

Deleting `__FILE__` from the source fixes this. Because `__LINE__`,
`__func__` already  identifies the exact source location, this might be
a solution. Another solution is to no-op these macros for non-debug builds,
or strip these logging details from those builds.

My current workaround is compiling with `-ffile-prefix-map=my_root_path=`.
But that is GCC/llvm-specific, needing versions that support this options and
it needs to be added manually after the fact.

**Comment by tatsuhiro-t** [comment]
Thanks.  Just `__func__` might be problematic if we have the functions share the same name in multiple files, that would be remedied by `__LINE__`.  I would go with `__FILE_NAME__` macro which is available at least gcc and clang.  If that is not available, just emit placeholder string.

**Comment by tatsuhiro-t** [comment]
#1006 is what I wrote in the previous comment.

**Comment by vszakats** [comment]
`__FILE_NAME__` might work, though I don't know how compatible it is (e.g. with MSVC and older compiler versions).

Re-used function names touches another issue: I tried to enable "unity" [^1][^2] builds for ngtcp2/nghttp3/nghttp2 and it failed with all three. For these builds it's critical to have unique symbols (typically function names) accross the whole library.

Having unique symbol names could solve both problems in one, without limiting C compiler compatibility or adding more feature detections. Unity also make builds (much) faster. (I implemented it for both libssh2 and curl earlier this year.)

[^1]: Article: https://serge-sans-paille.github.io/pythran-stories/how-unity-builds-crept-into-the-firefox-build-system.html
[^2]: Docs: https://cmake.org/cmake/help/latest/variable/CMAKE_UNITY_BUILD.html

**Comment by tatsuhiro-t** [comment]
Perhaps, use `__FILE__` if `__FILE_NAME__` is not defined, and let package maintainer do anything they want, say, adding compiler specific flags etc.

Is Unity build related to this issue?  At the moment, C compiler is fast enough and ngtcp2 is small enough to be built in reasonable time.

**Comment by tatsuhiro-t** [comment]
Or if `__FILE__` is not acceptable, merge #1006, and for those compilers that do not define `__FILE_NAME__`, we just guess where the crash happens by function name and line number.  That is not nice but there is no way to handle this stuff nicely for all compilers out there.
