### ISSUE TITLE
BBR vs BBR2 

### ISSUE THREAD

**Issue by nEghbal** [ngtcp2/ngtcp2#1024]
Hello,

I was working on an old version of ngtcp2 from a year ago and there were both bbr and bbr2.
Recently, as I came across a performance problem with bbr, I tried bbr2 and it does not have that problem.

Then I check the recent version and realized that as some point bbr2 replaced bbr and now we have only one option for bbr.

My question are 
1) Did bbr in the previous code have some sort of bug/issue?
2) Is the current bbr implementation in the recent code based on the bbr 2017 paper or the updates after that as bbrv2?

Thanks.

**Comment by tatsuhiro-t** [comment]
BBR internet drafts are inherently incomplete and have missing pieces.  BBR is still the active experiments from Google. I am not surprised that we may have bugs or issues in such condition.  I do not remember any particular issues on BBRv1, and will not do any effort to check the old implementation that has already been deleted.

The current BBR implementation is based on https://datatracker.ietf.org/doc/html/draft-cardwell-iccrg-bbr-congestion-control-02

**Comment by nEghbal** [comment]
Great, thanks.
