### ISSUE TITLE
Assertion failure with GnuTLS early data enabled and %NO_TICKETS in the priority string

### ISSUE THREAD

**Issue by Spiffyk** [ngtcp2/ngtcp2#1070]
Hi, I get the following assertion error:

```
ngtcp2/lib/ngtcp2_conn.c:13515: ngtcp2_conn_set_retry_aead: Assertion `!conn->crypto.retry_aead_ctx.native_handle' failed.
```

Before the abort, `ERR_INVALID_STATE` is returned a few times from my `ngtcp2_conn_write_connection_close` calls.

This happens when my GnuTLS session has `GNUTLS_ENABLE_EARLY_DATA | GNUTLS_NO_END_OF_EARLY_DATA` flags set, but there is `%NO_TICKETS` set in the priority string, disabling TLS resumption.

**Comment by Spiffyk** [comment]
The usage is a DNS-over-QUIC client/bencharking tool: https://gitlab.nic.cz/knot/shotgun/-/merge_requests/75#note_292036

**Comment by tatsuhiro-t** [comment]
Please make sure that ngtcp2_conn is not reused among multiple connections.  It looks like the initial key is regenerated without retry token.

**Comment by Spiffyk** [comment]
Hmm, I don't think I am reusing `ngtcp2_conn`, definitely not intentionally. And it sounds strange to me that changing the flags handed to `gnutls_init()` would cause that, unless my code only ever hits that path when those specific flags are set? I can't immediately see how that would happen, though.

**Comment by tatsuhiro-t** [comment]
I am not sure about gnutls flags.  It is gnutls specific stuff, not really changing the behavior of ngtcp2.
You wrote ngtcp2_conn_write_connection_close returns nonzero error before you see the abort.  Typically, ngtcp2_conn_write_connection_close is the last API for a given ngtcp2_conn object.  That sounds very suspicious because after that you looks like reusing ngtcp2_conn object for some reason.

**Comment by Spiffyk** [comment]
Oh, I now see a possible misunderstanding.

The tool actually creates a larger number of connections against a DNS-over-QUIC server, so it might just be that one connection calls `ngtcp2_conn_write_connection_close`, which returns the `ERR_INVALID_STATE`; and another hits the failing assertion. What I know is that neither of these happens when the aforementioned GnuTLS flags are not set.

But I will investigate further whether I'm really not calling something on the `ngtcp2_conn` after the `write_connection_close` call. Until then, thank you for the assistance!

**Comment by tatsuhiro-t** [comment]
I tried %NO_TICKETS but did not see any assertion failure.

**Comment by Spiffyk** [comment]
Thanks. I have investigated a bit more and found out that an `ngtcp2_conn` *does* occasionally get used even after the `ngtcp2_conn_write_connection_close`, so that is a bug on my side. What threw me off is that the assertion failure **only** gets triggered with the early data flags and resumption tickets disabled, but that is probably just a combination of coincidences at play here. The root of the problem will probably be the reuse in any case.

Thanks for the help, I'll be closing this now, as the issue probably does not lie with `ngtcp2` after all.
