### ISSUE TITLE
Does conn_write_handshake_ack_pkt need to be called always after handshake ack packet sent and handshake complete？

### ISSUE THREAD

**Issue by XingkaiLiang** [ngtcp2/ngtcp2#108]
Hi tatsuhiro-t-san,
 **1.Question：**
i run perf to check the event of ngtcp2 at server side and find the ratio of conn_create_ack_frame is too high with a ratio of 1.8%. I track the source and get some info.
    server call  ngtcp2_conn_writev_stream to send every packet  to client and always call conn_write_handshake_ack_pkts before and after handshake completeness. My point is at conn_write_handshake_ack_pkts.  Initial and handshake ACK packet should be skipped after handshake ACK is sent,  right？

**2.debug code：**
//after handshake ack sent and handshake complete，skip
static ssize_t conn_write_handshake_ack_pkts(ngtcp2_conn *conn, uint8_t *dest,
                                             size_t destlen, ngtcp2_tstamp ts) {
  ssize_t res = 0, nwrite;
  **static uint16_t check_flag=0;**
  int require_padding = !conn->hs_pktns.tx_ckm;

  if (require_padding) {
    /* PADDING frame counts toward bytes_in_flight, thus destlen is
       constrained to cwnd */
    destlen = ngtcp2_min(destlen, conn_cwnd_left(conn));
  }
  **if (check_flag){
      return 0;
  }**
  nwrite = conn_write_handshake_ack_pkt(conn, dest, destlen, NGTCP2_PKT_INITIAL,
                                        require_padding, ts);
  if (nwrite < 0) {
    assert(nwrite != NGTCP2_ERR_NOBUF);
    return nwrite;
  }

  res += nwrite;
  dest += nwrite;
  destlen -= (size_t)nwrite;

  nwrite = conn_write_handshake_ack_pkt(
      conn, dest, destlen, NGTCP2_PKT_HANDSHAKE, 0 /* require_padding */, ts);
  if (nwrite < 0) {
    assert(nwrite != NGTCP2_ERR_NOBUF);
    return nwrite;
  }
  **if(ngtcp2_conn_get_handshake_completed(conn)){
    check_flag = 1;
  }**
  return res + nwrite;
}   

**3.Enviroment：**
 Client           GET  /index.html_1M             Server
client connect with server and get 1M file

**4 call stack：**
ngtcp2_conn_writev_stream ->
 conn_write_handshake_ack_pkts ->
conn_write_handshake_ack_pkt ->
conn_create_ack_frame

**5 raw data：**
+    3.35%  lt-ngquic  libjemalloc.so.1       [.] free
+    2.86%  lt-ngquic  libjemalloc.so.1       [.] malloc
+    1.80%  lt-ngquic  libngtcp2.so.0.0.0    [.] conn_create_ack_frame.constprop.2
+    1.35%  lt-ngquic  libcrypto.so.1.1        [.] OPENSSL_cleanse

**Comment by tatsuhiro-t** [comment]
At the moment, we have no good way to know that all handshake packets are received.  The upcoming update to quic spec will fix this.  When it is ready, I will review this code and remove the unnecessary function call.

**Comment by XingkaiLiang** [comment]
Thanks for your reply.
