### ISSUE TITLE
compiling draft-17 branch fails

### ISSUE THREAD

**Issue by ptrd** [ngtcp2/ngtcp2#109]
Hi,

When compiling draft-17 branch (on Mac osx) i get the error below.
Master compiles and works withouth errors.
Any idea?

client.cc:809:3: error: no matching function for call to 'SSL_set_key_callback'
  SSL_set_key_callback(ssl_, key_cb, this);
  ^~~~~~~~~~~~~~~~~~~~
/Users/peter/source/os/openssl/build/include/openssl/ssl.h:634:6: note: candidate function not viable: no known conversion from 'int (SSL *,
      int, const unsigned char *, size_t, void *)' (aka 'int (ssl_st *, int, const unsigned char *, unsigned long, void *)') to 'int (*)(SSL
      *, int, const unsigned char *, size_t, const unsigned char *, size_t, const unsigned char *, size_t, void *)' (aka 'int (*)(ssl_st *,
      int, const unsigned char *, unsigned long, const unsigned char *, unsigned long, const unsigned char *, unsigned long, void *)') for
      2nd argument
void SSL_set_key_callback(SSL *ssl,

**Comment by hoang-tranviet** [comment]
If you are using custom openssl, you also need to switch your openssl to the relevant branch (draft-17) and compile both.

**Comment by tatsuhiro-t** [comment]
Closing since quictls/openssl has now different set of APIs for QUIC.
