### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by mcollina** [ngtcp2/ngtcp2#1109]
I'm part of the Node.js TSC, and it would be of great help if nctcp2 adopted a Security policy.
let me know if you need help in crafting one.

Thanks!

**Comment by tatsuhiro-t** [comment]
I am currently considering to adopt the policy similar to nghttp2 https://github.com/nghttp2/nghttp2/blob/master/doc/sources/security.rst

**Comment by mcollina** [comment]
That’d be perfect, thanks!
