### ISSUE TITLE
Perform PMTUD periodically

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#1118]
I have another feature request.

In addition to right after handshake and upon connection migration, could we have the ability to perform PMTUD periodically, with a specified interval?

Although hopefully pretty rare, some intermediate nodes or a VPN between the endpoints could change in a way that affects the MTU without causing the endpoints' IPs to change; i.e., the MTU could change even without a connection migration.

It would be nice to be able to do PMTUD periodically to detect this scenario and start using the new MTU.

**Comment by tatsuhiro-t** [comment]
If MTU gets larger, performing PMTUD again will get a perf boost a bit, but if it is shortened, then the damage has already been done, dropping large packets just like misconfigured MTU.  Periodic PMTUD might be too late to fix this issue.  Linux does PMTUD on UDP socket in background, and sendmsg returns error if we send a packet larger than that after kernel knowns the MTU.  Is linux kernel also does PMTUD periodically?

**Comment by sshock** [comment]
> but if it is shortened, then the damage has already been done, dropping large packets just like misconfigured MTU.

Is there any damage besides lost datagrams (which aren't guaranteed anyways) and delayed stream bytes?  Isn't it better to at least eventually figure out the new MTU so stream bytes can get transmitted in a smaller packet and eventually get through?

> Periodic PMTUD might be too late to fix this issue.

Applications must be designed to handled dropped datagrams and delayed stream bytes anyways.  And the impact of these could be minimized if desired by specifying a smaller PMTUD interval.

> Linux does PMTUD on UDP socket in background, and sendmsg returns error if we send a packet larger than that after kernel knowns the MTU. Is linux kernel also does PMTUD periodically?

Maybe, but in my case at least, I am not using Linux sockets.

**Comment by tatsuhiro-t** [comment]
My point is that loss ratio due to misconfigured MTU is much higher than normal loss which is less than 1% that I heard several years ago.
https://www.rfc-editor.org/rfc/rfc8899#name-black-hole-detection-and-re has some guidance about re-evaluating PMTU on this situation.  It includes periodic timer.  It also says do not perform PMTUD if application does not send any app-data not to cause unnecessary network load.  Triggering PMTUD on large-sized packet loss is interesting, though actually how to detect that thing needs some consideration, especially this situation is rare so it is hard to justify the current method is good enough.

**Comment by sshock** [comment]
This isn't a super high priority for me at the moment, so I'm ok to give it some more thought and maybe revisit it in the future, so you can close this out if you like.

**Comment by tatsuhiro-t** [comment]
Thanks.  It is nice to do something to adopt the changes in path characteristics for a long lived connection, but currently I have no good answer how to implement this.  Just leave this one open (may be closed due to inactivity).  Will revisit later.

**Comment by redbaron** [comment]
> sendmsg returns error if we send a packet larger than that after kernel knowns the MTU.

@tatsuhiro-t , how should app react to it? is it enough to  decrease available buffer size when calling ngtcp2_conn_writev_stream?

**Comment by redbaron** [comment]
I can see that [example](https://github.com/ngtcp2/ngtcp2/blob/3786f10b3900e2aaff71f9ead6ee4eac96790c7a/examples/client.cc#L1559) client treats `EMSGSIZE` as success and doesn't make any adjustments anywhere.

**Comment by tatsuhiro-t** [comment]
If you know the correct MTU, then compute the safe DGRAM payload size from it, and pass that amount of buffer to ngtcp2_conn_writev_stream.  example is just an example and does not handle everything, and that's OK.

**Comment by redbaron** [comment]
> If you know the correct MTU

That's easier said than done  :)  I am trying to figure it out, previously example was a tremendous help on how to wire stuff up (TLS stack especially), but not in this case.

My understanding is that there are 3 mechanisms:
- `IP_MTU_DISCOVER` socket option + `EMSGSIZE` error code
- "DF" flag + IP_RECVERR to read back ICMPs
- ngtcp2's PMTUD , which seems to relay on unACKed packets to infer MTU.

should just one be used? combination of them? do any of these conflict with each other?  what is the tradeoff for each of them?

**Comment by tatsuhiro-t** [comment]
Discussion in closed issue is hard to check.  This is my last comment in this thread.
I believe QUIC mandates DF bit, but intermediaries can happily drop it sadly.
I heard that this MTU change is so unpredictable, a large internet service company uses minimum 1200 bytes DGRAM to avoid this entirely.
You might use RTNETLINK to get MTU if linux kernel knows it but I have not tried that.
It might be nice to have a switch to tell ngtcp2 to reset MTU and do PMTUD again if we get EMSGSIZE or something.
