### ISSUE TITLE
Can't see NEW_CONNECTION_IDs

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#1131]
Hi, I'm hoping this has an easy explanation.  I recently started testing with the latest ngtcp2 (previously I had been testing with an older version like 0.14) and I noticed that the NEW_CONNECTION_IDs are no longer showing up in wireshark.

My guess is it is a side effect of this: https://github.com/ngtcp2/ngtcp2/pull/906

That's awesome if the NCIs are now being exchanged sooner without an extra round-trip!

My question is, why don't they show up in wireshark?  I see a QUIC packet that wireshark describes as "(Random) padding data" that I am pretty confident contains the NCIs, but it worries me that wireshark does not dissect it.

Is this a known issue with wireshark, or could there be an actual problem?

**Comment by sshock** [comment]
Screenshots (old vs new) to illustrate:

OLD:
![ncids_old](https://github.com/ngtcp2/ngtcp2/assets/1693761/e829b61f-b267-4a83-8a9b-26e44e97b2cc)

NEW:
![ncids_new](https://github.com/ngtcp2/ngtcp2/assets/1693761/21d055c2-2b2d-46de-bd77-b3eefbe8767d)

**Comment by tatsuhiro-t** [comment]
I think it is better to ask wireshark developer about this.  0.5 RTT data is legitimate in QUIC, and other implementations can receive it without an issue.

**Comment by sshock** [comment]
Ok, I'll submit an issue to wireshark.

Also, thank you for anticipating my next question: it is relieving to know that it interops fine with other implementations.
