### ISSUE TITLE
CMake wolfssl find_package is out of sync with latest version

### ISSUE THREAD

**Issue by kdowney-lot49** [ngtcp2/ngtcp2#1133]
In `CMakeLists.txt`:

```
if(ENABLE_WOLFSSL)
  find_package(wolfssl 5.5.0)
```

but the `README.rst` correctly references 5.6.6 as the correct latest version.

**Comment by 0xg0nz0** [comment]
My mistake -- this is the *minimum* version ... though there are pre-5.6.6 issues so might not be a bad idea to change
