### ISSUE TITLE
How to build GnuTLS and Picotls client & server.

### ISSUE THREAD

**Issue by Karthikdasari0423** [ngtcp2/ngtcp2#1149]
How to build GnuTLS client & server ,Picotls client & server.

I have built GnuTLS and Picotls using below urls
https://github.com/curl/curl/blob/master/docs/HTTP3.md#build-with-gnutls
https://github.com/h2o/picotls

@tatsuhiro-t 
Can you pls provide ./configure commands for ngtcp2 to  generate GnuTLS client & server ,Picotls client & server executables.
(Like how you have provided ./configure commands  to build ngtcp2 executables with Boringssl, Wolfssl, AWS-LC)

**Comment by Karthikdasari0423** [comment]
i mean how to generate gtlsclient, gtlsserver and ptlsclient, ptlsserver with ./configure command.

**Comment by tatsuhiro-t** [comment]
In general, provide --with-<TLS_STACK> (e.g., --with-gnutls, --with-picotls, etc) to configure, see ./configure -h
Also provide <TLS_STACK>_CFLAGS and <TLS_STACK>_LIBS to specify the path to header files and library respectively.
If TLS stack provides pkg-config, the above 2 variables can be detected automatically.  If pkg-config is found in non-standard location, specify PKG_CONFIG_PATH.  See also https://github.com/ngtcp2/ngtcp2/blob/main/.github/workflows/build.yml as an example.

Please refer to the individual TLS stack document to know how to build it.

**Comment by Karthikdasari0423** [comment]
okay,Will try these
Thanks @tatsuhiro-t

**Comment by Karthikdasari0423** [comment]
Thanks @tatsuhiro-t 
Successfully created ptlsclient, ptlsserver and gtlsclient, gtlsserver

```
root@ubuntu:/home/vagrant/quic_services/ngtcp2/examples# ls -lrth | grep "rwxr"
-rwxr-xr-x 1 root root  65K Mar  9 02:48 qtlssimpleclient
-rwxr-xr-x 1 root root 2.2M Mar  9 02:48 qtlsclient
-rwxr-xr-x 1 root root 2.9M Mar  9 02:48 qtlsserver
-rwxr-xr-x 1 root root 1.1M Mar  9 02:49 examplestest
-rwxr-xr-x 1 root root 2.9M Mar  9 13:48 ptlsclient
-rwxr-xr-x 1 root root 3.7M Mar  9 13:48 ptlsserver
drwxr-xr-x 3 root root 4.0K Mar  9 14:37 tests
-rwxr-xr-x 1 root root  70K Mar  9 14:37 gtlssimpleclient
-rwxr-xr-x 1 root root 2.2M Mar  9 14:37 gtlsclient
-rwxr-xr-x 1 root root 2.9M Mar  9 14:37 gtlsserver
root@ubuntu:/home/vagrant/quic_services/ngtcp2/examples#
```
