### ISSUE TITLE
Server CONNECTION_CLOSE during handshake can result in an assertion

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#1151]
The following scenario leads to an assertion:
* Client has sent first packet with ClientHello
* Server has replied with its first packet (with ServerHello + EE + TLS Handshake Finished + NCIs)
* On server try to send a CONNECTION_CLOSE of CCERR_TYPE_APPLICATION

In this state the following conditions are true:
* conn->state == NGTCP2_CS_SERVER_WAIT_HANDSHAKE
* conn->flags == 0x808F (includes NGTCP2_CONN_FLAG_HANDSHAKE_CONFIRMED, 0x80)

While in this state an assertion occurs in ngtcp2_conn_write_application_close_pkt() on the `assert(res);` line in this block of code:

```
  if (conn->state != NGTCP2_CS_POST_HANDSHAKE) {
    assert(res);

    if (!conn->server || !conn->pktns.crypto.tx.ckm) {
      return res;
    }
  }
```

Since the HANDSHAKE_CONFIRMED flag is set, it skipped the call to conn_write_connection_close(), and since it's still in SERVER_WAIT_HANDSHAKE (hasn't transitioned to POST_HANDSHAKE yet), it goes into this block and immediately asserts on assert(res), since res didn't get set.

**Comment by tatsuhiro-t** [comment]
I think we can go simpler to just send 1RTT connection close when we have keying materials for it.  Will look into it.

**Comment by sshock** [comment]
Great, thanks for the quick turn-around and fix!
