### ISSUE TITLE
Server cannot send CONNECTION_CLOSE after handshake timeout

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#1152]
On a client I am allowed to send a CONNECTION_CLOSE after handshake timeout (it sends the CC in an Initial Packet).

But on a server I cannot send a CONNECTION_CLOSE after handshake timeout because `ngtcp2_conn_write_connection_close()` returns NGTCP2_ERR_NOBUF.

This is happening because `ngtcp2_conn_write_connection_close_pkt()` sets destlen to 0 in this section of code (because server_tx_left is 0):

```
  if (conn->server) {
    server_tx_left = conn_server_tx_left(conn, &conn->dcid.current);
    destlen = (size_t)ngtcp2_min((uint64_t)destlen, server_tx_left);
  }
```

Is this by design?  Is a server not allowed to send a CC after handshake timeout, whereas a client is?

If it is by design, I can change my server code to avoid sending a CC after handshake timeout.

**Comment by tatsuhiro-t** [comment]
During initial connection setup phase, server is subject to amplification limit to avoid certain kind of attack, that is server is only allowed to send 3 times that it received from client.  So yes, this is by design.

**Comment by sshock** [comment]
>So yes, this is by design.

Ok, thanks!
