### ISSUE TITLE
CONNECTION_CLOSE Initial Packet from client is treated as new connection by server

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#1153]
Hi, I'm hoping you can help me understand if this is by design, or an issue with the API, or an issue with how I'm using it.

I set up an environment where all packets from the server are dropped.  Shortly after creating a connection, before handshake timeout, I have the client do a close.  This is before the client has received anything from the server.  The client sends the CONNECTION_CLOSE as an Initial packet.

The server treats this packet as a new connection, which is the part that seems wrong, although it doesn't cause too big of a problem I suppose, since it right away closes this new connection as ngtcp2_conn_read_pkt() returns NGTCP2_ERR_DRAINING.

But if it had been able to associate it with the first connection, that would have allowed the server to close down that first connection, rather than have it be left hanging around until it hits a handshake or idle timeout.

The server does not associate the packet with the first connection because it only uses its own generated SCIDs (not the initial DCID from client) to identify connections.

I guess this isn't all that different than when a client retransmits a ClientHello; each of those will be treated as a new connection by the server.  But it seems especially pointless for a CC.  Why even send a CC this early if a server will not benefit from it?

I must be missing something.  It seems like one of the following must be true:
1. Server should use initial DCID from client as an SCID to identify the connection.
    * But this is a violation of the RFC that is also a security vulnerability I believe.
2. Server should use client IP + client port + SCID + (initial) DCID as a connection identifier.
    * But I don't see the example server app doing this, and one of the key design points of QUIC is that a connection be identified solely by the DCID.
3. Client should not bother sending a CC during initial phase before it has received initial packet from server.
    * Maybe ngtcp2_conn_write_connection_close() should return an error if client is in this state?  It does return an INVALID_STATE error if in the CLIENT_INITIAL state, but we're in the CLIENT_WAIT_HANDSHAKE state.
    * Or if there is a way for ngtcp2 to let me know I'm in this state, I can avoid trying to send a connection close in this state.

Is one of the above three correct, or is there another explanation?  I just don't understand how it can be appropriate for a client to send a CC that will never benefit the server in any way.

**Comment by tatsuhiro-t** [comment]
> The server treats this packet as a new connection, which is the part that seems wrong, although it doesn't cause too big of a problem I suppose, since it right away closes this new connection as ngtcp2_conn_read_pkt() returns NGTCP2_ERR_DRAINING.
>
> But if it had been able to associate it with the first connection, that would have allowed the server to close down that first connection, rather than have it be left hanging around until it hits a handshake or idle timeout.

Those packets are expected to go here
https://github.com/ngtcp2/ngtcp2/blob/5abac22c174a176b00d7be59df6cd33630be330d/lib/ngtcp2_conn.c#L9783
but in this particular case, the function returns before that: https://github.com/ngtcp2/ngtcp2/blob/5abac22c174a176b00d7be59df6cd33630be330d/lib/ngtcp2_conn.c#L9763
Will fix this.

> The server does not associate the packet with the first connection because it only uses its own generated SCIDs (not the initial DCID from client) to identify connections.

There are several possible ways to associate DCID to connection.  The one that example ngtcp2 server uses is 2 separate associates: initial DCID to connection and server generated DCID to the connection.
The mapping from initial DCID to connection ensures that retransmitted initial packets can go to the same connection.  You can drop this after the handshake with some period to avoid the issue you described.

**Comment by tatsuhiro-t** [comment]
> Will fix this.

I decided to leave it as is because it would be nicer to drain packets destined to this connection ID when connection close is received.

**Comment by sshock** [comment]
> > Will fix this.
> 
> I decided to leave it as is because it would be nicer to drain packets destined to this connection ID when connection close is received.

Ok, sounds good.  From my perspective returning DROP_CONN or entering draining and returning ERR_DRAINING are equally fine for the scenario where a CC is processed as the first packet in a new connection.

> There are several possible ways to associate DCID to connection. The one that example ngtcp2 server uses is 2 separate associates: initial DCID to connection and server generated DCID to the connection.

Ah, ok good to know.  I think I missed this first mapping because I was only searching for `associate_cid()`, but I see now there is also a direct call to `handlers_.emplace(dcid_key, h.release());` in read_pkt().

> The mapping from initial DCID to connection ensures that retransmitted initial packets can go to the same connection. You can drop this after the handshake with some period to avoid the issue you described. In fact it is even better to use initial DCID plus address information to produce key. I'm doing this in nghttpx proxy server.

Very good, thanks!  I'll plan on using initial DCID + address info for this initial mapping like you're doing in nghttpx 😄.
