### ISSUE TITLE
Calculating max_pktcnt

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#1174]
Hi, I noticed that the sample server calculates `max_pktcnt` (to pace sending packets) by dividing the send_quantum by  `max_udp_payload_size`:

However, the (PMTUD discovered) path max is available in `path_max_udp_payload_size`; why not divide by that?

I may set `max_tx_udp_payload_size` to 9000-28 in order to support networks with jumbo frame support, however PMTUD might discover only 1500-28.  In that scenario, if I do like the sample app it could limit it to sending 7 packets in one go (65536 / 8972) instead of 44 (65536 / 1472) for example.

Although my tx buffer will be as large as `max_tx_udp_payload_size` (9000-28 bytes), since ngtcp2 discovered (1500-28) it will only write (1500-28) bytes to my tx buffer for each packet, so I think it makes more sense to divide by the `path_max_udp_payload_size`.

Please advise whether this sounds ok or if you foresee a problem with using `path_max_udp_payload_size` in this calculation.  Thanks!

**Comment by tatsuhiro-t** [comment]
If rewrite the code in a way that it does not overflow the gso buffer, then it would be fine, by checking remaining packet size is at least max_tx_udp_payload_size.

**Comment by sshock** [comment]
> If rewrite the code in a way that it does not overflow the gso buffer, then it would be fine, by checking that at least 1200 bytes buffer is passed to ngtcp2_conn_writev_stream.

Ok, in my case I'm not using packet batching, just sending one packet at a time, and my tx buffer will always be at least 1200 bytes, so I suspect I should be good here.

**Comment by tatsuhiro-t** [comment]
#1176 changes examples server so that more QUIC packets is packed in one gso buffer with larger MTU.

**Comment by sshock** [comment]
Thanks!
