### ISSUE TITLE
Installed wolfssl package missing wsslserver/wsslclient tool

### ISSUE THREAD

**Issue by ciscohack** [ngtcp2/ngtcp2#1178]
Hello Expert,

I have followed the steps mentioned on the documentation page and installed wolfssl packet for quic protocol. But after installation I have noticed examples/wsslserver  and examples/wsslclient is missing tried installation multiple time and all dependency package is installed as mention on doc but don't know why the tool is missing.

I installed the package on Ubuntu based linux distro. can you please help fix this problem as installation has no error but why the tool is missing

**Comment by tatsuhiro-t** [comment]
Older wolfssl does not support quic, and even if it does, quic feature is disabled by build configuration.

**Comment by ciscohack** [comment]
@tatsuhiro-t first thanks for the comment.. I installed yesterday only by pulling git repo as mentioned in documentation so I feel downloaded wolfssl is latest and I hope that wolfssl compilation have quic protocol but problem here with me when I trying to do examples/wsslserver and wsslclient these package not showing but this is disabled then documentation needs to be fixed and steps and example needs to be clearly documented to avoid any confusion

**Comment by ciscohack** [comment]
@tatsuhiro-t I wants to use wolfssl for http3 and quic how can I do this

**Comment by tatsuhiro-t** [comment]
https://github.com/ngtcp2/ngtcp2?tab=readme-ov-file#build-with-wolfssl is pretty clear.  Which part are you saying confusing? 
Or try docker https://github.com/ngtcp2/ngtcp2/blob/main/docker/Dockerfile if you are just trying wolfssl.

**Comment by ciscohack** [comment]
> https://github.com/ngtcp2/ngtcp2?tab=readme-ov-file#build-with-wolfssl is pretty clear. Which part are you saying confusing? Or try docker https://github.com/ngtcp2/ngtcp2/blob/main/docker/Dockerfile if you are just trying wolfssl.

No no Docker not needed. I am done with installation wolfssl becoz other 2 option having some issue with my linux machine 

now when I am trying this step.. wsslserver command is missing infact tool is not in examples directory and I want to fix it to use it for my testing

<img width="861" alt="image" src="https://github.com/ngtcp2/ngtcp2/assets/11479557/6001ba89-78aa-45d7-989e-da313d6f9375">

**Comment by ciscohack** [comment]
@tatsuhiro-t  Here I am trying to install aws-lc package as per doc.. I have Gcc/golang/clang all dependencies installed but the installation failing ...  Second I have openssl installed but I don't know why it complaining ..so this package installation is so complex never thought ..


<img width="1031" alt="image" src="https://github.com/ngtcp2/ngtcp2/assets/11479557/aa39dc9b-f242-4947-9269-e5ebf4636101">

**Comment by ciscohack** [comment]
@tatsuhiro-t Thanks for the quick response... I tried gcc-11 installation but didn't find packet in apt install .. don't know if gcc-12 will fix the issue
