### ISSUE TITLE
Provide encryption level when emiting crypto data

### ISSUE THREAD

**Issue by DaanDeMeyer** [ngtcp2/ngtcp2#118]
BoringSSL's quic API requires the encryption level to be provided to `SSL_provide_quic_data`. Currently, `ngtcp2_recv_crypto_data` doesn't provide the encryption level. Is it possible to add a parameter that provides the current encryption level to `ngtcp2_recv_crypto_data`?

I'm willing to make a pr myself, but I thought I'd ask if you're interested in merging it first. Pointers to where I can get the encryption level in the source code would be appreciated as well.

**Comment by tatsuhiro-t** [comment]
encryption level has been added to the callback in 0ea9f4b

**Comment by DaanDeMeyer** [comment]
Thanks!
