### ISSUE TITLE
submit_crypto_data adds handshake data to the application encryption level queue if the application level keys have already been set

### ISSUE THREAD

**Issue by DaanDeMeyer** [ngtcp2/ngtcp2#119]
I'm changing the example client and server to use OpenSSL instead of BoringSSL. BoringSSL provides the user with both the handshake encryption keys and the application encryption keys (that are immediately forwarded to ngtcp2) before providing the user with handshake data.

Because `ngtcp2_submit_crypto_data` decides the queue to add crypto data to based on which encryption keys have already been set, handshake data is added to the application queue instead of the handshake queue.

A possible solution is to change `ngtcp2_submit_crypto_data` to take the encryption level as a parameter and decide the queue to add crypto data to based on that parameter instead of which keys have already been set.

**Comment by DaanDeMeyer** [comment]
I can confirm adding the encryption level as a parameter and selecting the packet number space based on the encryption level in `ngtcp2_submit_crypto_data` solves the issue.

**Comment by tatsuhiro-t** [comment]
Thank you for diagnosing this problem.  I'll add encryption level parameter to the function.

**Comment by tatsuhiro-t** [comment]
crypto_level parameter is added by 3db0595

**Comment by DaanDeMeyer** [comment]
Thanks!
