### ISSUE TITLE
Build Error, ‘SSL_KEY_CLIENT_EARLY_TRAFFIC’ was not declared in this scope

### ISSUE THREAD

**Issue by yazh-zy** [ngtcp2/ngtcp2#121]
**I met this problem when I excuting 'make -j$(nproc) check', can anyone can help?**

keylog.cc: In function ‘void ngtcp2::keylog::log_secret(SSL*, int, const unsigned char*, size_t)’:
keylog.cc:43:10: error: ‘SSL_KEY_CLIENT_EARLY_TRAFFIC’ was not declared in this scope
     case SSL_KEY_CLIENT_EARLY_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
keylog.cc:43:10: note: suggested alternative: ‘SSL_R_CLIENTHELLO_TLSEXT’
     case SSL_KEY_CLIENT_EARLY_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
          SSL_R_CLIENTHELLO_TLSEXT
keylog.cc:46:10: error: ‘SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC’ was not declared in this scope
     case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
keylog.cc:46:10: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
     case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          SSL_F_SSL_HANDSHAKE_HASH
keylog.cc:49:10: error: ‘SSL_KEY_CLIENT_APPLICATION_TRAFFIC’ was not declared in this scope
     case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
keylog.cc:49:10: note: suggested alternative: ‘SSL_R_NO_APPLICATION_PROTOCOL’
     case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          SSL_R_NO_APPLICATION_PROTOCOL
keylog.cc:52:10: error: ‘SSL_KEY_SERVER_HANDSHAKE_TRAFFIC’ was not declared in this scope
     case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
keylog.cc:52:10: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
     case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          SSL_F_SSL_HANDSHAKE_HASH
keylog.cc:55:10: error: ‘SSL_KEY_SERVER_APPLICATION_TRAFFIC’ was not declared in this scope
     case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
keylog.cc:55:10: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
     case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          SSL3_RT_APPLICATION_DATA
make[1]: *** [keylog.o] Error 1
make[1]: *** Waiting for unfinished jobs....
client.cc: In member function ‘int Client::on_key(int, const uint8_t*, size_t)’:
client.cc:106:8: error: ‘SSL_KEY_CLIENT_EARLY_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_EARLY_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc: In member function ‘int Handler::on_key(int, const uint8_t*, size_t)’:
server.cc:101:8: error: ‘SSL_KEY_CLIENT_EARLY_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_EARLY_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:106:8: note: suggested alternative: ‘SSL_R_CLIENTHELLO_TLSEXT’
   case SSL_KEY_CLIENT_EARLY_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_R_CLIENTHELLO_TLSEXT
client.cc:107:8: error: ‘SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:101:8: note: suggested alternative: ‘SSL_R_CLIENTHELLO_TLSEXT’
   case SSL_KEY_CLIENT_EARLY_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_R_CLIENTHELLO_TLSEXT
server.cc:102:8: error: ‘SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:107:8: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
   case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_F_SSL_HANDSHAKE_HASH
client.cc:108:8: error: ‘SSL_KEY_SERVER_HANDSHAKE_TRAFFIC’ was not declared in this scope
   case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:102:8: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
   case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_F_SSL_HANDSHAKE_HASH
server.cc:103:8: error: ‘SSL_KEY_SERVER_HANDSHAKE_TRAFFIC’ was not declared in this scope
   case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:108:8: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
   case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_F_SSL_HANDSHAKE_HASH
client.cc:110:8: error: ‘SSL_KEY_CLIENT_APPLICATION_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:103:8: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
   case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_F_SSL_HANDSHAKE_HASH
server.cc:105:8: error: ‘SSL_KEY_CLIENT_APPLICATION_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:110:8: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
   case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL3_RT_APPLICATION_DATA
client.cc:113:8: error: ‘SSL_KEY_SERVER_APPLICATION_TRAFFIC’ was not declared in this scope
   case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:105:8: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
   case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL3_RT_APPLICATION_DATA
server.cc:108:8: error: ‘SSL_KEY_SERVER_APPLICATION_TRAFFIC’ was not declared in this scope
   case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:113:8: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
   case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL3_RT_APPLICATION_DATA
client.cc:153:8: error: ‘SSL_KEY_CLIENT_EARLY_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_EARLY_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:108:8: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
   case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL3_RT_APPLICATION_DATA
server.cc:148:8: error: ‘SSL_KEY_CLIENT_EARLY_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_EARLY_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:153:8: note: suggested alternative: ‘SSL_R_CLIENTHELLO_TLSEXT’
   case SSL_KEY_CLIENT_EARLY_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_R_CLIENTHELLO_TLSEXT
client.cc:160:8: error: ‘SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:148:8: note: suggested alternative: ‘SSL_R_CLIENTHELLO_TLSEXT’
   case SSL_KEY_CLIENT_EARLY_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_R_CLIENTHELLO_TLSEXT
server.cc:155:8: error: ‘SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:160:8: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
   case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_F_SSL_HANDSHAKE_HASH
client.cc:167:8: error: ‘SSL_KEY_CLIENT_APPLICATION_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:155:8: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
   case SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_F_SSL_HANDSHAKE_HASH
server.cc:162:8: error: ‘SSL_KEY_CLIENT_APPLICATION_TRAFFIC’ was not declared in this scope
   case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:167:8: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
   case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL3_RT_APPLICATION_DATA
client.cc:174:8: error: ‘SSL_KEY_SERVER_HANDSHAKE_TRAFFIC’ was not declared in this scope
   case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:162:8: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
   case SSL_KEY_CLIENT_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL3_RT_APPLICATION_DATA
server.cc:169:8: error: ‘SSL_KEY_SERVER_HANDSHAKE_TRAFFIC’ was not declared in this scope
   case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:174:8: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
   case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_F_SSL_HANDSHAKE_HASH
client.cc:181:8: error: ‘SSL_KEY_SERVER_APPLICATION_TRAFFIC’ was not declared in this scope
   case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.cc:169:8: note: suggested alternative: ‘SSL_F_SSL_HANDSHAKE_HASH’
   case SSL_KEY_SERVER_HANDSHAKE_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL_F_SSL_HANDSHAKE_HASH
server.cc:176:8: error: ‘SSL_KEY_SERVER_APPLICATION_TRAFFIC’ was not declared in this scope
   case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.cc:181:8: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
   case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL3_RT_APPLICATION_DATA
server.cc:176:8: note: suggested alternative: ‘SSL3_RT_APPLICATION_DATA’
   case SSL_KEY_SERVER_APPLICATION_TRAFFIC:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        SSL3_RT_APPLICATION_DATA
client.cc: In member function ‘int Client::init_ssl()’:
client.cc:829:3: error: ‘SSL_set_key_callback’ was not declared in this scope
   SSL_set_key_callback(ssl_, key_cb, this);
   ^~~~~~~~~~~~~~~~~~~~
client.cc:829:3: note: suggested alternative: ‘SSL_set_msg_callback’
   SSL_set_key_callback(ssl_, key_cb, this);
   ^~~~~~~~~~~~~~~~~~~~
   SSL_set_msg_callback
server.cc: In member function ‘int Handler::init(const Endpoint&, const sockaddr*, socklen_t, const ngtcp2_cid*, const ngtcp2_cid*, uint32_t)’:
server.cc:1039:3: error: ‘SSL_set_key_callback’ was not declared in this scope
   SSL_set_key_callback(ssl_, key_cb, this);
   ^~~~~~~~~~~~~~~~~~~~
server.cc:1039:3: note: suggested alternative: ‘SSL_set_msg_callback’
   SSL_set_key_callback(ssl_, key_cb, this);
   ^~~~~~~~~~~~~~~~~~~~
   SSL_set_msg_callback

**Comment by wenchiching** [comment]
did you follow every step in README.rst?
I just git pull from master again and build pass

Build from git
--------------

.. code-block:: text

   $ git clone --depth 1 -b quic-draft-18 https://github.com/tatsuhiro-t/openssl
   $ cd openssl
   $ # For Linux
   $ ./config enable-tls1_3 --prefix=$PWD/build
   $ make -j$(nproc)
   $ make install_sw
   $ cd ..
   $ git clone https://github.com/ngtcp2/ngtcp2
   $ cd ngtcp2
   $ autoreconf -i
   $ # For Mac users who have installed libev with MacPorts, append
   $ # ',-L/opt/local/lib' to LDFLAGS, and also pass
   $ # CPPFLAGS="-I/opt/local/include" to ./configure.
   $ ./configure PKG_CONFIG_PATH=$PWD/../openssl/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,$PWD/../openssl/build/lib"
   $ make -j$(nproc) check

**Comment by yazh-zy** [comment]
> did you follow every step in README.rst?
> I just git pull from master again and build pass
> 
> ## Build from git
> .. code-block:: text
> 
> $ git clone --depth 1 -b quic-draft-18 https://github.com/tatsuhiro-t/openssl
> $ cd openssl
> $ # For Linux
> $ ./config enable-tls1_3 --prefix=$PWD/build
> $ make -j$(nproc)
> $ make install_sw
> $ cd ..
> $ git clone https://github.com/ngtcp2/ngtcp2
> $ cd ngtcp2
> $ autoreconf -i
> $ # For Mac users who have installed libev with MacPorts, append
> $ # ',-L/opt/local/lib' to LDFLAGS, and also pass
> $ # CPPFLAGS="-I/opt/local/include" to ./configure.
> $ ./configure PKG_CONFIG_PATH=$PWD/../openssl/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,$PWD/../openssl/build/lib"
> $ make -j$(nproc) check

I think so, I downloaded the openssl from their website with the 1.1.1 version, and followed the steps.
Can you find the define of SSL_KEY_CLIENT_EARLY_TRAFFIC? As I cannot find the definition in OpenSSL.
Thanks

**Comment by wenchiching** [comment]
include/openssl/ssl.h
```
 648 typedef enum {
 649     SSL_KEY_CLIENT_EARLY_TRAFFIC,
 650     SSL_KEY_CLIENT_HANDSHAKE_TRAFFIC,
 651     SSL_KEY_CLIENT_APPLICATION_TRAFFIC,
 652     SSL_KEY_SERVER_HANDSHAKE_TRAFFIC,
 653     SSL_KEY_SERVER_APPLICATION_TRAFFIC
 654 } OSSL_KEY_TYPE;
```
ngtcp2 and openssl need to be put in the same folder, maybe give it a check

**Comment by LPardue** [comment]
You need to use Tatsuhiro's modified OpenSSL

**Comment by yazh-zy** [comment]
> You need to use Tatsuhiro's modified OpenSSL

thanks
