### ISSUE TITLE
Feature request: logging levels

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#1232]
Not sure if this would be too big of a breaking change, but could the ngtcp2_settings log_printf callback be enhanced to include a log level (to indicate if the log message is a debug, info, warning, or error message)?

Or does this request not make sense because 100% of these log messages should be considered DEBUG level?

**Comment by tatsuhiro-t** [comment]
Currently, they are all debug level log.

**Comment by sshock** [comment]
Ok, thanks.  I had a feeling that was likely the case.
