### ISSUE TITLE
Memory Leak for Stream and Crypto frames

### ISSUE THREAD

**Issue by havril514** [ngtcp2/ngtcp2#1244]
We seem to have a memory leak when memory pools are enabled in ngtcp2.

When pools are enabled (`NOMEMPOOL` undefined), small objects can be pulled from a pool (`ngtcp2_objalloc`). This pool is composed of a memory allocator (`ngtcp2_balloc`) which takes care of allocating chunks of memory and a linked list of objects stored into these chunks (`ngtcp2_opl`). Instead of allocating via the custom memory allocator (`ngtcp2_mem`), ngtcp2 pops an object from the pool and pushes it back upon release.

For small frames, ngtcp2 uses an object pool (on a per connection basis). For larger frames, ngtcp2 goes through the custom memory allocator. Crypto (`NGTCP2_FRAME_CRYPTO`) and stream frames (`NGTCP2_FRAME_STREAM`) have both a varying number of elements that contain the frame data which are stored in vectors (`ngtcp2_vec` in `ngtcp2_stream`). Discriminating between small and large frames is based on the number of elements. When a new frame is needed, based on the number of elements, the memory is pulled either from the custom memory allocator (large frame) or from the pool (small frame).

```
int ngtcp2_frame_chain_stream_datacnt_objalloc_new(ngtcp2_frame_chain **pfrc,
                                                   size_t datacnt,
                                                   ngtcp2_objalloc *objalloc,
                                                   const ngtcp2_mem *mem) {
  size_t need, avail = sizeof(ngtcp2_frame) - sizeof(ngtcp2_stream);

  if (datacnt > 1) {
    need = sizeof(ngtcp2_vec) * (datacnt - 1);

    if (need > avail) {
      return ngtcp2_frame_chain_extralen_new(pfrc, need - avail, mem);  <----- Large frame allocated via the custom memory allocator
    }
  }

  return ngtcp2_frame_chain_objalloc_new(pfrc, objalloc);   <----- Small frame popped from the pool
}

```
Similarly, when a frame is released, based on the number of elements, its memory is either given back to the pool or to the custom memory allocator.

```
void ngtcp2_frame_chain_objalloc_del(ngtcp2_frame_chain *frc,
                                     ngtcp2_objalloc *objalloc,
                                     const ngtcp2_mem *mem) {
  ngtcp2_frame_chain_binder *binder;

  if (frc == NULL) {
    return;
  }

  switch (frc->fr.type) {
  case NGTCP2_FRAME_CRYPTO:
  case NGTCP2_FRAME_STREAM:
    if (frc->fr.stream.datacnt &&
        sizeof(ngtcp2_vec) * (frc->fr.stream.datacnt - 1) >
            sizeof(ngtcp2_frame) - sizeof(ngtcp2_stream)) {
      /* Large frame released via the custom memory allocator. */
      ngtcp2_frame_chain_del(frc, mem);  <----- Large frame released via the custom memory allocator

      return;
    }

    break;
  case NGTCP2_FRAME_NEW_TOKEN:
    if (frc->fr.new_token.tokenlen >
        sizeof(ngtcp2_frame) - sizeof(ngtcp2_new_token)) {
      ngtcp2_frame_chain_del(frc, mem);

      return;
    }

    break;
  }

  binder = frc->binder;
  if (binder && --binder->refcount == 0) {
    ngtcp2_mem_free(mem, binder);
  }

  frc->binder = NULL;

  ngtcp2_objalloc_frame_chain_release(objalloc, frc);  <----- Small frame pushed back into the pool
}

```
In the end, allocation is symmetric: frames popped from the pool are always pushed back into the pool and frames allocated via the custom allocator are always released via the custom allocator.

But this is true as long as the number of elements (`datacnt`) in a frame does not change, which does not seem to be the case. For example, in `ngtcp2_strm_streamfrq_pop()`, frame vectors can be merged (`ngtcp2_vec_merge`), thus resetting the number of elements (`nfr->datacnt`) in the source frame.

```
int ngtcp2_strm_streamfrq_pop(ngtcp2_strm *strm, ngtcp2_frame_chain **pfrc,
                              size_t left) {
    <snip snip>
    nmerged = ngtcp2_vec_merge(a, &acnt, nfr->data, &nfr->datacnt, left,    <----- Vectors merged (nfr->datacnt becomes 0)
                               NGTCP2_MAX_STREAM_DATACNT);
    if (nmerged == 0) {
      rv = ngtcp2_ksl_insert(strm->tx.streamfrq, NULL, &nfr->offset, nfrc);
      if (rv != 0) {
        assert(ngtcp2_err_is_fatal(rv));
        ngtcp2_frame_chain_objalloc_del(nfrc, strm->frc_objalloc, strm->mem);
        ngtcp2_frame_chain_objalloc_del(frc, strm->frc_objalloc, strm->mem);
        return rv;
      }
      break;
    }

    datalen += nmerged;
    left -= nmerged;

    if (nfr->datacnt == 0) {
      fr->fin = nfr->fin;
      ngtcp2_frame_chain_objalloc_del(nfrc, strm->frc_objalloc, strm->mem);   <----- Frame wrongfully pushed into the pool
      continue;
    }

```
If that source frame was a large frame (and allocated via the custom allocator), then it becomes a small frame after the merge (`datacnt` is 0) and pushed wrongfully into the object pool upon release (`ngtcp2_frame_chain_objalloc_del`) instead of being released via the custom allocator.

In the end, those frames allocated via the custom allocator and wrongfully pushed into the pools end up as memory leaks.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  The current plan for the fix is create new ngtcp2_frame_chain if ngtcp2_frame_chain is large and datacnt goes less than the threshold.
