### ISSUE TITLE
ngtcp2_pkt_adjust_pkt_num is wrong?

### ISSUE THREAD

**Issue by relaxisland** [ngtcp2/ngtcp2#125]
thanks for sharing the good project.
It seems that the logic of ngtcp2_pkt_adjust_pkt_num is not consistent with quic doc(draft-ietf-quic-transport-18.pdf).
actually, running the case blow has  a wrong result.
package with pkn 250 comes after pkn 255，it will be adjusted to 506 by the function.
#the lenth of pkt num is  1byte = 8bits。
-----------------------
  int64_t k = max_pkt_num == NGTCP2_MAX_PKT_NUM ? max_pkt_num : max_pkt_num + 1;
  int64_t u = k & ~(((int64_t)1 << n) - 1);
  int64_t a = u | pkt_num;
  int64_t b = (u + (1ll << n)) | pkt_num;
  int64_t a1 = k < a ? a - k : k - a;
  int64_t b1 = k < b ? b - k : k - b;
-->result: a= 506 b =762.
both are wrong.

**Comment by tatsuhiro-t** [comment]
Thank you for telling me this issue.  It was fixed via commit 3893e15dc655b11fc88072a0978925cfbc9cfb6e
