### ISSUE TITLE
How to do "immediate close" for closing connection?

### ISSUE THREAD

**Issue by adikabintang** [ngtcp2/ngtcp2#126]
I am trying ngtcp2 on branch `draft-20`. As far as I understand, the example client and server use "idle timeout" for connection termination ([connection termination on RFC draft 20](https://tools.ietf.org/html/draft-ietf-quic-transport-20#section-10)). 

How to do "immediate close" the right way?

If I put `c->disconnect();` in `client.cc` function `int stream_close()` on line 637, it *resembles* immediate close method, but I am not sure if this is the correct way (most likely it *is not* the correct way).

**Comment by tatsuhiro-t** [comment]
Call ngtcp2_conn_write_conneciton_close (or ngtcp2_conn_write_application_close) to produce the packet which includes CONNECTION_CLOSE (or APPLICATION_CLOSE), and store it for a while and respond with it against any incoming packet to the closed connection.

**Comment by adikabintang** [comment]
I have tried adding `ngtcp2_conn_write_application_close` in function `Client::on_stream_close()`. It works, i.e., the client enters closing state after sending `CONNECTION_CLOSE` frame and the server enters draining state after receiving that `CONNECTION_CLOSE` frame. However, sometimes the server didn't receive that `CONNECTION_CLOSE` frame, and the function `retransmitcb()` is called by the server yet the client has stopped.

How to deal with this? Or my approach in adding `ngtcp2_conn_write_application_close` in function `Client::on_stream_close()` is wrong in the first place?

**Comment by tatsuhiro-t** [comment]
If you want to handle packet loss, client has to send copy of a packet containing CONNECTION_CLOSE in response to packets from server for a while, just like TCP does in FIN_WAIT.  I think examples/client does not have this feature.

**Comment by tatsuhiro-t** [comment]
Closing because there is no new information available for quite a long time.
