### ISSUE TITLE
Bug in fc2129450303bb3ac38e2b7b00e319c59c747807

### ISSUE THREAD

**Issue by crytaljin** [ngtcp2/ngtcp2#1281]
Our most recent ngtcp2/nghttp3 upgrade caused our app to enter a state where requests hang. From debugging I saw that response headers are received but are unable to be processed due to QPACK decode being blocked. I originally thought this was an http3 bug and posted https://github.com/ngtcp2/nghttp3/issues/244 but after bisecting I found that it is fc2129450303bb3ac38e2b7b00e319c59c747807 that's causing the issue.

**Comment by tatsuhiro-t** [comment]
Thank you for finding the bug.  It looks like I failed to update psl when an element is removed.
