### ISSUE TITLE
Pass enums as ints to callbacks?

### ISSUE THREAD

**Issue by DaanDeMeyer** [ngtcp2/ngtcp2#132]
I'm wrapping ngtcp2 in a C++ class. The ngtcp2 class takes an implementation class as a parameter which implements all the required ngtcp2 callbacks. This implementation class is passed as the `userdata` pointer to ngtcp2. The list of callbacks passed to ngtcp2 consists of static functions which first transform the callback parameters to idiomatic C++ types before calling the corresponding method on the implementation class.

The problem with this approach is that all the callback implementation methods in the implementation class have to be public so they can be called directly from the static functions. I want to get around this by making all the static functions static methods of the ngtcp2 class instead and making the ngtcp2 class a friend of the implementation class. This allows all the callbacks methods of the implementation class to be made private.

However, this requires me to put all the static method declarations in the class header file (vs static functions declared and defined in the source file). This wouldn't be a problem if I could forward-declare all of the types used in the ngtcp2 callbacks (and I can forward-declare most of them) except I cannot forward-declare ngtcp2 enums in the header file. This means I have to include the ngtcp2.h header in the ngtcp2 class header files in order to be able to declare the static methods which I want to avoid since I don't want ngtcp2's API leaking into other parts of my code that use the ngtcp2 class.

A solution to this is using int instead of specific enums when passing enum values to callbacks. This allows the static methods to be declared in the ngtcp2 class header file without including the ngtcp2.h header. This is already done in for many enums (such as the error enum) but a few enums (such as `ngtcp2_crypto_level`) are still passed directly as the enum type.

Would you be willing to merge a pull request changing all enum usages in callbacks to ints to make wrapping of ngtcp2 easier?

**Comment by DaanDeMeyer** [comment]
More specifically, one occurrence of `ngtcp2_path_validation_result`, one occurrence of `ngtcp2_rand_ctx` and 3 occurrences of `ngtcp2_crypto_level` would have to be changed to int.

**Comment by DaanDeMeyer** [comment]
I've made #133 to show the necessary changes.

**Comment by tatsuhiro-t** [comment]
I'm not sure this is the way to go.
While this change might help your particular implementation, I think using enum type is better than bare int type.  Actually enum can be greater than int.  If a enum changes from int to, say, uint64_t, it would be painful to track the changes if a parameter is of type int.
QUIC error code is extensible and application can define their own value, so I use uint64_t for them.  For other enums and if they have limited number of values, I would use enum rather than int.

**Comment by DaanDeMeyer** [comment]
Another possible solution is to declare the enums with a fixed type if the ngtcp2 header is included in C++ code. This allows the enum to be forward declared in C++ headers without including the ngtcp2 header.

```
#ifdef __cplusplus
enum ngtcp2_crypto_level : int
#else
enum ngtcp2_crypto_level
#endif
```

Of course, this assumes the underlying type used by the compiler is int (which probably can be forced by adding an INT_MAX value to the enum).

Is this a more viable solution?

**Comment by tatsuhiro-t** [comment]
I'm fine to add maximum value to ensure the size of enum.  For ngtcp2_transport_error, NGTCP2_TRANSPORT_ERROR_MAX = UINT64_MAX ensures that it is of type uint64_t.  I think this is necessary  because without it, adding larger value requires recompilation.
It is only necessary if value range goes beyond default int type.

**Comment by DaanDeMeyer** [comment]
Would you also be willing to add the specific size declarations if `__cplusplus` is defined? To forward declare the enum in C++ headers, the enum definition needs the size declaration as well (`enum ngtcp2_crypto_level : int`) has to be in the ngtcp2 C header.

**Comment by tatsuhiro-t** [comment]
Isn't it enum class C++11 or later version specific?  Do we need to guard C++ standard version?

**Comment by DaanDeMeyer** [comment]
We don't have to use enum class, type specifiers can be used with normal C++ enums. However, you are right that enum type specifiers were added in C++11. If you want to support C++ versions before C++11 a check on the version would also be necessary.

**Comment by tatsuhiro-t** [comment]
How can type specifiers be used with legacy C++ enums?   It seems that it is just like C enums and there is no room to specify the type.

**Comment by DaanDeMeyer** [comment]
```
enum test : int {
  A,
  B,
  C
};
```

This is valid C++. It just forces the compiler to use that type as the underlying type for the enum. I don't think there's any issues as long as we use the same type the compiler would use when compiling without the type specifier.

**Comment by tatsuhiro-t** [comment]
Compiler complains that it is ISO C++ 2011 standard:

```
In file included from /usr/include/c++/8/cstdint:35,
                 from sample.cc:1:
/usr/include/c++/8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^~~~~
sample.cc:7:13: warning: scoped enums only available with -std=c++11 or -std=gnu++11
 enum test : int {
```

I think It might be fine just define enum type for C++11 or later.  I need to find a macro to detect it though.

**Comment by DaanDeMeyer** [comment]
https://stackoverflow.com/a/29407260

`__cplusplus` is actually set to a specific value depending on the supported standard so you can just check on that.

**Comment by tatsuhiro-t** [comment]
Yeah, thanks.  I got the same answer from SO.

**Comment by tatsuhiro-t** [comment]
It looks like it does not work because enum Foo vs Foo:
```
typedef redefinition with different types ('enum ngtcp2_transport_error' vs 'ngtcp2_transport_error')
```

**Comment by tatsuhiro-t** [comment]
The following code works.  It looks a bit ugly though.
```c
#if defined(__cplusplus) && __cplusplus >= 201103L
enum ngtcp2_frame_type : uint64_t {
#else
enum ngtcp2_frame_type {
#endif
  NGTCP2_FRAME_PADDING = 0x00,
  ...
  NGTCP2_FRAME_TYPE_MAX = UINT64_MAX
};

typedef enum ngtcp2_frame_type ngtcp2_frame_type;
```

**Comment by DaanDeMeyer** [comment]
Maybe a macro helps:

```c++
#if defined(__cplusplus) && __cplusplus >= 201103L
#define NGTCP2_ENUM(name, type) enum name : type
#else
#define NGTCP2_ENUM(name, type) enum name
#endif
```

Usage:

```c++
NGTCP2_ENUM(ngtcp2_frame_type, uint64_t) {
  NGTCP2_FRAME_PADDING = 0x00,
  ...
  NGTCP2_FRAME_TYPE_MAX = UINT64_MAX
}
```

**Comment by tatsuhiro-t** [comment]
I added enum specifier in e485a28e75170bc833d7fc77afd332fee60f612f
macro is nice but clang-format does not like it.  I ended up writing it without macro.

**Comment by DaanDeMeyer** [comment]
It works as expected. Thanks!

The macro looks a lot better if added to the `ForEachMacros` list in clang-format style options but still not perfect.
