### ISSUE TITLE
Compiling for embedded systems

### ISSUE THREAD

**Issue by vipera** [ngtcp2/ngtcp2#1334]
Hi! I'm trying to compile ngtcp2 for an embedded system running FreeRTOS, and have run into a few minor setbacks, one of which is the ngtcp2_unreachable unit trying to use STDERR_FILENO. After a short look, it seems beneficial to be able to conditionally include the body of the function that prints to stderr, and that would be a fix.

I'm wondering whether you can advise me on whether it would be appropriate exclude this part with DEBUGBUILD, HAVE_UNISTD_H or you think another flag would be more appropriate. I can submit a PR, if that's more convenient.

Apart from this, [crypto/shared.c](../blob/master/crypto/shared.c) includes `netinet/in.h` unconditionally. I'm not using the library as a cmake dependency right now, although that would be more practical for the crypto bindings, but these two issues seem unrelated to this.

Thanks for your time!

**Comment by tatsuhiro-t** [comment]
I am not sure I understand the exact issue, but FreeRTOS lacks STDERR_FILENO definition, and it leads to compile error, is that correct?  Is just defining STDERR_FILENO to 2 fix your issue?

**Comment by tatsuhiro-t** [comment]
Right, so the fix is use write only when we have unistd.h otherwise do nothing.

**Comment by vipera** [comment]
Ok, thanks for your feedback, I've opened a PR with the suggested change.
