### ISSUE TITLE
server-example: "ipi_spec_dst" vs "ipi_addr"

### ISSUE THREAD

**Issue by doublex** [ngtcp2/ngtcp2#1338]
IPv4 references `ipi_spec_dst` ("Header Destination address")
IPv6 references `ipi6_addr` ("Local address") of IP_PKTINFO
Is it intentional? 

https://github.com/ngtcp2/ngtcp2/blob/main/examples/server.cc#L3108
````c
pktinfo.ipi_spec_dst = addrin->sin_addr;
````

https://github.com/ngtcp2/ngtcp2/blob/main/examples/server.cc#L3120
````c
pktinfo.ipi6_addr = addrin->sin6_addr;
````

**Comment by tatsuhiro-t** [comment]
The name is quite misleading but
https://man7.org/linux/man-pages/man7/ip.7.html
> ipi_spec_dst is the local address of the packet

**Comment by doublex** [comment]
I was unclear in my wording.
IPv4 and IPv6 reference a different item `ipi_spec_dst` (v4) and `ipi_addr` (v6).

**Comment by tatsuhiro-t** [comment]
ipv4 and ipv6 are quite different in detail.
See https://datatracker.ietf.org/doc/html/rfc3542.html#section-6

**Comment by doublex** [comment]
Ohh.
Again, sorry for the inconvenience
