### ISSUE TITLE
Stack buffer

### ISSUE THREAD

**Issue by doublex** [ngtcp2/ngtcp2#1371]
Could you check this line:
https://github.com/ngtcp2/ngtcp2/blob/main/crypto/shared.c#L1055

ASAN reported "stack-buffer-overflow" due to misconfiguration (my fault).
Input-buffer size: 45 bytes
Output-buffer size: 29 bytes

Question:
Could a specially crafted verify-token also cause a stack-buffer-overflow?

**Comment by tatsuhiro-t** [comment]
The library only accepts a token of length NGTCP2_CRYPTO_MAX_RETRY_TOKENLEN bytes.

As for 45 vs 29 bytes, the former is exactly 16 bytes long, which is the length of AEAD tag.  In AEAD ciphers that QUIC supports, ciphertext is exactly 16 bytes longer than plaintext.
Which TLS backend are you using?  I do not know the ones that produce plaintext with the same length of ciphertext.

**Comment by doublex** [comment]
Thank you for the review. 
Backend: `picotls` with `mbedtls`
As said: There was a misconfiguration (server vs client).
