### ISSUE TITLE
examplees/util.cc build error

### ISSUE THREAD

**Issue by jorenwu84** [ngtcp2/ngtcp2#138]
# git branch
* draft-22
=======error info==============
util.cc:262:27: error: 'strlen' was not declared in this scope
  262 |   res.append(host.data(), strlen(host.data()));
      |                           ^~~~~~
util.cc:40:1: note: 'strlen' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
   39 | #include <iostream>
  +++ |+#include <cstring>
   40 | 
make[2]: *** [util.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/joren/ngtcp2/examples'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/joren/ngtcp2'
make: *** [all] Error 2

**Comment by tatsuhiro-t** [comment]
I think this has been fixed in main branch.
