### ISSUE TITLE
Unable to reach ng maintainers through regular channels. (ngtcp2, nghttp3, nghttp2, aria2)

### ISSUE THREAD

**Issue by OSTIF-Derek** [ngtcp2/ngtcp2#1384]
Hello,

First of all I apologize for putting this here. This is my last resort attempt to reach out.

I have a unique problem that isn't code/docs related. I'm the founder of https://ostif.org and we are trying to reach the maintainers for nghttp3 and ngtcp2 to discuss a security audit of the projects. This process is mostly hands off for the maintainers, but we want to ensure that we are including the communities input directly when we are considering how to scope the review so that what we do is as helpful as possible, and also give the maintainers the option of participating if they'd like to, and just inform the project that we're doing this work. It's completely free and participation is optional.

We've tried reaching out in the past for Aria2 and nghttp2 but were unable to find any direct lines of communication with the lead contributor, and the nghttp2.org website also does not have any contact info. I understand the reasons for not broadcasting this information to the public, but we would like to get in touch. I can be reached directly at firstname at my orgs domain for email, I'm also happy to attend meetings or any other avenue for communication.

Finally, thanks for building and maintaining these awesome libraries!

Please reach out to me so we can collaborate!

**Comment by tatsuhiro-t** [comment]
You can find my e-mail address in git log.  See the e-mail attached to "Tatsuhiro Tsujikawa"
