### ISSUE TITLE
ngtcp2_conn_read_pkt: ERR_DRAINING

### ISSUE THREAD

**Issue by vunhatminh241191** [ngtcp2/ngtcp2#139]
I followed these steps you guys mention in the README, under branch draft-22 and successfully installed it. I am trying to use h2load from nghttp2 under QUIC protocol by using this command
`./h2load --npn-list=h3-22 -c 100 -n 1000 --log-file=/var/log/testing_h2load.log https://10.13.0.220:8443/index.html`

And I got 2 errors:
   1. ngtcp2_conn_read_pkt: ERR_DRAINING
   2. It looks like h2load will hang in there forever to waiting for response and it never close these connections.

Do you guys have any idea what is going on?
Note: My server supports draft-22 version

**Comment by tatsuhiro-t** [comment]
ERR_DRAINING means h2load received CONNECTION_CLOSE frame from server.  Do you see any error in server side?
The current recovery draft-22 spec of QUIC has a defect that the handshake fails if packet is lost in a certain pattern.  It is best to increase UDP packet receive buffer kernel parameters: net.core.rmem_max and net.core.rmem_default.

**Comment by vunhatminh241191** [comment]
I am trying to increase the UDP packet buffer by the following command:
`sudo sysctl -w net.core.rmem_max=26214400000
  sudo sysctl -w net.core.rmem_default=26214400000`

However, when I tried the previous ./h2load command, it still has the same error.
In the server side, I am using docker and I double check my nginx log, it does not have catch any error.

**Comment by EasyCoderWei** [comment]
> 

By testing with the latest version of h2load, I found the relationship between parameters.
According to the following parameter relationship, it wouldn't occur the error infomation "ngtcp2_conn_read_pkt: ERR_DRAINING".

n' = n / m
n' / c <= 500 : 1
