### ISSUE TITLE
Low cwnd is used when sending small POST requests after commit 702ba868

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#1399]
To reproduce:
```
mkfile -n 500 /tmp/file

git checkout 702ba86873d9f8783e5e2446cfd70f24a67a4862
make
./examples/bsslclient --no-http-dump -m POST -n 10000 --max-streams-bidi 1 -d /tmp/file nghttp2.org 4433 https://nghttp2.org:4433 2>&1 | grep cwnd

git checkout a57d939208d509eb27cc82124a5c1b5b071f6c5f
make
./examples/bsslclient --no-http-dump -m POST -n 10000 --max-streams-bidi 1 -d /tmp/file nghttp2.org 4433 https://nghttp2.org:4433 2>&1 | grep cwnd
```

Observe that on 702ba868 a significantly lower cwnd is used. E.g. on my setup it stabilizes at around 50K, while on a57d9392 it keeps growing.

The issue also reproduces on the latest main (c0ed7969) and may be even somewhat worse.

**Comment by tatsuhiro-t** [comment]
If application does not fully utilize cwnd, and the transport is under app-limited (e.g., waiting for flow control credit), cwnd is not extended.

**Comment by amirlivneh** [comment]
Note that before 702ba868, the cwnd was in fact extended in the same scenario. See reproduction steps.

What I try to reproduce in this test is an issue we're seeing in production. The cwnd of organic production traffic is about 10x lower starting from the version that contains 702ba868 and there are some performance regressions as well. However, there are other changes in that version, so there is no proof that this change is to blame.

A hypothesis I had is that when an HTTP/3 connection is reused for multiple requests, if requests that don't fully utilize cwnd cause an extension of the cwnd (as was the case before 702ba868), later requests with a large body can benefit from the higher cwnd on that connection.

**Comment by tatsuhiro-t** [comment]
Before 702ba86, cubic does not take into account app-limited phase.  CUBIC RFC 9438 says it should not extend cwnd if it is under app-limited and cwnd is not fully utilized: https://datatracker.ietf.org/doc/html/rfc9438#section-5.8

In your scenario, if the first HTTP/3 request has no request body and not utilize full cwnd, cwnd should not be extended if we follow what RFC says.  Increase cwnd if the following requests starts using cwnd to the max.

If this behavior significantly different form tcp (h2), I need to consider changing it, but that deviates RFCs or my understanding is wrong somewhere.  RFC 9002 also says do not increase cwnd in this situation: https://datatracker.ietf.org/doc/html/rfc9002#section-7.8

Do you think we should ignore this guidance and just increase cwnd under app-limited phase as well?

**Comment by amirlivneh** [comment]
In my opinion we should deviate from the RFC only as a last resort. I suggest to first confirm using an A/B test that doing so is in fact beneficial in the real world. Is it possible to temporarily make the the behavior in question configurable so we can experiment with it?

**Comment by tatsuhiro-t** [comment]
Comment out https://github.com/ngtcp2/ngtcp2/blob/c0ed796950a724abf1070a5f365fe99ff9f43861/lib/ngtcp2_cc.c#L260-L276
now cubic ignores app-limited signal.

**Comment by tatsuhiro-t** [comment]
FYI https://github.com/torvalds/linux/blob/850925a8133c73c4a2453c360b2c3beb3bab67c9/include/net/tcp.h#L1375-L1379
linux also does not increase cwnd if it is not underutilized, but in slow-start, linux increases cwnd if it uses the half of cwnd.

**Comment by crytaljin** [comment]
@tatsuhiro-t Thank you for pointing us to the code block for the app limited condition. We experimented with disabling that block on client side (mobile- iOS and Android) and there are improvements in request duration and upload latency. We will be disabling this block in our copy, but it's up to you whether you want to differ from the RFC/Linux behavior by default in ngtcp2.

**Comment by tatsuhiro-t** [comment]
I made a change to make app-limited phase not restrict CWND severely.  It might fix your issue.

**Comment by amirlivneh** [comment]
Thank you.
