### ISSUE TITLE
ngtcp2 occasionaly fails to parse QUIC helo packet with error: ngtcp2_conn_read_pkt: ERR_CRYPTO

### ISSUE THREAD

**Issue by vranem1** [ngtcp2/ngtcp2#1403]
### Detailed Description of the Problem
In our quic-interop test setup we've observed that ngtcp2 server sometimes fails to parse QUIC client helo packet, which makes some tests shaky. The initial packet (by design) consists of various number of QUIC frames. Depending on the packet layout the parsing is or is not successful. I've attached an example of [failing.pcap.zip](https://github.com/user-attachments/files/17621329/failing.pcap.zip), which ngtcp2 implementation fails to parse, but other server are successful in procesing it. The packet was generated by a client based on Chromium source code, so I belive the structure matches the QUIC standard.

### Steps to reproduce
1) Run the server. In my case I've used the quic-interop docker image to run it
```
docker run -p 127.0.0.1:4433:4433/udp -v $PWD/www:/www -v $PWD/logs:/logs  -v ${PWD}/certs:/certs  -v ${PWD}/my_run_endpoint.sh:/run_endpoint.sh  -e ROLE=server -e TESTCASE=http3 ghcr.io/ngtcp2/ngtcp2-interop
```
2) (as root)Send the problematic QUIC helo-packet from the attached pcap using the Python scapy script.
```
from scapy.utils import rdpcap
reader = PcapNgReader("failing.pcap")
for i in reader:
    p = i[IP]
    p.dport = 4433
    p.dst = "127.0.0.1"
    p[UDP].chksum=0
    p.display()
    send(p)
```
3) Inspect the server log, which unexpectedly ends with:
```
ngtcp2_conn_read_pkt: ERR_CRYPTO
Closing period has started (0.9 seconds)
I00000001 0xbc4786094f183aabe191caf34916399c3590 pkt tx pkn=1821265201 dcid=0x scid=0xbc4786094f183aabe191caf34916399c3590 version=0x00000001 type=Initial len=0
I00000001 0xbc4786094f183aabe191caf34916399c3590 frm tx 1821265201 Initial CONNECTION_CLOSE(0x1c) error_code=CRYPTO_ERROR(0x100) frame_type=0 reason_len=0 reason=[]
mask=1bdb6d8945 sample=3ed000137e5f68241752a30adcdd9d4f
Closing Period: TX CONNECTION_CLOSE
Sent packet: local=[172.16.0.1]:4433 remote=[172.16.0.5]:40691 ecn=0x0 55 bytes
0xbc4786094f183aabe191caf34916399c3590 Closing QUIC connection 
```

### Expected behaviour
The packet is successfuly processed

### Actual behaviour:
The packet is rejected by the server and the connection is closed

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  The interop image uses wolfssl, and I could only reproduce this with wolfssl.  This is wolfssl issue.
By glancing at wolfssl source code, https://github.com/wolfSSL/wolfssl/blob/8ecf0643144e8430a6ea0eb16e137dbafb5112c8/src/quic.c#L158 is suspicous.

In wolfssl, 0 is not successful return code, perhaps inheriting openssl practice.  I think it should be `goto cleanup` or something.
It would be nice to report this to wolfssl.
