### ISSUE TITLE
Want-write

### ISSUE THREAD

**Issue by doublex** [ngtcp2/ngtcp2#1411]
Situation: 
`ngtcp2`-client connects to an nginx-server with super-high packet loss (due reloading nginx without 'bpf')

Issue: `ngtcp2`-connection is queued for writing in future, but `ngtcp2` reports 'want-write'.
Want-write means: 
````c 
nghttp3_conn_writev_stream(): true
ngtcp2_conn_get_max_data_left() != 0
ngtcp2_conn_get_cwnd_left() != 0
if(stream_id != -1): ngtcp2_conn_get_max_stream_data_left(stream_id) != 0
````    
My guess is that `ngtcp2` wants to retransmit some lost packets.
    
Test:
````c
quic_settings.handshake_timeout = 3600 * NGTCP2_SECONDS;    // very high
quic_settings.initial_rtt = NGTCP2_NANOSECONDS;     // very low
[...]
ngtcp2_tstamp expiry = ngtcp2_conn_get_expiry( quic_conn );
````

Gotten `expiry`: close to 3600s
Expected `expiry`: time of next retransmission of lost packets - quite recent due to low `initial_rtt`

Have I got something wrong?

**Comment by tatsuhiro-t** [comment]
It is unclear to me how to reproduce this.
Could you describe more detail about how to reproduce this issue with ngtcp2 client (e.g, qtlsclient)?

**Comment by doublex** [comment]
Yes, sorry. To create a test-case, two questions about `ngtcp2` internals.
`ngtcp2` is used as client. 

a) Suspected: Lost packet retransmission is also initiated by the client 
(without a retransmission command from the server)
b) Suspected: `ngtcp2_conn_get_expiry()` returns the time of the next retransmission

Nobody abstracts protocols as brilliantly as you do (by the way).
Best wishes from Vienna!

**Comment by tatsuhiro-t** [comment]
a) client retransmits whatever it should resend.  I am not sure how to interpret "without a retransmission command from the server".  There is no such command in quic protocol.

b) ngtcp2_conn_get_expiry returns the earliest timestamp that when it is expired, application must call ngtcp2_conn_handle_expiry.  It is not limited to retransmission.

Thank you for you words, that encourages us to continue to work on this project.

**Comment by doublex** [comment]
Sorry, I was on the wrong track.
After adding some "debug with printf()", the down below `printf()` triggered.
Is there a case where `nwrite == 0` but not 'congestion limited'?

````c
assert( buflen == 1452 );
ngtcp2_ssize nwrite = ngtcp2_conn_writev_stream( quic_conn,
    &path_storage.path, &pi, offset, buflen, &ndatalen,
    NGTCP2_WRITE_STREAM_FLAG_MORE, stream_id, (const ngtcp2_vec*)vec, sveccnt, nanotime() );
if( nwrite == 0 &&
    ngtcp2_conn_get_max_data_left(quic_conn) != 0 &&
    ngtcp2_conn_get_cwnd_left(quic_conn) != 0 )
{
    // not want-write
    int64_t stream_id = -1;
    int fin = 0;
    nghttp3_vec vec[16];
    nghttp3_ssize sveccnt = nghttp3_conn_writev_stream( http3_conn, &stream_id, &fin, vec, ARRAY_LENGTH(vec) );
    if( sveccnt != 0 )
    {
        if( stream_id == -1 || ngtcp2_conn_get_max_stream_data_left(quic_conn, stream_id) != 0 )
            printf("huh: ngtcp2 wants write\n" );
    }
}
````

**Comment by doublex** [comment]
Sorry for wasting your time.
`fin != 0`

**Comment by doublex** [comment]
Sorry for the re-opening of this issue.
`printf("ngtcp2 wants write")` happens with `fin == 0` and `fin != 0`.
Did I miss a case in the pseudo-code above?

**Comment by doublex** [comment]
One reason that `ngtcp2_conn_writev_stream()` returns `nwrite == 0` even if not congestion limited is `ngtcp2_acktr_require_active_ack` in `ngtcp2_conn_create_ack_frame` (`ackfr` remains `NULL`):
  
````c
// 1
ngtcp2_ssize conn_write_ack_pkt(...)
{
  nwrite = ngtcp2_conn_write_vmsg(conn, path, pkt_info_version, pi, dest,
                                  destlen, vmsg, ts);

// 2                                
int ngtcp2_conn_create_ack_frame(...) 
{
  ackfr = NULL;
  rv = ngtcp2_conn_create_ack_frame(conn, &ackfr, pktns, type, ts, ack_delay, ack_delay_exponent);
  if (rv != 0) {
    return rv;
  }
  if (!ackfr) {
    return 0;
  }

// 3
int ngtcp2_acktr_require_active_ack(...) 
{
  if (!ngtcp2_acktr_require_active_ack(acktr, ack_delay, ts)) {
    return 0;
  }

// 4
int ngtcp2_tstamp_elapsed(ngtcp2_tstamp base, ngtcp2_duration d, ngtcp2_tstamp ts)
{
  // base = 21269449894341719
  // d    = 404515
  // ts   = 21269449894643414
  // (base + d <= ts)    -> 0
  return base != UINT64_MAX && base < UINT64_MAX - d && base + d <= ts;
````

**Comment by tatsuhiro-t** [comment]
ngtcp2_conn_writev_stream returns 0 if it has nothing to send.
It is not clear to me what you are discussing in this thread.
Please write down like:

1. What you did
2. What you got
3. What you expected instead
4. How to reproduce the issue

**Comment by doublex** [comment]
Got it.
There are a number of reasons for "nothing to send" - not just "congestion limited".
Sorry for any inconvenience.
