### ISSUE TITLE
http-parser still imported in server.cc

### ISSUE THREAD

**Issue by crytaljin** [ngtcp2/ngtcp2#1437]
Just wondering why is http-parser still imported in [server.cc](https://github.com/ngtcp2/ngtcp2/blob/624863a43e418c701725d0c9504c2d33c731c9d9/examples/server.cc#L47) after [624863a](https://github.com/ngtcp2/ngtcp2/commit/624863a43e418c701725d0c9504c2d33c731c9d9?fbclid=IwZXh0bgNhZW0CMTEAAR2DI14EGqRkpCPOyuWlvClbfFZbx8rHt2tQDyiqj0wiJituAkiJwBmzlvY_aem_Gq5qxXqtnHZcMUz2OKKNtQ#diff-76e715a9e756e801193429538c1cea6cd190fa8e48f4c94fd46594d813eb4966L2238) replaced it? It seems to compile and run if I remove the import.

**Comment by tatsuhiro-t** [comment]
Thanks.  That is most likely an oversight when replacing it with urlparse.
