### ISSUE TITLE
Merge OpenSSL patch fork to origin

### ISSUE THREAD

**Issue by Sakirnth-Z** [ngtcp2/ngtcp2#144]
Hi,

I am packaging ngtcp2 for Debian. It would be helpful when the OpenSSL patch would be in the original OpenSSL repository. When are you consider to start a merge request to OpenSSL upstream?

Thanks and Cheers
Saki

**Comment by bagder** [comment]
There's something of a consensus going that the official QUIC work for OpenSSL is being done in [OpenSSL PR 8797](https://github.com/openssl/openssl/pull/8797) which is a different take than @tatsuhiro-t's OpenSSL patch.

**Comment by tatsuhiro-t** [comment]
It is best to wait for OpenSSL PR 8797 to be merged at the moment.
Part of my patch (removal of EOED and enabling 0RTT) might useful for OpenSSL, but currently it is very hard to collaborate with the PR because it is under the corporate account.

**Comment by Sakirnth-Z** [comment]
Ok, I will wait until the OpenSSL PR 8797 is merged.

Sakirnth

**Comment by tatsuhiro-t** [comment]
I abandoned my custom OpenSSL and switched to https://github.com/quictls/openssl/
