### ISSUE TITLE
Aborted and core dumped in conn_recv_ack

### ISSUE THREAD

**Issue by matsumito** [ngtcp2/ngtcp2#1440]
Assert and coredump with below stack. (num_acked value is -201 from coredump)
1. Why does this assert happen? and what is the suggested way to avoid it?
2. If there are multiple quic sessions towards different end points, why is it that a single session hitting this case should result in assert and coredump of process / full system?
3. Is there any API(or any other way) to not coredump and instead tear down the problematic quic session?

#4  0x00007bbb8e1123d7 in __assert_fail_base [__assert_fail_base.c...] (
    fmt=0x7bbb8e2821a0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7bbb8e00ad9d "ngtcp2_err_is_fatal((int)num_acked)", 
    file=file@entry=0x7bbb8e0076a6 "/lib/ngtcp2_conn.c", line=line@entry=5333, 
    function=function@entry=0x7bbb8e00adc1 "int conn_recv_ack(ngtcp2_conn *, ngtcp2_pktns *, ngtcp2_ack *, ngtcp2_tstamp, ngtcp2_tstamp)") at assert.c:92
#5  0x00007bbb8e11ff93 in __GI___assert_fail [__assert_fail] (
    assertion=0x7bbb8e00ad9d "ngtcp2_err_is_fatal((int)num_acked)", 
    file=0x7bbb8e0076a6 "/lib/ngtcp2_conn.c", 
    line=5333, 
    function=0x7bbb8e00adc1 "int conn_recv_ack(ngtcp2_conn *, ngtcp2_pktns *, ngtcp2_ack *, ngtcp2_tstamp, ngtcp2_tstamp)") at assert.c:101
#6  0x00007bbb8dfea7b1 in conn_recv_ack (conn=conn@entry=0x595dee5dd9b8, 
    pktns=pktns@entry=0x595dee5ddc38, fr=fr@entry=0xfffffcb7e41e70, pkt_ts=159358650608772, 
    ts=159358650608772)
    at /lib/ngtcp2_conn.c:5333
#7  0x00007bbb8dfe9928 in conn_recv_pkt (conn=conn@entry=0x595dee5dd9b8, 
    path=path@entry=0xfffffcb7e422b0, pi=pi@entry=0xfffffcb7e421e8, 
    pkt=pkt@entry=0x595dee677678 "I\v)\002M[\003\025\tXrt\177,\211\365\205N\355\370[\375\270\233~Ӎ\235\363܂.N\261\213)t\005\nX", pktlen=pktlen@entry=40, dgramlen=dgramlen@entry=40, 
    pkt_ts=159358650608772, ts=159358650608772)

**Comment by tatsuhiro-t** [comment]
Could you tell me which version are you using?

**Comment by matsumito** [comment]
Thankyou for quic response;
version is 1.4.0

**Comment by tatsuhiro-t** [comment]
Thank you.  Do you use 0 length STREAM data?  If so, #1441 fixes this bug.

**Comment by matsumito** [comment]
Yes; we do use 0 length STREAM data. Will try with this fix patch and update;

**Comment by matsumito** [comment]
This fix has worked. Crash is not seen even if sending 0 length STREAM data.
