### ISSUE TITLE
CONNECTION_CLOSE in Initial Packet

### ISSUE THREAD

**Issue by jasnell** [ngtcp2/ngtcp2#145]
Working through draft-22...

To support the SERVER_BUSY response, we need the ability to send CONNECTION_CLOSE in an initial packet, unfortunately `ngtcp2_conn_write_connection_close` returns `NGTCP2_ERR_INVALID_STATE` when attempting to write a connection close too early. It's not clear yet if this behavior has been implemented or is in progress so I wanted to check before digging into it.

**Comment by jasnell** [comment]
Pending resolution of: https://github.com/ngtcp2/ngtcp2/issues/145

**Comment by tatsuhiro-t** [comment]
It is allowed to send CONNECTION_CLOSE frame in Initial packet as long as ngtcp2_conn has initial key installed and it is not in closing or draining state.

**Comment by jasnell** [comment]
Hmm ok. I was hoping to avoid having to do any of that initial setup but it makes sense why we'd need the initial key. Thank you! :)
