### ISSUE TITLE
Out-of-order/on-demand stream creation

### ISSUE THREAD

**Issue by rsepassi** [ngtcp2/ngtcp2#1454]
IIUC nothing in the QUIC spec defines the order in which streams need to be created, but the ngtcp2 API forces applications to open streams in a particular order via `ngtcp2_conn_open_{uni,bidi}_stream`. Am I reading the ngtcp2 API correctly?

This makes it difficult to implement protocols that may pre-define a set of streams that carry different kinds of information, or protocols where a stream ID could carry some meaning on its own (e.g. a protocol that defines that data for some ID X should always be sent on stream X % 30).

Looking at another QUIC library like picoquic, I see no similar restriction. The stream id is passed in as a parameter for sending and is part of the callback in receiving. It'd be nice to have a similar non-restrictive option in ngtcp2. The receive path doesn't seem to have an issue, but for `ngtcp2_conn_writev_stream_versioned`, it would be nice if the `stream_id` parameter could be anything, and if it was a not-before-used id, then the library would transparently initialize it (with the caveat that it would be an error to use an id that exceeded the configured maximum values for that connection).

Looking at the code for stream id generation, it seems to rely on some private APIs so it seems that currently defining a new stream id can't be done in user space. Specifically `ngtcp2_objalloc_strm_{get,release}`, `ngtcp2_conn_init_stream`, and `ngtcp2_strm_shutdown`. It's also not clear to me what the internal semantics of `local.uni.next_stream_id` are; I think it's mostly only used here to assign the next id, but I think it's also used as a "maximum" value elsewhere, so that would need to be changed to independently track a maximum-seen id.

```c
int ngtcp2_conn_open_uni_stream(ngtcp2_conn *conn, int64_t *pstream_id,
                                void *stream_user_data) {
  int rv;
  ngtcp2_strm *strm;

  if (ngtcp2_conn_get_streams_uni_left(conn) == 0) {
    return NGTCP2_ERR_STREAM_ID_BLOCKED;
  }

  strm = ngtcp2_objalloc_strm_get(&conn->strm_objalloc);
  if (strm == NULL) {
    return NGTCP2_ERR_NOMEM;
  }

  rv = ngtcp2_conn_init_stream(conn, strm, conn->local.uni.next_stream_id,
                               stream_user_data);
  if (rv != 0) {
    ngtcp2_objalloc_strm_release(&conn->strm_objalloc, strm);
    return rv;
  }
  ngtcp2_strm_shutdown(strm, NGTCP2_STRM_FLAG_SHUT_RD);

  *pstream_id = conn->local.uni.next_stream_id;
  conn->local.uni.next_stream_id += 4;

  return 0;
}
```

What do you think?

P.S. Love the library! Thank you for writing it and keeping it so nicely documented and tidy.

**Comment by tatsuhiro-t** [comment]
https://datatracker.ietf.org/doc/html/rfc9000#section-2.1

> The stream space for each type begins at the minimum value (0x00 through 0x03, respectively); successive streams of each type are created with numerically increasing stream IDs. A stream ID that is used out of order results in all streams of that type with lower-numbered stream IDs also being opened.

Actually RFC 9000 says that stream is created in the order of increasing stream ID.
So basically, you cannot open a stream with arbitrary stream ID.  The number of streams that can be opened is restricted by the receiver.

**Comment by rsepassi** [comment]
Ah, thank you for pointing that out, I definitely missed it.
