### ISSUE TITLE
Reporting of error code from received connection_close

### ISSUE THREAD

**Issue by jasnell** [ngtcp2/ngtcp2#147]
It's entirely possible that I'm just missing it... but looking through the API, there appears to not be any way of accessing the error code given in a *received* CONNECTION_CLOSE. I'm easily able to detect that the connection has gone into draining but not able to see the actual code used. A simple API or informational `ngtcp2_connection_close()` callback would be helpful.

**Comment by tatsuhiro-t** [comment]
I'll add field to remember the received error code and add a function to return it.

**Comment by jasnell** [comment]
Thank you! :)

**Comment by tatsuhiro-t** [comment]
Add the API to get connection close error code.  See 65822561997129b6d7aa7af2bf1dd22e93c881e9

**Comment by jasnell** [comment]
Thank you! 😁
