### ISSUE TITLE
Usage embeded in another project

### ISSUE THREAD

**Issue by VALERE91** [ngtcp2/ngtcp2#154]
Hi,

we want to use your QUIC implementation for a project. Our hierarchy enforce us to embed your project in our own directory structure. Everything works except the crypto library. We found that the includes folders used by the ntcp2_crypto lib (openssl directory) use the top level directory path (CMAKE_SOURCE_DIR). We change it to a relative path (CMAKE_CURRENT_SOURCE_DIR) and it simply works embeded or not. We want to know if it does not break one of your coding standard before submitting a PR.

Here is the change : 

FROM : 
```cmake
set(ngtcp2_crypto_openssl_INCLUDE_DIRS
  "${CMAKE_SOURCE_DIR}/lib/includes"
  "${CMAKE_BINARY_DIR}/lib/includes"
  "${CMAKE_SOURCE_DIR}/lib"
  "${CMAKE_SOURCE_DIR}/crypto/includes"
  "${CMAKE_BINARY_DIR}/crypto/includes"
  "${OPENSSL_INCLUDE_DIRS}"
)
```

TO : 
```cmake
set(ngtcp2_crypto_openssl_INCLUDE_DIRS
  "${CMAKE_CURRENT_SOURCE_DIR}/../../lib/includes"
  "${CMAKE_CURRENT_BINARY_DIR}/../../lib/includes"
  "${CMAKE_CURRENT_SOURCE_DIR}/../../lib"
  "${CMAKE_CURRENT_SOURCE_DIR}/../../crypto/includes"
  "${CMAKE_CURRENT_BINARY_DIR}/../../crypto/includes"
  "${OPENSSL_INCLUDE_DIRS}"
)
```

Thanks

**Comment by tatsuhiro-t** [comment]
I don't have a particular coding standard for cmake files.  I think it is ok as long as it works fine.
Could you submit a PR?

**Comment by VALERE91** [comment]
Sure I did it :)
