### ISSUE TITLE
ngtcp2_pkt_decode_version_cid len question

### ISSUE THREAD

**Issue by danbev** [ngtcp2/ngtcp2#191]
I noticed that the following code in `ngtcp2_pkt_decode_version_cid`:
https://github.com/ngtcp2/ngtcp2/blob/f8a1e964c2a769f42a97b22382e9cc2fc8702f1c/lib/ngtcp2_pkt.c#L70-L71

Looking at the [Long Packet Header](https://tools.ietf.org/html/draft-ietf-quic-transport-23#section-17.2) I came to believe that these increments refer to the following (but not in the same order as the in the specification):
```
 1 header form bit
 4 type specific bits
 1 fixed bit
 1 long packet type
```
But looking at the `Long Packet Type` it should be 2 bits and not one. I might have misunderstood something (probably) but I wanted to ask if the above assumption is correct and also offer to add a comment here to clarify this a little.

My question if basically what do the values `1+4+1+1` represent?

Thanks

**Comment by tatsuhiro-t** [comment]
It represents the minimum length to construct Long header.
1: The first byte (flags + type)
4: version (4 bytes)
1: DCID len (1 byte)
1: SCID len (1byte)

**Comment by danbev** [comment]
@tatsuhiro-t  Oh I was way off, thanks for clarifying that! 
Should I add a comment or do you think that would be unnecessary?

**Comment by tatsuhiro-t** [comment]
I think it would be easier to understand if there is a comment.
I haven't found a time to add it (and I know what it represents).

**Comment by danbev** [comment]
> I think it would be easier to understand if there is a comment.

Great, I'll add a comment.
