### ISSUE TITLE
Echo example?

### ISSUE THREAD

**Issue by pfeatherstone** [ngtcp2/ngtcp2#197]
Would it be possible to have an example echo server/client to demonstrate the bare-bones API?

**Comment by xiaozhihong** [comment]
If it's useful, I can write one example.

**Comment by Payne-X6** [comment]
Please, I'd really appreciate it.

**Comment by tatsuhiro-t** [comment]
It is not echo, but I wrote relatively simple client: https://github.com/ngtcp2/ngtcp2/blob/main/examples/simpleclient.c

**Comment by Payne-X6** [comment]
I tried to port `examples/simpleclient.c` to `GnuTLS` based on `examples/tls_client_session_gnutls.cc`, but without success. It fails on handshake and I have not been able to resolve the issue.

If someone could provide some revision code, I would be really grateful. Here is the code in progress, please be kind, it's not completely cleaned up.

https://github.com/Payne-X6/ngtcp2/commit/2de8f901d02acc16621a4cc76fc566a373e3d236

**Comment by JackyYin** [comment]
When you configure and build correctly you will get `gtlsclient` and `gtlsserver` in your examples directory.

I configure my project like this:
```
./configure PKG_CONFIG_PATH=$PWD/../gnutls/build/lib/pkgconfig:$PWD/../nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,$PWD/../gnutls/build/lib" --with-gnutls
```

**Comment by Payne-X6** [comment]
These examples are too complex and it is not clear what is needed for the basic QUIC functionality and what is extra functionality (HTTP/3 etc). I'm trying to create some simple client/server implementation that only includes the mandatory TLS settings.

**Comment by ueno** [comment]
FWIW I wrote an echo [program](https://gitlab.com/dueno/quic-echo) for this [talk](https://devconfus2021.sched.com/event/lkfO/understanding-quic-by-examples) (thank you @tatsuhiro-t for reviewing the presentation draft :-)
