### ISSUE TITLE
No Padding info on client debug

### ISSUE THREAD

**Issue by alagoutte** [ngtcp2/ngtcp2#20]
On client debug log, there is no info about Padding 
from your example 
$ examples/client 127.0.0.1 3000
[  0.000213] send Client Initial packet
             <conn_id=0x06675539ce47c609, pkt_num=417370691, ver=0xff000004>
             STREAM frame
             <stream_id=0x00000000, offset=0, data_length=147>

But with server, we see info 

[  0.806688] recv Client Initial packet
             <conn_id=0x06675539ce47c609, pkt_num=417370691, ver=0xff000004>
             STREAM frame
             <stream_id=0x00000000, offset=0, data_length=147>
             **PADDING frame
             <length=1076>**

And checked with wireshark, and there is a padding in Client Initial packet

**Comment by tatsuhiro-t** [comment]
Thank you for raising this up.  It is a known issue, and I will see how to fix this.
