### ISSUE TITLE
Detecting when handshake is confirmed

### ISSUE THREAD

**Issue by jasnell** [ngtcp2/ngtcp2#204]
https://tools.ietf.org/html/draft-ietf-quic-tls-24#section-4.1.2 specifies that a handshake is confirmed when:

```
the handshake is complete, and the endpoint has received
an acknowledgment for a packet sent with 1-RTT keys.
```

The timing of this confirmation determines when key update is permitted to happen. Currently, initiating a key update will fail if this state isn't reached but it would be helpful to be able to detect confirmation when it happens. A `ngtcp2_handshake_confirmed` callback would be ideal as it would allow us to respond by flipping a bit that would let us know that key update is available. Alternatively, an API such as `ngtcp2_conn_get_handshake_confirmed` could be helpful.

Or, is there's some other already existing signal that can be used to determine confirmation that I'm missing?

**Comment by tatsuhiro-t** [comment]
Current method to confirm handshake is somewhat broken.  The detailed discussion is https://github.com/quicwg/base-drafts/issues/2863 and PR https://github.com/quicwg/base-drafts/pull/3145
Once this issue is resolved, I'll implement it and add a functionality to signal this event to an application.

**Comment by jasnell** [comment]
Fantastic. Thank you.

**Comment by tatsuhiro-t** [comment]
master is now draft-25 and it has handshake_confirmed callback function.  It is meant for client only.  Server confirms handshake when handshake completed.

**Comment by jasnell** [comment]
Working fantastically, thank you
