### ISSUE TITLE
Detecting stateless reset

### ISSUE THREAD

**Issue by jasnell** [ngtcp2/ngtcp2#206]
Hello @tatsuhiro-t :-) ... I'm working on implementing stateless reset support for the Node.js quic implementation. The tricky bit for me right now is on detecting that I have received a stateless reset and I was wondering if you've worked out a best approach for that with ngtcp2 yet.

Specifically, for any endpoint we have a set of ngtcp2_conn instances that may be server or client side (an endpoint in our implementation can be configured to support both roles). These are indexed by known cid for quick lookup. Obviously, however, the cid in a stateless reset is random so we cannot do that quick lookup, so when I receive a short header packet for a cid that I do not recognize, it's either: (a) a stateless reset, (b) a packet for a session I no longer have state for (and should therefore send a stateless reset), or (c) garbage that I should ignore. Unfortunately there's nothing in the ngtcp2 API currently that see currently that I can use to easily and cheaply detect this.

What I currently end up having to do is iterate through all of the known ngtcp2_conn instances and attempt to read the packet then check to see if the ngtcp2_stateless_reset callback was invoked, which is expensive and error prone. Rather than having to read the entire packet, what I'd prefer is to have an ngtcp2 utility function like `ngtcp2_detect_stateless_reset(conn, path, pkt, pktlen)` that would perform a quick check on the received packet that is essentially the same as the existing internal `conn_on_stateless_reset` but without consuming the packet and triggering callbacks (effectively just checking to see if a stateless reset can be decoded and validated).

If `ngtcp2_detect_stateless_reset()` returns non-zero, then it's a valid stateless reset for the associated ngtcp2_conn, otherwise it is not and I can move on to check the next ngtcp2_conn in my collection.

The other alternative approach would be to add a new callback that allows me to maintain my own index of received cid's and reset tokens. I could then implement the code necessary to detect the stateless reset myself. Since ngtcp2 already implements the logic internally I think the `ngtcp2_detect_stateless_reset()` API option would be ideal but wanted to get your thoughts.

I can work on implementing it if it makes sense.

**Comment by jasnell** [comment]
Ok, just did a quick local implementation and the following works great for doing a simple stateless reset detection...

```diff
index c63f7b3d44..6222fae06a 100644
--- a/deps/ngtcp2/lib/includes/ngtcp2/ngtcp2.h
+++ b/deps/ngtcp2/lib/includes/ngtcp2/ngtcp2.h
@@ -1674,6 +1674,21 @@ NGTCP2_EXTERN int ngtcp2_conn_read_pkt(ngtcp2_conn *conn,
                                        const uint8_t *pkt, size_t pktlen,
                                        ngtcp2_tstamp ts);

+/**
+ * @function
+ *
+ * `ngtcp2_conn_detect_stateless_reset` decodes a QUIC packet given in
+ * |pkt| and determines whether is contains a valid stateless reset
+ * token.
+ *
+ * This function returns non-zero if a validate stateless reset token
+ * can be decoded.
+ */
+NGTCP2_EXTERN int ngtcp2_conn_detect_stateless_reset(ngtcp2_conn *conn,
+                                                     const ngtcp2_path *path,
+                                                     const uint8_t *pkt,
+                                                     size_t pktlen);
+
 /**
  * @function
  *
diff --git a/deps/ngtcp2/lib/ngtcp2_conn.c b/deps/ngtcp2/lib/ngtcp2_conn.c
index f3d7482d63..3f7f994317 100644
--- a/deps/ngtcp2/lib/ngtcp2_conn.c
+++ b/deps/ngtcp2/lib/ngtcp2_conn.c
@@ -6703,6 +6703,45 @@ static int conn_is_retired_path(ngtcp2_conn *conn, const ngtcp2_path *path) {
   return 0;
 }

+int ngtcp2_conn_detect_stateless_reset(ngtcp2_conn *conn,
+                                       const ngtcp2_path *path,
+                                       const uint8_t *pkt,
+                                       size_t pktlen) {
+  int rv = 0;
+
+  ngtcp2_log_info(&conn->log, NGTCP2_LOG_EVENT_CON,
+                  "detect stateless reset len=%zu", pktlen);
+
+  if (pktlen == 0)
+    return 0;
+
+  /* client does not expect a packet from unknown path. */
+  if (!conn->server && !ngtcp2_path_eq(&conn->dcid.current.ps.path, path) &&
+      (!conn->pv || !ngtcp2_path_eq(&conn->pv->dcid.ps.path, path)) &&
+      !conn_is_retired_path(conn, path)) {
+    ngtcp2_log_info(&conn->log, NGTCP2_LOG_EVENT_CON,
+                    "ignore packet from unknown path");
+    return 0;
+  }
+
+  ngtcp2_pkt_stateless_reset sr;
+  rv = ngtcp2_pkt_decode_stateless_reset(&sr, pkt, pktlen);
+  if (rv != 0)
+    return 0;
+
+  if ((!ngtcp2_path_eq(&conn->dcid.current.ps.path, path) ||
+       ngtcp2_verify_stateless_reset_token(conn->dcid.current.token,
+                                           sr.stateless_reset_token) != 0) &&
+      (!conn->pv || !(conn->pv->flags & NGTCP2_PV_FLAG_FALLBACK_ON_FAILURE) ||
+       !ngtcp2_path_eq(&conn->pv->fallback_dcid.ps.path, path) ||
+       ngtcp2_verify_stateless_reset_token(conn->pv->fallback_dcid.token,
+                                           sr.stateless_reset_token) != 0)) {
+    return 0;
+  }
+
+  return 1;
+}
+
 int ngtcp2_conn_read_pkt(ngtcp2_conn *conn, const ngtcp2_path *path,
                          const uint8_t *pkt, size_t pktlen, ngtcp2_tstamp ts) {
   int rv = 0;
```

**Comment by tatsuhiro-t** [comment]
Stateless reset is always tricky part of QUIC.  I don't have clear idea to handle stateless reset packets where multiple connections are involved.
I think iterating all ngtcp2_conn objects for each unknown packet is easy dos vector; anyone can send garage to trigger expensive operation.
Indexing stateless reset and ngtcp2_conn is probably the better choice here.
That said, the current draft requires that only stateless reset tokens which associated to CID that is used and not yet retired must be used for comparison.  ngtcp2 currently does not expose API/callback to tell these bits of information.  I need to add them.
If we can associate stateless reset token and ngtcp2_conn, then we just pass a incoming packet to ngtcp2_conn and then the existing code can handle the detection of stateless reset.

**Comment by jasnell** [comment]
That's largely what the patch above does but it still requires iterating through the known sessions. It's definitely not ideal and I'll be continuing to play with it to find a better way.

**Comment by tatsuhiro-t** [comment]
To help improving situation, I added dcid_status callback.  It tells application when a Destination Connection ID and its stateless reset token is activated and retired.  Application can use this hook to update lookup table.  To clean up the table, ngtcp2_conn_get_num_active_dcid and ngtcp2_conn_get_active_dcid to get all active Destination Connection IDs.
The use case of this is if application sees unknown packet which does not goes to any existing connection, then if it has sufficient length, get last 16 bytes and consult a table and ngtcp2_conn, then call ngtcp2_conn_read_pkt.

**Comment by jasnell** [comment]
That's fantastic. Exactly what was needed. Thank you very much
