### ISSUE TITLE
PUT method doesn't save files

### ISSUE THREAD

**Issue by gorghino** [ngtcp2/ngtcp2#209]
Hi! New to QUIC, I'm testing ngtcp2 client/server.
I can fetch a file from the server to the client, but apparently the PUT method from client to server doesn't save the file to the document root.
The server correctly reads the file content but it doesn't create the file.

(Server/Client IPs are omitted below)

test.txt: HELLO WORLD
Client:

`./client SERVER__IP 60004 file://SERVER__IP/test -m PUT -d test.txt`

Server: 

`./server 0.0.0.0 60004 priv.key cert.pem`

Server log: https://pastebin.com/wWZfPmZs
Client log: https://pastebin.com/vXCuEmrL

I tried creating the file test into the root document, before calling the client; in this case, the server replied with 200 instead of 404, but the file is not updated with 'HELLO WORLD'.

**Comment by Karthikdasari0423** [comment]
Hi @gorghino ,

I am also new to QUIC and please let me know if you found out a way to use PUT method using ngtcp2 client and server.

**Comment by Karthikdasari0423** [comment]
Thank you for replying back @gorghino 
I too faced the similar problem
