### ISSUE TITLE
TLS Buffering Limits

### ISSUE THREAD

**Issue by jasnell** [ngtcp2/ngtcp2#211]
Draft 25, Section 4, "Data sent in CRYPTO frames is not flow controlled in the same way as stream data... The implementation SHOULD provide an interface to QUIC to tell it about its buffering limits so that there is not excessive buffering at multiple layers"

With the move to the BoringSSL QUIC APIs, this buffering is now handed off to OpenSSL and it's not clear what buffering limits are enforced or where they should be enforced. One possible strategy is to track the amount of data written in to the OpenSSL APIs by `ngtcp2_crypto_read_write_crypto_data()` but that is obviously imperfect it does not adequately reflect the actual buffer size which may vary through the course of the handshake.

**Comment by tatsuhiro-t** [comment]
I haven't checked OpenSSL patch, but I think the amount of actual buffered data is only known to TLS stack, so it would be nice to see that OpenSSL has this kind of API.

**Comment by jasnell** [comment]
Just getting back to this. I'll investigate further to see what is possible here.
