### ISSUE TITLE
GnuTLS crypto back-end

### ISSUE THREAD

**Issue by ansasaki** [ngtcp2/ngtcp2#216]
I would like to know if ngtcp2 maintainers would be interested in having a GnuTLS based crypto back-end.

Currently, changes are being made in GnuTLS to add the API's required to support QUIC:

* Exporting secrets from TLS: https://gitlab.com/gnutls/gnutls/-/merge_requests/1184
* Exposing HKDF API: https://gitlab.com/gnutls/gnutls/-/merge_requests/1186
* Add API's to push/get unprotected data from TLS: https://gitlab.com/gnutls/gnutls/-/merge_requests/1187

If there is interest, I can provide the required patches, although slightly intrusive changes would be required in ngtcp2's code as it is currently strongly tied to OpenSSL QUIC implementation from the modified branch (the examples use OpenSSL directly and the crypto helper library interface design assumes the TLS implementation received intrusive changes to be "QUIC aware", e.g. handling QUIC encryption levels internally).

**Comment by tatsuhiro-t** [comment]
I think it would be nice that GnuTLS has the similar QUIC aware API just like OpenSSL/BoringSSL and picotls so that we don't have to write lots of code in ngtcp2 crypto library. It reduces maintenance burden.  That said, the current ngtcp2 crypto API is not stable, and will change.  BoringSSL developer says that they change key schedule so OpenSSL patch might follow it.

**Comment by ansasaki** [comment]
Thank you for the answer!
Since more complex changes are not wanted in ngtcp2, and given the current uncertainty about the stability of the API, I believe it is better to postpone or move this effort to try to make GnuTLS more aligned with other implementations. It is also important to consider the current status of the QUIC specification itself, which is not standardised yet.

Feel free to close this issue, or keep it for the future when QUIC RFC is finally finished and when we will be able to invest the effort to add a GnuTLS crypto backend to ngtcp2 with lower risks.

**Comment by ueno** [comment]
While we initially modelled the GnuTLS API after NSS, [the current (proposed) API](https://gitlab.com/gnutls/gnutls/-/merge_requests/1187) is more like OpenSSL; the only difference I can think of is that the client needs to "infer" encryption level from a secret type (= keylog label) upon receiving key scheduling events.

There are still missing parts, e.g. quic_transport_parameters extension and AES-ECB / raw-ChaCha for header encryption, but they are also going to be similar.
