### ISSUE TITLE
can this connection take another h3 stream?

### ISSUE THREAD

**Issue by bagder** [ngtcp2/ngtcp2#218]
libcurl's internals try to "fill up" existing connections with streams before it creates a new one for the next new transfer.

Assuming we have N current h3 streams going over a single QUIC connection, is there a way I can ask ngtcp2 if there's room for another h3 request over that connection? (Presumably I would need to ask for the availability of the "whole set" of streams a single h3 transfer might use)

(with nghttp2, we keep track of the negotiated max number of concurrent streams for this purpose)

**Comment by tatsuhiro-t** [comment]
If I understand it correctly, you are asking the way to know whether application can open new bidirectional stream now without actually opening stream under the current maximum concurrent stream limit, right?  If so, I can add a new function to answer that question (whether just return 0/1 or returning number of available streams I haven't decided yet).  Single h3 transfer only uses single bidirectional stream.  QPACK uses shared pair of unidirectional streams which should be already opened.  For completeness, I probably add both bidi and uni variants.

**Comment by bagder** [comment]
Ack, yes that's exactly what I'd want (and the remark on the QPACK stream already being there then is of course correct).

**Comment by tatsuhiro-t** [comment]
I added 2 functions to return the number of streams which the local endpoint can open without violating streams concurrency limit; see 81558fca864e406b3894f18757982b235e6cf178
