### ISSUE TITLE
ngtcp2_conn_writev_stream() returns NGTCP2_ERR_WRITE_STREAM_MORE when packet is full

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#223]
If `ngtcp2_conn_writev_stream()` is called with `NGTCP2_WRITE_STREAM_FLAG_MORE` and writes a STREAM frame, it appears to  always return `NGTCP2_ERR_WRITE_STREAM_MORE` regardless of whether there is room left in the packet.

If this is the expected behavior, consider clarifying it in the documentation and removing this condition from the client example as it will always evaluate to false:
https://github.com/ngtcp2/ngtcp2/blob/e71dbba9346d962aebc7f2c9b233238b588fa18d/examples/client.cc#L1227-L1237

If `ngtcp2_conn_writev_stream()` writes a STREAM packet it necessarily returns `NGTCP2_ERR_WRITE_STREAM_MORE` and the `while` loop continues. So if the check for `ndatalen` is reached, a STREAM packet has not been written and therefore `ndatalen` must be 0.

**Comment by tatsuhiro-t** [comment]
You are correct.  The current implementation always returns NGTCP2_ERR_WRITE_STREAM_MORE if STREAM frame is written (thus ndatalen >= 0).
I thought that it might be nice not to say this in order to allow some flexibility in the future, but adding extra not exercised code is worse, so I'll update the doc and remove those lines of code.

**Comment by tatsuhiro-t** [comment]
48ba0b8 clarifies the things up.

**Comment by tatsuhiro-t** [comment]
It looks like there is an execution code path that ndatalen >= 0 and the return code is not NGTCP2_ERR_WRITE_STREAM_MORE.  The example case is sending probe packet.
48ba0b8 breaks HTTP/3 transaction right now, causing malformed HTTP message by sending same data twice.
I'll revert 48ba0b8.  I think we can close this issue with no action.

**Comment by tatsuhiro-t** [comment]
After refactoring codebase, I reapplied the patch 548a452f4d5b68c27ad6fb6eba79afa8abbdd34c

**Comment by amirlivneh** [comment]
Thanks!
