### ISSUE TITLE
A corrupted INITIAL packet received by the client starts an endless PING loop

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#224]
After 2ec42740468f92c75ba17fc503d24657a5eb90ab, if the example client receives a corrupted INITIAL packet, the example client and server start exchanging PING frames rapidly and indefinitely.

To reproduce, apply the patch below and run the example client against the server:

```
diff --git a/examples/server.cc b/examples/server.cc
index 6698636..4a6d99e 100644
--- a/examples/server.cc
+++ b/examples/server.cc
@@ -1524,6 +1524,11 @@ void Handler::write_server_handshake(ngtcp2_crypto_level level,

   auto &buf = crypto.data.back();

+  if (*buf.begin == 2) {
+     std::cerr << "Corrupting handshake" << std::endl;
+     *buf.begin = 1;
+  }
+
   ngtcp2_conn_submit_crypto_data(conn_, level, buf.rpos(), buf.size());
 }
```

**Comment by tatsuhiro-t** [comment]
Thank you.  I confirmed this bug.
I think the immediate measure is return NGTCP2_ERR_CRYPTO in this case and let client drop the connection.
I'm wondering this happens in the other scenarios.  It looks like recovery draft changed again and PTO algorithm (which is one of the hardest part in QUIC draft IMHO) is also changed.  Will check the behaviour when next set of QUIC draft is released.

**Comment by tatsuhiro-t** [comment]
414c793 fixes this issue.

**Comment by amirlivneh** [comment]
Thank you, @tatsuhiro-t .

**Comment by tatsuhiro-t** [comment]
I found that similar issue is still there if server does not send CRYPTO.  Just keep acking client Initial packet creates endless  ping loop.  This might be a QUIC design issue.

**Comment by tatsuhiro-t** [comment]
42528792fe4bf645f3d524b120eb4df2f1ede38d avoids frequent PTO probe issue.   It is not known that not resetting pto_count per each ACK degrade performance at this moment.  Consecutive packet loss already causes quite performance hit, so adding one or two pto_count might not help.
