### ISSUE TITLE
Return value of -1 from Client::send_packet() is not handled consistently

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#226]
`Client::send_packet()` is called in two places inside `Client::on_write()`:
(1) https://github.com/ngtcp2/ngtcp2/blob/master/examples/client.cc#L1123
(2) https://github.com/ngtcp2/ngtcp2/blob/master/examples/client.cc#L1242

If `Client::send_packet()` returns -1 in (1), `disconnect()` is called. In (2) `disconnect()` is not called.

**Comment by tatsuhiro-t** [comment]
210c94fd00ce61f1501e7fa6d1bbdb055162ffa6 adds diconnect for (2).

**Comment by amirlivneh** [comment]
Thanks!
