### ISSUE TITLE
Unsafe conversions from uint64_t to size_t

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#237]
There are a number of instances where `uint64_t` is implicitly converted to `size_t`. This is not safe on 32-bit systems and has caused a few bugs. The straightforward solution will be to replace the affected `size_t` with `uint64_t`. Note that this may propagate to the public API. For example, the `datalen` parameter of `ngtcp2_recv_crypto_data` will change from `size_t` to `uint64_t`.

I'll be happy to work on a PR if this sounds reasonable.

**Comment by tatsuhiro-t** [comment]
I'll look into it.
I think it is safe if we know that the value is under SIZE_MAX (i.e., size of buffer/object), but will see.

**Comment by tatsuhiro-t** [comment]
I'll check nghttp3 as well.

**Comment by amirlivneh** [comment]
Thank you! It will be great if we can reach a state where the libraries compile with `-Wconversion` so that issues like https://github.com/ngtcp2/ngtcp2/pull/236 are detected at compile time.

**Comment by tatsuhiro-t** [comment]
cbc1bb09bbbbe78487f6d1af59399d4113e295f7 fixes this issue.   ./configure --enable-werror enables `-Wconversion` as well.

**Comment by amirlivneh** [comment]
Thank you!

**Comment by tatsuhiro-t** [comment]
It turns out that debian multilib gcc is quite handy to build 32bits binary on amd64 machine.
libcunit1-dev packages have a bug which prevents them from being installed at the same time.  Other than that, it works pretty well.
