### ISSUE TITLE
The default build fails due to GnuTLS

### ISSUE THREAD

**Issue by Lekensteyn** [ngtcp2/ngtcp2#238]
Following the instructions in the README will end up in a build failure because GnuTLS apparently needs special patches (see PR #225 by @ueno, issue #216).

Some suggestions to improve this situation:
 - [ ] Update README with instructions to build an appropriate GnuTLS backend.
 - [x] Build the OpenSSL backend only when a good GnuTLS version is missing. This would allow 3109444df8e83d7746f825dbf9fba61a168b82cd to be reverted.
 - [x] Update CI config to ensure that the GnuTLS has sufficient test coverage.
 - [x] Update the build systems to perform feature detection, so it fails early when OpenSSL or GnuTLS do not have suitable APIs.

I am using the CMake build system on Arch Linux which ships with GnuTLS 3.6.13.

Build output:
```
[28/51] Building C object crypto/gnutls/CMakeFiles/ngtcp2_crypto_gnutls.dir/gnutls.c.o
FAILED: crypto/gnutls/CMakeFiles/ngtcp2_crypto_gnutls.dir/gnutls.c.o 
...
crypto/gnutls/gnutls.c:260:8: error: unknown type name ‘gnutls_record_encryption_level_t’
crypto/gnutls/gnutls.c:264:12: error: ‘GNUTLS_ENCRYPTION_LEVEL_INITIAL’ undeclared (first use in this function); did you mean ‘NGTCP2_CRYPTO_LEVEL_INITIAL’?
crypto/gnutls/gnutls.c:264:12: note: each undeclared identifier is reported only once for each function it appears in
crypto/gnutls/gnutls.c:266:12: error: ‘GNUTLS_ENCRYPTION_LEVEL_HANDSHAKE’ undeclared (first use in this function); did you mean ‘NGTCP2_CRYPTO_LEVEL_HANDSHAKE’?
crypto/gnutls/gnutls.c:268:12: error: ‘GNUTLS_ENCRYPTION_LEVEL_APPLICATION’ undeclared (first use in this function)
crypto/gnutls/gnutls.c:270:12: error: ‘GNUTLS_ENCRYPTION_LEVEL_EARLY’ undeclared (first use in this function); did you mean ‘NGTCP2_CRYPTO_LEVEL_EARLY’?
crypto/gnutls/gnutls.c:283:9: warning: implicit declaration of function ‘gnutls_handshake_write’; did you mean ‘gnutls_handshake’? [-Wimplicit-function-declaration]
crypto/gnutls/gnutls.c:283:9: warning: nested extern declaration of ‘gnutls_handshake_write’ [-Wnested-externs]
```

**Comment by Lekensteyn** [comment]
It looks like both backends can be independently enabled. I'll try to fix the CMake config to add auto-detection, that should prevent the above failure. Help is still needed with the GnuTLS instructions in the README.

**Comment by Lekensteyn** [comment]
Hi @ueno, could you look into adding README instructions and CI config for the GnuTLS? Once addressed, this issue can be closed.

**Comment by ueno** [comment]
@Lekensteyn I'm sorry that it took too long; the QUIC related API has been finally merged in the GnuTLS master, and I've updated the [examples using it](https://github.com/ueno/ngtcp2-gnutls-examples). Would it be sufficient to mention that in the README.rst file?

**Comment by tatsuhiro-t** [comment]
GnuTLS build has been added to GitHub workflow using 3.7.0 release and nettle 3.6.

**Comment by tatsuhiro-t** [comment]
Now GnuTLS client/server are fully integrated into ngtcp2 examples.  They are built by default as gtlsclient/gtlsserver if GnuTLS are installed.

**Comment by Lekensteyn** [comment]
Thanks, now the only thing that is needed before closing this issue is a README update :)

**Comment by tatsuhiro-t** [comment]
yes.  Due to the sad state of OpenSSL regarding QUIC support and the versionless nature of BoringSSL, GnuTLS might be a best choice for QUIC support for the time being.
But at the moment,  it looks like GnuTLS has some issues regarding early data (0RTT).

- GnuTLS server simply crashes when it receives 0RTT packet due to null pointer dereference.
- GnuTLS client cannot send early data because GnuTLS does not offer early secret to QUIC stack.

I reported this issues on https://github.com/ueno/ngtcp2-gnutls-examples/issues/7
cc @ueno

**Comment by tatsuhiro-t** [comment]
Looks like ngtcp2 has some issues regarding cipher when resumption is rejected.  Will fix it.  It will affect crypto library API.

**Comment by tatsuhiro-t** [comment]
After checking source code and the output of gnutls-cli --early-data, it looks like GnuTLS client generates early key and sends early data AFTER receiving Server Hello.  That means it is "1RTT" data sent in 0RTT mechanism.  I might be missing something.

**Comment by tatsuhiro-t** [comment]
GnuTLS build is now disabled by default for now due to its early data issue.
I finded https://gitlab.com/gnutls/gnutls/-/issues/1146 which is a root cause of late early data secret generation.  No response so far.

**Comment by tatsuhiro-t** [comment]
Thank to @ueno, GnuTLS server and client are now fully capable of  early data.

**Comment by ueno** [comment]
Thank you, sorry for that it took so long to get fixed.
