### ISSUE TITLE
Request:  ngtcp2_qlog_write final write status/indicator

### ISSUE THREAD

**Issue by jasnell** [ngtcp2/ngtcp2#250]
For the `ngtcp2_qlog_write` callback function (https://github.com/ngtcp2/ngtcp2/blob/master/lib/includes/ngtcp2/ngtcp2.h#L694), it would be helpful for the callback to include an additional argument that indicates whether it is the final write. This would simplify a couple of checks that we need to do to keep track of current state.

**Comment by tatsuhiro-t** [comment]
Good idea. Will do.

**Comment by tatsuhiro-t** [comment]
7eaa3670dfb19b828ad99cd0a9788a40955e3667 adds flags parameter.  If NGTCP2_QLOG_WRITE_FLAG_FIN is set, it is the final call to the callback.

**Comment by jasnell** [comment]
Thank you!
