### ISSUE TITLE
Wireshark info Protected Payload? It didn't decrypt

### ISSUE THREAD

**Issue by flx413** [ngtcp2/ngtcp2#251]
Hi,I'm interested in this project.
I want to analyze QUIC traffic using Wireshark,but I have some problems.
I have followed the instructions in the README and set the Pre-Master-Secret log file,but it didn't work.
Here are the commands I executed:

```
./server 127.0.0.1 7777 server.key server.crt

./client 127.0.0.1 7777
```
![5af7f2ee9e1279c8d5a2794bb2832b20c4ffc24d](https://user-images.githubusercontent.com/30550274/89043025-76c03400-d37a-11ea-9a1f-301f7fb18fee.png)

Thanks a lot for your help.

**Comment by yyu4** [comment]
You need to use latest (beta) wireshark, see https://github.com/quicwg/base-drafts/wiki/Tools#wireshark

**Comment by simonasmulevicius** [comment]
To install the latest Wireshark version on Ubuntu use the following steps:

`sudo add-apt-repository ppa:wireshark-dev/stable 
sudo apt update
sudo apt -y install wireshark`

(Taken from https://computingforgeeks.com/how-to-install-wireshark-on-ubuntu-desktop/)

**Comment by simonasmulevicius** [comment]
@yyu4 Which Wireshark version are you using?

It seems that even with 3.4.2 I get the similar issues:
![Protected_payload](https://user-images.githubusercontent.com/50625590/104940762-19f91a00-59aa-11eb-8038-49c749f58500.png)

**Comment by simonasmulevicius** [comment]
@tatsuhiro-t I suspect that I may be generating keys in the wrong way.
Currently I am using the following command:
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365`.

However, MsQUIC team is using slightly different command:
`openssl req  -nodes -new -x509  -keyout server.key -out server.cert`
(taken from https://github.com/microsoft/msquic/blob/main/src/tools/sample/sample.cpp)

**Comment by flx413** [comment]
I've solved the problem,because I used the wrong version of openssl lib.You need to make sure that the openssl of the certificate is the same as the openssl of ngtcp2 using.

**Comment by simonasmulevicius** [comment]
@flx413 Ok, I will try this now. By the way, how should Wireshark's GUI look like when it is able to decrypt packets? What extra information is then visible?

**Comment by simonasmulevicius** [comment]
You are correct - when running `openssl version` I get that I am using:
_OpenSSL 1.1.1f  31 Mar 2020_
but it seems that 1.1.1g version is used for draft-32.

**Comment by simonasmulevicius** [comment]
@flx413 so how do you generate keys then?

**Comment by simonasmulevicius** [comment]
I wonder if shouldn't specify `--openssldir=DIR` parameter when calling `./config enable-tls1_3 --prefix=$PWD/build`
because I don't have **/usr/local/ssl** and 
`openssl version -d` returns **OPENSSLDIR: "/usr/lib/ssl"**

**Comment by tatsuhiro-t** [comment]
I don't fully understand what is the issue, but patched openssl is not required to produce server certificate and private key and openssl provides variety of ways to produce them.

**Comment by flx413** [comment]
> @yyu4 Which Wireshark version are you using?
> 
> It seems that even with 3.4.2 I get the similar issues:
> ![Protected_payload](https://user-images.githubusercontent.com/50625590/104940762-19f91a00-59aa-11eb-8038-49c749f58500.png)

@simonasmulevicius It works. Wireshark will not show 'PKN','STREAM' if QUIC packets not decrypted.

**Comment by simonasmulevicius** [comment]
> > @yyu4 Which Wireshark version are you using?
> > It seems that even with 3.4.2 I get the similar issues:
> > ![Protected_payload](https://user-images.githubusercontent.com/50625590/104940762-19f91a00-59aa-11eb-8038-49c749f58500.png)
> 
> @simonasmulevicius It works. Wireshark will not show 'PKN','STREAM' if QUIC packets not decrypted.

I see. So this is already the decrypted version of HTTP3 communication over QUIC.
(In order to reconstruct this example I had to set **SSLKEYLOGFILE** globally in **~/.bashrc** and launch Wireshark with `sudo wireshark`).
