### ISSUE TITLE
Running Server issues

### ISSUE THREAD

**Issue by karanmankar95** [ngtcp2/ngtcp2#267]
Hi,
I am trying to implement QUIC into my system for a college project. I am using Ubuntu Desktop and I am able to successfully run examples/client. However while trying to run examples/server I am getting the following output. 

root@DESKTOP-N0VT1DM:/home/kmm1110/ngtcp2/examples# ./server 0.0.0.0 9090 privatekey certificate.crt
Using document root /home/kmm1110/ngtcp2/examples/
root@DESKTOP-N0VT1DM:/home/kmm1110/ngtcp2/examples# 

Any help would be massively helpful. Thank you

**Comment by mconk** [comment]
Hello there, 
I am also having the same problem detailed above. I am running Ubuntu Desktop and only able to run examples/client. When I attempt to run examples/server the code fails to execute (Same output as you are getting). I have been attempting to solve this with no progress. Any help on this matter would be extremely helpful, thank you!

**Comment by Molloss** [comment]
I had the same issue. 
it was : if (setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, static_cast< socklen_t >(sizeof(val))) == -1)
that fails without writing any error but by commenting it, I can run it with no pb on my Ubuntu (WSL)

**Comment by karanmankar95** [comment]
@Molloss Thanks, that completely solved my problem. Thanks a lot

**Comment by tatsuhiro-t** [comment]
Thank you.  I think 4f2b408bfa5e83b4ba2b8bc6f027b021b90b98da fixes this issue.

**Comment by Molloss** [comment]
works for me :) thanks

**Comment by karanmankar95** [comment]
Hey guys, I am not able to send or receive a file using the commands given in the readme. I am using ```/examples/client SERVER_IP PORT -d DATA_FILE. Am I missing something in the commands that is not allowing data to go through? The headers are sent through and handshake is done but data file is not sent.

**Comment by simonasmulevicius** [comment]
@karanmankar95 By running `./client --help` in **~/ngtcp2/examples$** you can see that 

**Usage: client [OPTIONS] <HOST> <PORT> [<URI>...]**

So in your case you should run `/examples/client -d PATH_TO_FILE SERVER_IP PORT `.

However, I also tried something similar:
SERVER:
~/ngtcp2/examples$  `./server --htdocs /home/valdas/ngtcp2/examples/servers_folder/ 127.0.0.1 7777 server.key server.cert`

CLIENT:
~/ngtcp2/examples$ `./client --data /home/valdas/ngtcp2/examples/clients_folder/MrClient.txt  127.0.0.1 7777`

But I couldn't see neither contents of the file, for the name being transferred via Wireshark. 
In particular, I looked at the two HTTP3 packets and their HTTP3 information is more than boring:
![Screenshot from 2021-01-21 01-34-55](https://user-images.githubusercontent.com/50625590/105265995-03f58000-5b89-11eb-8ca5-23e2b47d2efb.png)
