### ISSUE TITLE
Plaintext mode?

### ISSUE THREAD

**Issue by ericcurtin** [ngtcp2/ngtcp2#270]
In some industries there's a tenancy to use plaintext protocols to squeeze that extra little performance out of a protocol. I know it's not part of the spec, but would it be possible to run ngtcp2 as a plaintext protocol? The use case is when you are connecting things directly over fibre or PCIe. The crypto acceleration hardware isn't really there for QUIC yet, although judging by some patent applications people are working on it. Would like to compare plaintext TCP vs plaintext ngTCP2 over UDP. Would this be possible in UDP?

**Comment by tatsuhiro-t** [comment]
libngtcp2 offloads any cryptographic operations to user defined callback function.  If you implement them in a way that it works with ngtcp2 without encryption, I think you will get unencrypted transport if you want.

**Comment by ericcurtin** [comment]
Will certainly look into it @tatsuhiro-t thanks. Curious to see if there is any significant performance difference between plaintext tcp vs ngtcp2 without encryption. Have you done any benchmarks yourself?

**Comment by tatsuhiro-t** [comment]
no.
