### ISSUE TITLE
Failed to construct the packet  while calling ngtcp2_conn_writev_stream after thousands' round

### ISSUE THREAD

**Issue by optimistyzy** [ngtcp2/ngtcp2#272]
I developed an client/server program based on NGTCP2. And currently face the following issue. 

After the connection is constructed, what I mean the handshake phase is completed. 
Then the client sends 72 bytes (user's datalen), and opens a stream via ngtcp2_conn_open_bidi_stream, then used ngtcp2_conn_writev_stream to read the data.  And the server returns 4168 bytes always. I expect to run this kind of behavior in several minutes to test the stability. It means:
client -> target (72 bytes, it is the user data which is not the total packet size)
target->client (4196 bytes, it is also the data which is not the total packet size).

But after thousand's running, the initiator fails on  ngtcp2_conn_writev_stream. 

"ngtcp2_conn_writev_stream(ngtcp2_conn *conn, ngtcp2_path *path,
                                       ngtcp2_pkt_info *pi, uint8_t *dest,
                                       size_t destlen, ngtcp2_ssize *pdatalen,
                                       uint32_t flags, int64_t stream_id,
                                       const ngtcp2_vec *datav, size_t datavcnt,
                                       ngtcp2_tstamp ts)"

It means after this function is invoked, **the return value of this function is 44, but pdatalen = -1** . And I checked the definition of ngtcp2_conn_writev_stream, but I do not understand why this happens. I know when I stream_id = -1 during the handshaking phase, it could have such condition. But when I use stream to write (stream_id is valid), why this happens?  So I would like to get some opinions from the community to give me some advice.

**Comment by tatsuhiro-t** [comment]
We have a documentation which says it is possible to have *pdatalen == -1 even if stream_id != -1.
It happens when stream data is not included in a packet because, for example, there is no room to include stream data in a packet or cannot send stream data at the moment because of flow control limit.

**Comment by optimistyzy** [comment]
@tatsuhiro-t  Thanks for your explanation. So could you give me some advice to solve this issue during the running? I hope that the solution is not killing or close the stream, but handling this cases and continue the data transmission again. Currently, I tried to close the stream and open a new stream, but it does not work.  By the way,  if we face such "flow control limit". Could we change the maximal value of flow control and avoid such issue. Looking forward to your further guidance, thanks.

**Comment by tatsuhiro-t** [comment]
Wait for the window to recover.  Flow control credit increases when a remote endpoint sends window update.  After reading packet, then try to write packet. You do not need to close stream.  It is a remote endpoint who decides the window size.

**Comment by optimistyzy** [comment]
> Wait for the window to recover. Flow control credit increases when a remote endpoint sends window update. After reading packet, then try to write packet. You do not need to close stream. It is a remote endpoint who decides the window size.

Hi @tatsuhiro-t  Do you mean that the target side receives this packet, need to read and write a new packet to the initiator. So my question is that what kinds of packet should the target side send?  How the target side can differentiate this packet with the normal one. Since the normal packet may also receive small packet. Currently, I know that if there is packet coming, if I call packet read, and the user callback function will be called if there will be user data received.

**Comment by optimistyzy** [comment]
Thanks for your info @tatsuhiro-t . Another question:

For the same program. During the test, If I use multiple connections from the client. Sometimes I see the function pointer by ngtcp2_recv_stateless_resetis called (I created a user callback function), It means that I call  ngtcp2_conn_read_pkt, then the "recv_stream_data" call back function is not called.  How to avoid such issue?

**Comment by tatsuhiro-t** [comment]
There are several reasons whey stateless reset is sent.  One of them is server has no connection context so it is unable to handle connection.  In any case, only server knows the exact reason.  Usually client should create new connection and try again.

**Comment by optimistyzy** [comment]
@tatsuhiro-t  Can you explain more on the connection context?   Thanks.

**Comment by optimistyzy** [comment]
@tatsuhiro-t  May I ask another question here:

How to write multiple packets in a stream for responding to the client.  For example, if a client writes a packet with 72 bytes user data. And the server side returns 256KB user space data.  And we know the default packet size for ngtcp2 is 1252 (Though we can change with larget value, there is still a limitation for one packet size, so there should be support for multiple packets). So if we to use one stream to respond to the clients. How to write the program. I did not see how to write the multiple packets example in ngtcp2.  I know that if client knows how many data the server returns. Client may construct a protocol to use multiple streams to achieve that. But how can we do it in a single stream for the response. 

And in my earlier question, we know that if one side continues writing the data, but did not get the acknowledgement from the client side, it will cause the flow control of the  window.  And it will cause the continue sending fail. If both the client and server uses the uni stream to write the data. It has the chance the that one side will have more streams, and it means that the other side will read the data but it will not write any packets. So how can the write side recover the window?  Does it mean that the read side needs to write packets containing NULL user data?  If it is really that, it means that there must be 1-1 mapping, i.e., one write from the client, there must one response from the target.

**Comment by tatsuhiro-t** [comment]
The receiver need to call ngtcp2_conn_writev_stream even if there is no application data to send.  Unlike TCP, QUIC needs to send ACK in user space. ngtcp2_conn_writev_stream writes ACK and other control frames as well.  If there is no data to send pass -1 to stream_id.  In general, call ngtcp2_conn_writev_stream at least once when packets are received.
