### ISSUE TITLE
ngtcp2_bswap64 is not using ngtcp2_ntohl

### ISSUE THREAD

**Issue by jpboivin** [ngtcp2/ngtcp2#277]
Minor bug, but ngtcp2_ntohl was introduced to avoid a dependency on WinSock, but the ngtcp2_bswap64 macro uses `ntohl` directly if `bswap_64` is not defined/available. The macro should be using ngtcp2_ntohl instead.

**Comment by tatsuhiro-t** [comment]
Thank you for pointing out this issue.  Fix committed via 5f000a396ba25e79435a93c63a68e96d689bb479
