### ISSUE TITLE
Potential null pointer dereference when receiving 0-RTT packets

### ISSUE THREAD

**Issue by Freddrickk** [ngtcp2/ngtcp2#278]
I'm opening this issue because we found a potential null pointer dereference while testing the project. It occurred when we tested a server connection in the handshake phase by repeatedly providing the same input as such:

```cpp
ngtcp2_tstamp ts = 1;
for (size_t round = 0; round != nbRounds; ++round)
{
 ngtcp2_conn_read_pkt(connection, path, data, size, ++ts);
 ngtcp2_conn_write_pkt(connection, nullptr, buffer, sizeof(buffer), ++ts);
}
```

The bug happened when providing a 0-RTT packet. In one of the calls to `ngtcp2_conn_read_pkt`, `conn->in_pktns` was set to null after the parsing of the packet in `conn_read_handshake`. This is due to
`conn_discard_initial_state` being called at ngtcp2_conn.c:8152:

```cpp
if (conn->hs_pktns->rx.max_pkt_num != -1) {
  conn_discard_initial_state(conn, ts);
}
```

 thus deleting `conn->in_pktns`. In the following call to `ngtcp2_conn_read_pkt` with the same packet the function `conn_recv_handshake_pkt` is called. This results in `conn_buffer_pkt` being called as such:

```cpp
rv = conn_buffer_pkt(conn, conn->in_pktns, path, pi, pkt, pktlen, ts); // ngtcp2_conn.cpp:5131
```

where `conn->in_pktns` is null. This causes a null-pointer dereference in `conn_buffer_pkt`.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this.  Do you actually reproduce this null pointer dereference by executing your test code with actual TLS setup?
I'm curious because once server sees client Initial packet, it sets NGTCP2_CONN_FLAG_CONN_ID_NEGOTIATED flag.  If conn->in_pktns is discarded, it means that the flag is set, and client Handshake packet is also received.
In this case, conn_buffer_pkt call at line 5131 will not be called if the flag is set.

**Comment by Freddrickk** [comment]
I did not test this with an actual TLS setup. I tested it by creating a handshake server connection using the `setup_handshake_server` from the unit tests (ngtcp2_conn_tests.c) and passing the input to `ngtcp2_conn_read_pkt` and `ngtcp2_conn_write_pkt` in a loop as described in my first comment.
The `NGTCP2_CONN_FLAG_CONN_ID_NEGOTIATED` flag is set when a `NGTCP2_PKT_INITIAL` is received. However, in this case I'm parsing a handshake packet (`NGTCP2_PKT_HANDSHAKE`) and that's why the flag is never set.

I'm not quite sure this code path could be reached in an actual setup. I would say it depends whether it is possible to receive a handshake packet in the state `setup_handshake_server` configures the server connection or not.

**Comment by tatsuhiro-t** [comment]
setup_handshake_server has unrealistic setup at the moment.  It installs handshake key at the beginning but in practice it does not happen that way.  I'll fix the current test setup.

**Comment by tatsuhiro-t** [comment]
I cleaned up key schedule in test suite.

**Comment by Freddrickk** [comment]
Finally had a bit of time to spend on this. I built a fuzzer using the new implementation of setup_handshake_fuzzer and still get the same issue. Turns out the `NGTCP2_CONN_FLAG_CONN_ID_NEGOTIATED` flag is never set. The same call to `conn_discard_initial_state` is made before a 0-RTT packet is received and buffered with `pktns->rx.buffed_pkts` set to null. It's a bit different from the original issue where `pktns` was null.

Unfortunately, I won't have much more time to investigate this crash. However, if you'd like to investigate this further, I have a fork with the fuzzer and the buggy input. You need to use clang for it to work since it uses libFuzzer. I made a quick doc to reproduce the crash with the buggy input there: https://github.com/Freddrickk/ngtcp2/tree/master/fuzzer. I hope this helps.

**Comment by tatsuhiro-t** [comment]
I think the return value of ngtcp2_conn_read_pkt and ngtcp2_conn_write_pkt must be handled.
In the failed test, ngtcp2_conn_read_pkt returns NGTCP2_ERR_DROP_CONN, which tells application to drop connection immediately.

**Comment by Freddrickk** [comment]
Indeed, by closing the connection if a fatal error or NGTCP2_ERR_DROP_CONN occurs, I don't get the bug anymore. Closing the issue.
