### ISSUE TITLE
No packet header encryption

### ISSUE THREAD

**Issue by simonasmulevicius** [ngtcp2/ngtcp2#279]
Good morning, 

I am doing a research project about the QUIC offloading in hardware.
For this reason, I would like to be able to see packet numbers (in hardware).
However, I know that multiple implementations of QUIC usually encrypt packet headers.
Hence, I wonder if this implementation of QUIC has an API to turn off packet header encryption mechanism.

Kind regards, 
Simonas

**Comment by tatsuhiro-t** [comment]
ngtcp2 uses a callback to ask application to generate a mask to encrypt packet header.  Encryption is done with XOR, so making callback return zero-cleared mask (all bits are off), then it effectively disables header encryption.

**Comment by simonasmulevicius** [comment]
I guess you are speaking about the following callback function:

**ngtcp2_hp_mask** _hp_mask_

which, according to https://nghttp2.org/ngtcp2/types.html#c.ngtcp2_callbacks, _is invoked to get a mask to encrypt or decrypt packet header._

What do you mean by "zero-cleared mask"? 
If I understand correctly from (https://nghttp2.org/ngtcp2/types.html#c.ngtcp2_hp_mask), the mask should be made of a string of NGTCP2_HP_MASKLEN number of 0's, am I right?

**Comment by tatsuhiro-t** [comment]
yes.

**Comment by simonasmulevicius** [comment]
Are there any convenient commands to run the default tests after the compilation?

**Comment by simonasmulevicius** [comment]
No worries - found `examplestest` in /ngtcp2/examples

**Comment by simonasmulevicius** [comment]
Do you think something like this would work:

```
int do_hp_mask(uint8_t *dest, const ngtcp2_crypto_cipher *hp,
               const ngtcp2_crypto_cipher_ctx *hp_ctx, const uint8_t *sample) 
{
    std::fill_n(dest, NGTCP2_HP_MASKLEN, 0);
    return 0;
}
```
