### ISSUE TITLE
Assertion hs_pktns failed while handling expiry

### ISSUE THREAD

**Issue by markspanbroek** [ngtcp2/ngtcp2#280]
I'm running into an issue when calling ngtcp2_conn_handle_expiry on a server connection. It keeps failing an assert:

```
ngtcp2_conn.c:10231: ngtcp2_conn_on_loss_detection_timer: Assertion `hs_pktns' failed.
```

This is after handshake completed. The weird thing is that the loss detection timer seems to want to handle initial and handshake packets after handshake is completed. Just before the assert the code asks for the earliest_pktns, which is conn->in_pktns, the initial packet number space. It then processes the in_pktns, and because of a switch-case fall through, it also tries to process hs_pktns. But conn->hs_pktns has already been discarded, because the handshake is completed.

Some context: I'm [integrating](https://github.com/status-im/nim-quic/) ngtcp2 into [Nim](https://nim-lang.org/). I'm currently using a dummy TLS implementation, and a fake UDP connection in my tests.

**Comment by markspanbroek** [comment]
I found a workaround for the issue. This ensures that when the handshake state is being discarded, it also discards the initial state:

```C
/*
 * conn_discard_handshake_state discards state for Handshake packet
 * number space.
 */
static void conn_discard_handshake_state(ngtcp2_conn *conn, ngtcp2_tstamp ts) {
  if (!conn->hs_pktns) {
    return;
  }

  conn_discard_initial_state(conn, ts); // workaround
  
  conn_discard_pktns(conn, &conn->hs_pktns, ts);
}
```

I'm not sure whether it is correct to assume that the initial state can always be discarded together with the handshake state, but it seems to solve my problem.

**Comment by tatsuhiro-t** [comment]
It is expected that handshake packet number space lives longer than initial packet number space.  By the time, handshake packet number space is discarded, initial packet number state must have been discarded in TLS flow.  I think your placeholder TLS implementation might set keys in unexpected way.  The library also expects the Initial/Handshake packets to proceed in proper handshake state.

**Comment by markspanbroek** [comment]
Thanks for the hints, @tatsuhiro-t! I'm currently looking through my dummy TLS implementation where I might have gone wrong. I'm puzzled why the initial packet number state is not discarded in my flow. I'll update this issue once I know more.

**Comment by markspanbroek** [comment]
I spent a lot of time debugging this until someone suggested that I log the TLS behavior in the example server and client. This gave me the following overview:

```
client:

ngtcp2_crypto_client_initial_cb
- ngtcp2_conn_set_initial_crypto_ctx
- ngtcp2_conn_install_initial_key
- ngtcp2_conn_submit_crypto_data, level: 0
recv_crypto_data, level: 0
- ngtcp2_conn_set_crypto_ctx
- ngtcp2_conn_install_rx_handshake_key
- ngtcp2_conn_install_tx_handshake_key
recv_crypto_data, level: 1
- ngtcp2_conn_set_remote_transport_params
- ngtcp2_conn_install_rx_key
- ngtcp2_conn_install_tx_key
- ngtcp2_conn_submit_crypto_data, level: 1
- ngtcp2_conn_handshake_completed
handshake_completed
recv_crypto_data, level: 2


server:

ngtcp2_crypto_recv_client_initial_cb
- ngtcp2_conn_set_initial_crypto_ctx
- ngtcp2_conn_install_initial_key
recv_crypto_data, level: 0
- ngtcp2_conn_submit_crypto_data, level: 0
- ngtcp2_conn_set_crypto_ctx
- ngtcp2_conn_install_rx_handshake_key
- ngtcp2_conn_install_tx_handshake_key
- ngtcp2_conn_set_remote_transport_params
- ngtcp2_conn_submit_crypto_data, level: 1
- ngtcp2_conn_install_rx_key
- ngtcp2_conn_install_tx_key
recv_crypto_data, level: 1
- ngtcp2_conn_submit_crypto_data, level: 2
- ngtcp2_conn_handshake_completed
handshake_completed
```

When I changed my TLS dummy code to match these invocations, it all started working.
