### ISSUE TITLE
Data file  wont go through.

### ISSUE THREAD

**Issue by surajkolari** [ngtcp2/ngtcp2#284]
After I run the Server and client, initial and handshake is being established. But the data file I am attaching wont go through. Can any one tell me what I am missing.

![image](https://user-images.githubusercontent.com/19970098/106208486-77068400-6191-11eb-8923-c4de9d4d604a.png)

![image](https://user-images.githubusercontent.com/19970098/106208645-acab6d00-6191-11eb-8ea4-32fcff04c550.png)

![image](https://user-images.githubusercontent.com/19970098/106208799-f2683580-6191-11eb-966c-2b66968add19.png)

**Comment by tatsuhiro-t** [comment]
Specify URI:

`examples/client 127.0.0.1 4433 https://127.0.0.1:4433`

**Comment by surajkolari** [comment]
Thank you for the reply. But I am fairly new to this. I tried what you said and still got the same result. My client and server are running on different machines. They are both in a private network. My server is running on 10.0.0.4 and my client is running on 10.0.0.8. If I want to send a helloworld.txt, what command should I run.
