### ISSUE TITLE
Support for routable connection IDs

### ISSUE THREAD

**Issue by jasnell** [ngtcp2/ngtcp2#285]
Hello @tatsuhiro-t :-) ... I'm looking at https://tools.ietf.org/id/draft-ietf-quic-load-balancers-06.html and working through what will be needed to support it. Before I get too far along, I wanted to check to see if you had any plans to build support for routable CIDs into ngtcp2.

**Comment by tatsuhiro-t** [comment]
Application generates Connection ID and libngtcp2 accepts it as a opaque byte array.  Application can employ any encoding it wants and arrange routing table to pass a UDP datagram payload to a correct ngtcp2_conn object.  So we do not require any change in libngtcp2.

**Comment by jasnell** [comment]
Ok that's what I suspected, I just wanted to confirm before doing the implementation myself. It might be worthwhile at some point adding a utility function to the ngtcp2_crypto include that handles the actual encryption parts but that's certainly not critical. 

Thank you!
