### ISSUE TITLE
ACK/NACK callback for DATAGRAM frames

### ISSUE THREAD

**Issue by jpboivin** [ngtcp2/ngtcp2#286]
Hello,

The datagram RFC specifies that DATAGRAM frames are ACK-eliciting. Some applications can be interested to know whether an unreliable message was ACKed or NACKed. It would be great if ngtcp2 could track the ACKs for DATAGRAM frames and notify back the application. Currently, packets are not associated with any DATAGRAM frames (so ACKs are not associated with DATAGRAM frames) and there is no identification for the frames either.

We previously had a custom support for datagrams (without the ACK/NACK callback), and we were using the offset of the sender to identify frames internally in ngtcp2.

**Comment by tatsuhiro-t** [comment]
I'll add new parameter to ngtcp2_conn_writev_datagram which identifies a passed DATAGRAM frame.  When a packet is acknowledged, new callback is invoked with the ID.

**Comment by tatsuhiro-t** [comment]
I'm not sure we need nack callback because loss detection takes some time and application might not be interested in DATAGRAM by the time packet loss is declared.  Also as pointed out by RFC, reordering creates spurious loss declaration.

**Comment by jpboivin** [comment]
It is expected for loss detection to not be immediate. But it is also a part of the QUIC protocol that is quite configurable (like the thresholds), and as such can be adapted to fit some needs an application could have.

I’m aware that reordering creates spurious losses with QUIC. Still, it might be interesting for some applications to know when the transport consider the DATAGRAM likely loss as it might react on this event sooner.

If the application only had a ACK callback, it would need to guess itself when a DATAGRAM is likely loss, without knowing if the transport actually had a bit more info about it.

**Comment by tatsuhiro-t** [comment]
I think if ACKed or not-ACKed is very important, then application should use STREAM rather than DATAGRAM.
If there is no concrete use case, I'd like to omit nack part for now.

**Comment by jpboivin** [comment]
Thanks for the new callback!

---

For the NACK part, although most of the time using a reliable stream will works, it's not always the case. Suppose you're sending state data with a periodic forced sync followed by deltas (and you don't need, nor want reliability). When you get a NACK, you'll want to send the current state in a new sync message (you no longer care about the old data, it's outdated anyway). Using a reliable stream (let's say just for the syncs) would mean that a previous one would need to be sent & ACKed, even if it is no longer interesting.

**Comment by tatsuhiro-t** [comment]
Added ngtcp2_lost_datagram callback.
