### ISSUE TITLE
ngtcp2 failed make -j$(nproc) check

### ISSUE THREAD

**Issue by vkosuri** [ngtcp2/ngtcp2#288]
Hi,

I am a newbie to the entire quic protocol and OpenSSL, could you please help me resolve this issue?

Here is the my Operating System details
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

After all the installation of openss, nghttp3 it was went verwell after installed ngtcp2, make check was failed with below resons

```Bash
server.cc:3763:52: error: no matching function for call to ‘quoted(std::string_view&)’
               << std::quoted(config.mime_types_file) << std::endl;
                                                    ^
In file included from server.cc:33:0:
/usr/include/c++/7/iomanip:461:5: note: candidate: template<class _CharT> auto std::quoted(const _CharT*, _CharT, _CharT)
     quoted(const _CharT* __string,
     ^~~~~~
/usr/include/c++/7/iomanip:461:5: note:   template argument deduction/substitution failed:
server.cc:3763:52: note:   mismatched types ‘const _CharT*’ and ‘std::basic_string_view<char>’
               << std::quoted(config.mime_types_file) << std::endl;
                                                    ^
In file included from server.cc:33:0:
/usr/include/c++/7/iomanip:470:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> auto std::quoted(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, _CharT, _CharT)
     quoted(const basic_string<_CharT, _Traits, _Alloc>& __string,
     ^~~~~~
/usr/include/c++/7/iomanip:470:5: note:   template argument deduction/substitution failed:
server.cc:3763:52: note:   ‘std::string_view {aka std::basic_string_view<char>}’ is not derived from ‘const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>’
               << std::quoted(config.mime_types_file) << std::endl;
                                                    ^
In file included from server.cc:33:0:
/usr/include/c++/7/iomanip:480:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> auto std::quoted(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, _CharT, _CharT)
     quoted(basic_string<_CharT, _Traits, _Alloc>& __string,
     ^~~~~~
/usr/include/c++/7/iomanip:480:5: note:   template argument deduction/substitution failed:
server.cc:3763:52: note:   ‘std::string_view {aka std::basic_string_view<char>}’ is not derived from ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>’
               << std::quoted(config.mime_types_file) << std::endl;
                                                    ^
  CXX      server-debug.o
Makefile:2308: recipe for target 'server-server.o' failed
make[1]: *** [server-server.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/tcp2/ngtcp2/examples'
Makefile:474: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by tatsuhiro-t** [comment]
It looks like C++ compiler is too old.  g++10 and clang++-10 should work.

**Comment by av223119** [comment]
Would you mind to change the README to state this fact, then?

**Comment by LPardue** [comment]
well, it's right there at the top of [requirements](https://github.com/ngtcp2/ngtcp2#requirements)

> The libngtcp2 C library itself does not depend on any external libraries. The example client, and server are written in C++17, and should compile with the modern C++ compilers (e.g., clang >= 8.0, or gcc >= 8.0).

**Comment by av223119** [comment]
@LPardue 

I was referred to the discrepancy: @tatsuhiro-t  has recommended gcc-10, while README says that version 8 will suffice. I've just verified, version 8 does indeed suffice, and it is available in Ubuntu 18.10, unlike version 10.

@vkosuri The solution going to be easy for you, export CC and CXX variables pointing to the gcc version 8:
`export CC=gcc-8 CXX=g++-8`

**Comment by NooshinEghbal** [comment]
Hello,
I am using gcc/g++ 9.4.0.
But here is the build summary of nghttp3:
configure: summary of build options:

    Package version: 0.6.0-DEV
    Library version: 2:1:0
    Install prefix:  /home/nooshin/Desktop/FEC_HTTP/ngtcp2/nghttp3/build
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C preprocessor: gcc -E
      CPPFLAGS:       
      C compiler:     gcc
      CFLAGS:         -g -O2
      C++ compiler:   g++ -std=c++17
      CXXFLAGS:       -g -O2
      LDFLAGS:        
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Test:
      CUnit:          no (CFLAGS='' LIBS='')
    Debug:
      Debug:          no (CFLAGS='')
    Library only:     yes
    Examples:         no

And the ngtcp2 summary is:

configure: summary of build options:

    Package version: 0.7.0-DEV
    Library version: 5:0:0
    Install prefix:  /usr/local
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C preprocessor: gcc -E
      CPPFLAGS:       
      C compiler:     gcc
      CFLAGS:         -g -O2
      C++ compiler:   g++ -std=c++17
      CXXFLAGS:       -g -O2
      LDFLAGS:        -Wl,-rpath,/home/nooshin/Desktop/FEC_HTTP/ngtcp2/ngtcp2/../openssl/build/lib
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Libtool:
      LIBTOOL_LDFLAGS: 
    Crypto helper libraries:
      libngtcp2_crypto_openssl:   yes
      libngtcp2_crypto_gnutls:    no
      libngtcp2_crypto_boringssl: no
      libngtcp2_crypto_picotls:   no
    Test:
      CUnit:          no (CFLAGS='' LIBS='')
    Debug:
      Debug:          no (CFLAGS='')
    Libs:
      OpenSSL:        yes (CFLAGS='-I/home/nooshin/Desktop/FEC_HTTP/ngtcp2/openssl/build/include' LIBS='-L/home/nooshin/Desktop/FEC_HTTP/ngtcp2/openssl/build/lib -lssl -lcrypto')
      Libev:          no (CFLAGS='' LIBS='')
      Libnghttp3:     yes (CFLAGS='-I/home/nooshin/Desktop/FEC_HTTP/ngtcp2/nghttp3/build/include' LIBS='-L/home/nooshin/Desktop/FEC_HTTP/ngtcp2/nghttp3/build/lib -lnghttp3')
      Jemalloc:       yes (CFLAGS='' LIBS='-ljemalloc')
      GnuTLS:         no (CFLAGS='' LIBS='')
      BoringSSL:      no (CFLAGS='' LIBS='')
      Picotls:        no (CFLAGS='' LIBS='')
    Examples:         no

What is the problem with these "no"s? Specially examples.

**Comment by tatsuhiro-t** [comment]
For ngtcp2, examples are disabled because libev was not found.

**Comment by NooshinEghbal** [comment]
Thanks.

Now here is the summery for nghttp3:

Package version: 0.6.0-DEV
    Library version: 2:1:0
    Install prefix:  /home/nooshin/Desktop/FEC_HTTP/ngtcp2/nghttp3/build
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C preprocessor: gcc -E
      CPPFLAGS:       
      C compiler:     gcc
      CFLAGS:         -g -O2
      C++ compiler:   g++ -std=c++17
      CXXFLAGS:       -g -O2
      LDFLAGS:        
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Test:
      CUnit:          yes (CFLAGS='' LIBS='-lcunit')
    Debug:
      Debug:          no (CFLAGS='')
    Library only:     yes
    Examples:         no
============================================================================
Testsuite summary for nghttp3 0.6.0-DEV
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

Why the examples of nghttp3 is "no"?

here is the summery for ngtcp2:

Package version: 0.7.0-DEV
    Library version: 5:0:0
    Install prefix:  /usr/local
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C preprocessor: gcc -E
      CPPFLAGS:       
      C compiler:     gcc
      CFLAGS:         -g -O2
      C++ compiler:   g++ -std=c++17
      CXXFLAGS:       -g -O2
      LDFLAGS:        -Wl,-rpath,/home/nooshin/Desktop/FEC_HTTP/ngtcp2/ngtcp2/../openssl/build/lib
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Libtool:
      LIBTOOL_LDFLAGS: 
    Crypto helper libraries:
      libngtcp2_crypto_openssl:   yes
      libngtcp2_crypto_gnutls:    no
      libngtcp2_crypto_boringssl: no
      libngtcp2_crypto_picotls:   no
    Test:
      CUnit:          yes (CFLAGS='' LIBS='-lcunit')
    Debug:
      Debug:          no (CFLAGS='')
    Libs:
      OpenSSL:        yes (CFLAGS='-I/home/nooshin/Desktop/FEC_HTTP/ngtcp2/openssl/build/include' LIBS='-L/home/nooshin/Desktop/FEC_HTTP/ngtcp2/openssl/build/lib -lssl -lcrypto')
      Libev:          yes (CFLAGS='' LIBS='-lev')
      Libnghttp3:     yes (CFLAGS='-I/home/nooshin/Desktop/FEC_HTTP/ngtcp2/nghttp3/build/include' LIBS='-L/home/nooshin/Desktop/FEC_HTTP/ngtcp2/nghttp3/build/lib -lnghttp3')
      Jemalloc:       yes (CFLAGS='' LIBS='-ljemalloc')
      GnuTLS:         no (CFLAGS='' LIBS='')
      BoringSSL:      no (CFLAGS='' LIBS='')
      Picotls:        no (CFLAGS='' LIBS='')
    Examples:         yes

============================================================================
Testsuite summary for ngtcp2 0.7.0-DEV
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

How can I install GnuTLS, BoringSSL, Picotls on Ubuntu?

Thanks.
