### ISSUE TITLE
connection migration issues

### ISSUE THREAD

**Issue by flx413** [ngtcp2/ngtcp2#290]
client invoked 'ngtcp2_conn_initiate_migration' interface, how can client be notified the connection migration success finally?
thanks a lot for your help.

**Comment by tatsuhiro-t** [comment]
https://nghttp2.org/ngtcp2/types.html#c.ngtcp2_path_validation is called when path validation succeeds, and then client migrates to new local address.

**Comment by flx413** [comment]
thanks! but I'm still a little confused.
I want to simulate connection migration,used command:

`
./server 127.0.0.1 50000 ../interop/server.key ../interop/server.crt  
`
`
./client 127.0.0.1 50000 --delay-stream=10 --change-local-addr=5
`

I found server sent 'PATH_CHALLENGE' frame and client responded 'PATH_RESPONSE' when client changed local address, then server invoked 'ngtcp2_path_validation' callback. Client not send 'PATH_CHALLENGE', client not invoked 'ngtcp2_path_validation'?

**Comment by flx413** [comment]
I think client should write 'PATH_CHALLENGE' frame when initial connection migration, but I didn't see it after running the demo.
![image](https://user-images.githubusercontent.com/30550274/115531668-a2e46200-a2c7-11eb-8526-1b1868ee66b5.png)

figure reference: https://tools.ietf.org/id/draft-tan-quic-connection-migration-00.html

**Comment by tatsuhiro-t** [comment]
As far as I know, it is not a MUST requirement for client to send PATH_CHALLENGE before migrating to new local address.
The examples/client uses `ngtcp2_conn_initiate_immediate_migration` function which does not send PATH_CHALLENGE.
If `ngtcp2_conn_initiate_migration` function is used instead, it first sends PATH_CHALLENGE and if it sees PATH_RESPONSE from server, it migrates to the new address.

**Comment by flx413** [comment]
thanks!
