### ISSUE TITLE
 unable to restart idle timer accurately when sending packet

### ISSUE THREAD

**Issue by gangwn** [ngtcp2/ngtcp2#295]
The demo server restart the idle timer every time after sending a packet, the packet could be following types:
1. first ack-eliciting packet since last receiving a packet
2. retransmited first ack-eliciting packet
3. second ack-eliciting packet
4. non ack-eliciting packet

From the description in RFC9000, only type-1 packet should restart idle timer. Application is unable to check the type of sending packet from ngtcp2_conn_writev_stream, so does ngtcp2 has plans to tell application which packet can restart idle timer?

_An endpoint restarts its idle timer when a packet from its peer is received and processed
successfully. An endpoint also restarts its idle timer when sending an ack-eliciting packet if no
other ack-eliciting packets have been sent since last receiving and processing a packet. Restarting
this timer when sending a packet ensures that connections are not closed after new activity is
initiated._

**Comment by tatsuhiro-t** [comment]
`ngtcp2_conn_get_idle_expiry` returns the time instant when idle timer expires.  If application remembers the last value, it can easily determine whether it is updated or not.

**Comment by gangwn** [comment]
got it! it fixed my problems
