### ISSUE TITLE
ngtcp2_crypto_hp_mask corrupts caller's memory

### ISSUE THREAD

**Issue by ngorskikh** [ngtcp2/ngtcp2#300]
Doc for `ngtcp2_crypto_hp_mask` says that `dest` must have 5 bytes available, but this:
https://github.com/ngtcp2/ngtcp2/blob/7284e99bae11b8b9789a857f83f1b6bc1ec220a0/crypto/boringssl/boringssl.c#L347
writes 16 bytes to `dest`, possibly corrupting memory if passed a buffer of lesser size.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  The documentation has been updated to make sure that buffer must have at least 16 bytes; see 6753091e427b71bb0fec48ad4822cc46fea29b55
