### ISSUE TITLE
Packet loss detection timer may not be set in conn_recv_ack.

### ISSUE THREAD

**Issue by plarose** [ngtcp2/ngtcp2#302]
This issue has been introduced in change: d6e2e62fc6776afaeff643ba838e4c23e4fff558.

The function "conn_recv_ack" calls "ngtcp2_rtb_recv_ack" -> "rtb_detect_lost_pkt".  The latter is removing from list all packets who are considered as lost.
In case where all packets are considered as lost (and all removed from list), the loss detection timer needs to be resetted by calling "ngtcp2_conn_set_loss_detection_timer".  But it may not be resetted; the function "conn_recv_ack" may return before reaching the call to "ngtcp2_conn_set_loss_detection_timer".

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  I think 9ca518fb6698f478e4afa63c44313c19de06bce4 fixes it.

**Comment by plarose** [comment]
Thanks for quick response.  The fix provided fixes the issue.  Closing this issue.
