### ISSUE TITLE
How to add personalized transport parameters?

### ISSUE THREAD

**Issue by skyerguo** [ngtcp2/ngtcp2#303]
How can I simply add personalized transport parameters in QUIC packet?
If I only need to add some variables in "client.cc" and "server.cc", or change some files like "ngtcp2_crypto.cc" in the lib folder?
Thanks.

**Comment by tatsuhiro-t** [comment]
Do you mean you are trying to add custom non-standard transport parameters?  Currently there is no easy way to do this.  You need to modify encoder/decoder functions and pass some values in client and server.

**Comment by dr7ana** [comment]
@tatsuhiro-t Is there any possibility of doing this with the newest ngtcp2 versions? I see [RFC 9000](https://www.rfc-editor.org/rfc/rfc9000#name-reserved-transport-paramete) has facility for reserved parameters that are ignored. If I'm thinking about it correctly, that would open the door for coordinating extra information at connection creation? Asking this in regards to a custom quic [implementation](https://github.com/oxen-io/oxen-libquic) we are building using ngtcp2

**Comment by tatsuhiro-t** [comment]
At the moment, no plan for this feature.  It does not mean we won't do this, but at least ngtcp2 v1.0.0 does not have this kind of API.
