### ISSUE TITLE
Maybe issue with ngtcp2 when generating a fragmented CRYPTO frame ?

### ISSUE THREAD

**Issue by lcuminato** [ngtcp2/ngtcp2#304]
Hi,

I came across this scenario when trying to enable 0-RTT using a server that requires mutual auth. I believe in this case the session ticket includes the client's cert as well so the crypto information is bigger and ngtcp2 splits the CRYPTO frame into two datagrams, each containing an Initial packet. Problem is that the second UDP datagram is smaller than 1200 bytes and nginx declines the packet. Even when trying with NGTCP2_WRITE_STREAM_FLAG_MORE to coalesce packets into the same datagram, the final datagram size is still smaller than 1200 bytes. Shouldn't ngtcp2 add padding to the second Initial packet ?

Thanks

**Comment by tatsuhiro-t** [comment]
It looks like ngtcp2 correctly pads to Initial only packet, but does not if 0RTT packet is coalesced with it.  Will fix it.

**Comment by tatsuhiro-t** [comment]
0799acce6474f512dd10a8d3ad72b18b7e7956aa should fix this issue.

**Comment by lcuminato** [comment]
Thanks for the quick QUIC fix. I was able to verify that it indeed works but apparently the padding frame is going into the 0-RTT packet instead of the second Initial packet. Is this a security concern ?
