### ISSUE TITLE
How to process 0RTT packet

### ISSUE THREAD

**Issue by xiaozhihong** [ngtcp2/ngtcp2#307]
`        case NGTCP2_PKT_0RTT:
          send_retry(&hd, ep, *local_addr, &su.sa, msg.msg_namelen);
          continue;
        }
`
I found the code above in examples, is there any other way to process 0rtt data, instead of sending a retry packet? Thanks.

**Comment by tatsuhiro-t** [comment]
Retry packet is not required for 0RTT.  Client sends Initial packet, and then 0RTT packet.  Server can process them without Retry packet.  If 0RTT packet is received before Initial, ngtcp2 server will send Retry so that it does not need to buffer packet in unknown origin.
