### ISSUE TITLE
Is there a way to pause receiving data from the stream?

### ISSUE THREAD

**Issue by rhoxn** [ngtcp2/ngtcp2#308]
I want to temporarily stop receiving when there is not enough memory or other reason.
I can prevent reception by not calling ngtcp2_conn_read_pkt() when a packet is received, but then all other streams and control packets will also be stopped.

**Comment by tatsuhiro-t** [comment]
Consider to set stream-level connection window to match the amount of memory you can afford. See https://nghttp2.org/ngtcp2/types.html#c.ngtcp2_settings

**Comment by rhoxn** [comment]
Thanks for the reply.
My understanding is that ngtcp2_settings.max_window and max_stream_window control the receive buffer inside ngtcp2 according to the transfer rate.

Let me clarify the scenario I am concerned about.
For example, let's say I want to transfer a 1GB file. And the transfer rate is 10MB/s and the speed of the destination storage is 1MB/s (very slow).
The file transfer will be completed in 100 seconds. 100MB will be written to the storage, and 900MB will stay in the memory.
Thus, depending on the transfer rate and the storage speed, the client memory will be consumed in a large amount. Therefore, my request is to control the flow between ngtcp2 and the application.

For example, if the application can only receive a portion of the data, we would like to have a feature that specifies the size of the received data in the return value of ngtcp2_recv_stream_data callback function. After that, I think it would be good to have an API that resumes the receive callback when the application is ready to receive data.

In the case of the socket API, this can be controlled by simply not calling recv() until the application is ready.

**Comment by tatsuhiro-t** [comment]
I think you should call [ngtcp2_conn_extend_max_stream_offset](https://nghttp2.org/ngtcp2/ngtcp2_conn_extend_max_stream_offset.html) after an application completed to write data to a storage when the buffer is running out.

**Comment by rhoxn** [comment]
Thank you so much. It looks good. I did not understand the API.

My understanding is that the application must call ngtcp2_conn_extend_max_stream_offset() after processing the data. Otherwise, the receive buffer in ngtcp2 will be full, and then the recv_stream_data callback will not be called.

Is this correct?

**Comment by tatsuhiro-t** [comment]
ngtcp2 library does not buffer incoming data.  There is per-stream flow control credit that a sender has to obey.  If it runs out the credit, it cannot send data.  ngtcp2_conn_extend_max_stream_offset gives back certain amount of credit to the sender and controls the amount of data it can send.

**Comment by rhoxn** [comment]
Finally understood, learned a lot about ngtcp2 and Quic flow control.

**Comment by redbaron** [comment]
>  There is per-stream flow control credit that a sender has to obey.

What if they don't ? In this case IO loop keep receiving packets and keep feeding them into `ngtcp2_conn_read_pkt()` , which in turn calls   `recv_stream_data` .  If packet rate exceeds  flow control window, will ngtcp2 drop it without calling `recv_stream_data` ?
