### ISSUE TITLE
Error code is not preserved in RST ACK path

### ISSUE THREAD

**Issue by JunqiWang** [ngtcp2/ngtcp2#310]
In https://github.com/ngtcp2/ngtcp2/blob/main/lib/ngtcp2_rtb.c#L720, we're passing hard coded NO_ERROR, however, I think it makes more sense to pass the error code that's originally encoded in the RESET_STREAM frame.

Should we save the error code somewhere and retrieve it and pass it to `ngtcp2_conn_close_stream_if_shut_rdwr` here?

**Comment by tatsuhiro-t** [comment]
When sending RESET_STREAM or STOP_SENDING, app_error_code is stored to ngtcp2_strm.app_error_code.
The case we do not handle well is when STOP_SENDING or RESET_STREAM is received.

**Comment by tatsuhiro-t** [comment]
f4c32460ea42ca3677a7478324c4445a2530e760 will fix this.
app_error_code parameter passed to ngtcp2_conn_close_stream_if_shut_rdwr should be removed because it is hard to use and in most cases it is not used, like the code you pointed out.

**Comment by JunqiWang** [comment]
Thanks @tatsuhiro-t.
