### ISSUE TITLE
How to manage the stream data buffer

### ISSUE THREAD

**Issue by xiaozhihong** [ngtcp2/ngtcp2#318]
I use std::string as stream send buffer. And write down the code like this

```cpp

// payload_ is member of my class.
ngtcp2_ssize ndatalen = -1;
int udp_buffer_len = 1500;
uint8_t* udp_buffer = new uint8_t[udp_buffer_len];
ngtcp2_conn_write_stream(conn, path, nullptr, udp_buffer, udp_buffer_len, &ndatalen, 0, 0, payload_.data(), payload_.size(), now_ns);

if (ndatalen > 0) {
    payload_.erase(0, ndatalen);
}

```

I noticed that the receiver side received a different payload in some cases. (When high loss rate of the link)
Then I found there have a callback function `acked_stream_data_offset`,  and it seems that the user should manage the buffer by himself, and should not free or realloc it before peer acked stream data.
If I don't specify the callback function, how can I know when to free the buffer.

Is my understand correct? Is libngtcp2 just hold the point of data?

**Comment by tatsuhiro-t** [comment]
The passed stream data must be kept alive:

> The number of data encoded in STREAM frame is stored in *pdatalen if it is not NULL. The caller must keep the portion of data covered by *pdatalen bytes in tact until ngtcp2_acked_stream_data_offset indicates that they are acknowledged by a remote endpoint or the stream is closed.

If you do not specify ngtcp2_acked_stream_data_offset, you cannot free the data until stream is closed.

std::string.erase most likely changes the memory address of data, so it does not work in retransmission.

**Comment by xiaozhihong** [comment]
> The passed stream data must be kept alive:
> 
> > The number of data encoded in STREAM frame is stored in *pdatalen if it is not NULL. The caller must keep the portion of data covered by *pdatalen bytes in tact until ngtcp2_acked_stream_data_offset indicates that they are acknowledged by a remote endpoint or the stream is closed.
> 
> If you do not specify ngtcp2_acked_stream_data_offset, you cannot free the data until stream is closed.
> 
> std::string.erase most likely changes the memory address of data, so it does not work in retransmission.

Thanks for your reply. It's my careless ignored the annotation of the function.

**Comment by xiaozhihong** [comment]
By the way,  is it possible to manage the stream buffer by ngtcp2 itself? Just like buffered the encrypted data in this [commit](https://github.com/ngtcp2/ngtcp2/commit/1b84fdd332764d21776e66ea4d0c3c9f53bf2da4)

**Comment by tatsuhiro-t** [comment]
At the moment, there is no plan to do that for the time being.  Buffering CRYPTO is done because application is typically has no interest in it.
On the other hand, application data is its main interest.  In most cases, it already created buffers for them.  Just using references avoids extra copy.

**Comment by xiaozhihong** [comment]
I closed the issue, thanks again.
