### ISSUE TITLE
ngtcp2_pkt_decode_version_cid return code

### ISSUE THREAD

**Issue by pavelxdd** [ngtcp2/ngtcp2#319]
`ngtcp2_pkt_decode_version_cid` returns 1 if Version Negotiation packet should be sent.

Maybe it should return `NGTCP2_ERR_VERSION_NEGOTIATION` for consistency with other functions, such as `ngtcp2_accept`?

**Comment by tatsuhiro-t** [comment]
Agreed.
60e2d9640165405b1c11e89ecc904acacc30992f makes this change.
