### ISSUE TITLE
Migration broken due to "Rework max_udp_payload_size" commit

### ISSUE THREAD

**Issue by Natris** [ngtcp2/ngtcp2#320]
The relevant commit is 670949511b1de69320629a1d0c6f858684691cb5 .

The issue is that dcids in conn_select_preferred_addr, ngtcp2_conn_initiate_immediate_migration and ngtcp2_conn_initiate_migration are not initialized correctly and have max_udp_payload_size zero. 

While the first is pretty easy to fix, the next two would require a temporary path to be created so that ngtcp2_dcid_set_path can be used. I am not sure how you would prefer to have this fixed.

In my reworked migration fork it is hopefully fixed by https://github.com/Natris/ngtcp2/pull/2/commits/42b2d317abdf6666bd9f478483d91786abfb4f53 as I already have the data in the form of path.

**Comment by tatsuhiro-t** [comment]
Thank you for telling me.  Fix committed via 9518e999

**Comment by tatsuhiro-t** [comment]
And now ngtcp2_conn_initiate_migration takes path rather than address, just like ngtcp2_select_preferred_addr callback.

**Comment by Natris** [comment]
great! Thanks.
