### ISSUE TITLE
ngtcp2_rtb_recv_ack's "assert(cc_ack.pkt_delivered <= ent->rst.delivered)" fires after migration

### ISSUE THREAD

**Issue by Natris** [ngtcp2/ngtcp2#321]
First, I want to stress that I am using modified client side which splits path validation and migration; however the assert fires in server, which should (I hope) be unchanged. If the client is sending crap to the server (which is possible), it should probably not assert but fail cleanly.

It seems that if there is a delay between receiving of info about successful path validation on client side and actual migration (so that ack timers fire on (one of or both) client and server side), after a successful migration ACKs embedded in PATH_RESPONSE packet sent by client trigger an assert in ngtcp2_rtb_recv_ack.

Please note that this is timing dependent, I can 100% reliably induce this by adding breakpoint to client's path validation callback and waiting there second or two (which for me delays actual migration); without this all works fine. I can not guarantee it is caused by the acks being triggered to be sent.

Please does the logic cope correctly with path migration on the server side? Is the assert correct?

Server receives PATH_RESPONSE with ACKs:
```
2021-09-06 16:47:54.612+0200 [52227:ddbe04] DEBUG   ngtcp2_conn : conn 1: (server) I00004106 0x24a2305d83622acd70e795c97f008a722bba frm rx 8 Short(0x40) PATH_RESPONSE(0x1b) data=0xff2400cb22c57eb5
2021-09-06 16:47:54.612+0200 [52227:ddbe04] DEBUG   ngtcp2_conn : conn 1: (server) I00004106 0x24a2305d83622acd70e795c97f008a722bba ptv path has been validated
2021-09-06 16:47:54.612+0200 [52227:ddbe04] DEBUG   quic_conn   : conn 1: (server) path validation against path {local: [127.0.0.1]:62252, remote: [192.168.0.1]:62252} succeeded
2021-09-06 16:47:54.612+0200 [52227:ddbe04] DEBUG   http3_engine: conn 1: server just migrated to a new path client [192.168.0.1].62252 server[127.0.0.1].62252
2021-09-06 16:48:01.934+0200 [52227:ddbe04] DEBUG   ngtcp2_conn : conn 1: (server) I00004106 0x24a2305d83622acd70e795c97f008a722bba frm rx 8 Short(0x40) ACK(0x02) largest_ack=7 ack_delay=1(130) ack_block_count=0
2021-09-06 16:48:01.934+0200 [52227:ddbe04] DEBUG   ngtcp2_conn : conn 1: (server) I00004106 0x24a2305d83622acd70e795c97f008a722bba frm rx 8 Short(0x40) ACK(0x02) block=[7..5] block_count=2
2021-09-06 16:48:01.934+0200 [52227:ddbe04] DEBUG   ngtcp2_conn : conn 1: (server) I00004106 0x24a2305d83622acd70e795c97f008a722bba rcv latest_rtt=2 min_rtt=2 smoothed_rtt=3 rttvar=1 ack_delay=1
2021-09-06 16:48:44.572+0200 [52227:ddbe04] DEBUG   ngtcp2_conn : conn 1: (server) I00004106 0x24a2305d83622acd70e795c97f008a722bba rcv pkn=6 acked, slow start cwnd=12118
Assertion failed: (cc_ack.pkt_delivered <= ent->rst.delivered), function ngtcp2_rtb_recv_ack, file /Users/ondrejkolacek/.conan/data/ngtcp2/0.1/avu/local/build/baa049ddcf948195eaff13d6115dd85928470ab5/ngtcp2-0.1/lib/ngtcp2_rtb.c, line 933.
```

during processing of the acks,  in ngtcp2_rtb_recv_ack, in second iteration of loop 
```
if (conn) {
    for (ent = acked_ent; ent; ent = acked_ent) {
```
this assert fires:
`assert(cc_ack.pkt_delivered <= ent->rst.delivered);`

ent chain contains two items
// content of ent at initial "for (ent = acked_ent; ent; ent = acked_ent) {"
```
(lldb) p *ent
(ngtcp2_rtb_entry) $1 = {
  next = 0x00006080000096a0
  hd = (pkt_num = 6, type = 64 '@', flags = 0 '\0')
  frc = 0x000060b000014f10
  ts = 1497929209124323
  lost_ts = 18446744073709551615
  pktlen = 79
  rst = (delivered = 2485, delivered_ts = 1497929206840412, first_sent_ts = 1497929206840412, is_app_limited = 0)
  flags = '\x06' 6 '\x06'
}
```
```
(lldb) p *ent->next
(ngtcp2_rtb_entry) $2 = {
  next = NULL
  hd = (pkt_num = 7, type = 64 '@', flags = 0 '\0')
  frc = NULL
  ts = 1497929209850058
  lost_ts = 18446744073709551615
  pktlen = 44
  rst = (delivered = 0, delivered_ts = 1497929209850058, first_sent_ts = 1497929209850058, is_app_limited = 0)
  flags = '$' 36 '$'
}
```

//content of  cc_ack (at initial "for (ent = acked_ent; ent; ent = acked_ent) {")
```
(lldb) p cc_ack
(ngtcp2_cc_ack) $3 = {
  prior_bytes_in_flight = 88
  bytes_delivered = 0
  bytes_lost = 0
  pkt_delivered = 0
  largest_acked_sent_ts = 0
}
```

//content of cc_ack when assert "assert(cc_ack.pkt_delivered <= ent->rst.delivered);" is triggered in the second iteration (on *ent-> next being ent)
```
(lldb) p cc_ack
(ngtcp2_cc_ack) $4 = {
  prior_bytes_in_flight = 88
  bytes_delivered = 123
  bytes_lost = 0
  pkt_delivered = 2485
  largest_acked_sent_ts = 0
}
(lldb) p cc_ack.pkt_delivered
(uint64_t) $5 = 2485
(lldb) p ent->rst.delivered
(uint64_t) $6 = 0
```

I have attached full log, hopefully it will not be needed: [srv_log6.txt](https://github.com/ngtcp2/ngtcp2/files/7116855/srv_log6.txt): in it, client side is identified by "conn 1000:", server side as "conn 1:"

How did we get there? This unblocks client's path validation packets
`2021-09-06 16:47:50.526+0200 [52227:ddbe04] DEBUG   http3_engine: conn 1: validation of path between client [192.168.0.1].62252 and server[127.0.0.1].62252 finished with 0`

Here "path validated" call is invoked; however unlike in the the mainline, the path is not changed immediately, we are still using the old path. It is necessary to wait here a bit to trigger ack timers on both client and server side, I just wait few seconds in debugger. Within this callback I schedule 0 second timer to initiate migration outside of the callback:
`2021-09-06 16:47:50.528+0200 [52227:ddbe04] DEBUG   quic_conn   : conn 1000: (client) path validation against path {local: [192.168.0.1]:62252, remote: [127.0.0.1]:62252} succeeded`

Here immediate migration is performed. It should use new dcid as we throw away the old one.
`2021-09-06 16:47:54.606+0200 [52227:ddbe04] DEBUG   http3_client: conn 1000: migrating to path (l=[192.168.0.1].62252,r=[127.0.0.1].62252,id=0)`

this triggers path validation by the server.

Server's path validation callback is invoked; this means that the path has successfully migrated:
`2021-09-06 16:47:54.612+0200 [52227:ddbe04] DEBUG   http3_engine: conn 1: server just migrated to a new path client [192.168.0.1].62252 server[127.0.0.1].62252`

Acks from the same packet cause assert to fire.

**Comment by Natris** [comment]
I will try to dive deeper tomorrow; however this part seems pretty complex and not really well documented, maybe the issue is clear to you at first glance. It may also be caused by my modification, but it seems to me that this could be something that rarely surfaces in normal workflow. The numbers of packets on old and new path are similar etc...

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  On path migration, server resets congestion state, which resets delivered value and the current assertion fails because it expects monotonic increase of it.  As you wrote, assertion might not be correct.  Will check.

**Comment by tatsuhiro-t** [comment]
I made a commit d4aba14d which I think fixes this assertion failure.
I have not repoduced this bug, but in theory, cc_pkt should use packets sent after cc state reset.  The patch will do this which should fix the bug.

**Comment by Natris** [comment]
thanks that has fixed the issue
