### ISSUE TITLE
How to detect a remote endpoint has received a fin?

### ISSUE THREAD

**Issue by rhoxn** [ngtcp2/ngtcp2#323]
If the ngtcp2_acked_stream_data_offset callback is called with datalen 0, we know that the remote endpoint has definitely received fin.
However, if the callback was not called with datalen 0, it is not exactly known.

The case when the callback is not called with datalen 0 occurs when ngtcp2_conn_write_stream() is called with the fin flag specified along with the application data.
However, if ngtcp2_conn_write_stream() is called without fin flag and with application data, and immediately after that ngtcp2_conn_write_stream is called with fin flag and without application data, we expect that the ack will be combined and ngtcp2_acked_stream_data_offset may not be called with datalen 0.

In this case, there is no way to determine whether fin was received or not.
Or is it guaranteed that ack will not be bound and ngtcp2_acked_stream_data_offset will be called back with datalen 0?
I need this mechanism to gracefully shutdown the stream transmission.

Adding fin flag to the argument of ngtcp2_acked_stream_data_offset may help.

**Comment by tatsuhiro-t** [comment]
To gracefully shutdown stream, application should wait for ngtcp2_stream_close callback is invoked.
When it is called, it is guaranteed that all application data is acknowledged unless ngtcp2_conn_shutdown_stream_write or ngtcp2_conn_shutdown_stream is called.

This requires the remote endpoint to send fin or close its write side.  To elicit this, you can call ngtcp2_conn_shutdown_stream_read.

**Comment by rhoxn** [comment]
Thank you so much.
I have tested the scenario you gave me and the additional cases.

Action | Client side ngtcp2_stream_close() app_error_code | Server side ngtcp2_stream_close() app_error_code
------- | ------------ | -------------
Client send fin and server send fin | 0 | 0
Client send fin and call ngtcp2_conn_shutdown_stream_read(c, s, 123) | 123 | 0
Client call ngtcp2_conn_shutdown_stream_write(c, s, 123) and server send fin | 0 | 123
Client call ngtcp2_conn_shutdown_stream(c, s, 123) | 123 | 0

Looking at the first three cases, I thought the ngtcp2_stream_close callback was notifying me of error codes related to reception.
However, in the last case, contrary to my expectation, the server side ngtcp2_stream_close callback notified me of 0.

How should I interpret the app_error_code value reported by the ngtcp2_stream_close callback?

**Comment by tatsuhiro-t** [comment]
ngtcp2 has a bug which prevents app_error_code from being passed to callback correctly.
09754df080c926ea693cdd4b1723d2e6dfac439a fixes it.

**Comment by rhoxn** [comment]
Thanks for the quick fix!
The behavior after the fix is as follows.

Action | Client side ngtcp2_stream_close() app_error_code | Server side ngtcp2_stream_close() app_error_code
-- | -- | --
Client send fin and server send fin | Not Set | Not Set
Client send fin and call ngtcp2_conn_shutdown_stream_read(c, s, 123) | 123 | 123
Client call ngtcp2_conn_shutdown_stream_write(c, s, 123) and server send fin | 123 | 123
Client call ngtcp2_conn_shutdown_stream(c, s, 123) | 123 | 123

I have an additional question about the behavior of ngtcp2_conn_shutdown_stream_read, but it's off topic, so I'll make another Issue.
