### ISSUE TITLE
BBR aggressive

### ISSUE THREAD

**Issue by xiaozhihong** [ngtcp2/ngtcp2#327]
<img width="1576" alt="ngtcp2_bbr_issue" src="https://user-images.githubusercontent.com/8449258/134813742-b6101ceb-2013-4fd0-9008-b322a9763c47.png">
I implement the quic video server and quic video client, client sends 30fps video to the server using bbr algorithm. And I test it in different network conditions. I set the loss rate from 0% to 45% before I published a video to the server, the result is shown above.
The version of ngtcp2 is newest(commit id 390b4e6f0eb1d10bc7a6430c539b8ee136196146)
The result showed that the implementation of BBR in ngtcp2 is too aggressive and not fair. BBR's max pacing gain is 5/4(1.25), any network that has a loss rate >= 25% will harm BBR's transmit rate.

I review the implementation of BBR several times, and could not found where the problem is.
Maybe calculate the wrong sample_rate or have some state error/logic bugs in ngtcp2_bbr.c.

**Comment by tatsuhiro-t** [comment]
What happens if [these lines](https://github.com/ngtcp2/ngtcp2/blob/390b4e6f0eb1d10bc7a6430c539b8ee136196146/lib/ngtcp2_bbr.c#L385-L386) are removed?

**Comment by tatsuhiro-t** [comment]
The BBR v1 draft (published in 2017) we implemented does not treat loss as congestion signal, it is understandable that it sends more packets and gets more packet losses in high loss environment.
I do not know which TCP BBR implementation you are comparing with, but I think that it probably has some tweaks to deal with these circumstances.

**Comment by xiaozhihong** [comment]
> The BBR v1 draft (published in 2017) we implemented does not treat loss as congestion signal, it is understandable that it sends more packets and gets more packet losses in high loss environment. I do not know which TCP BBR implementation you are comparing with, but I think that it probably has some tweaks to deal with these circumstances.

I use this version [BBR 4.15.0-142](https://elixir.bootlin.com/linux/v4.15/source/net/ipv4/tcp_bbr.c)

**Comment by xiaozhihong** [comment]
> What happens if [these lines](https://github.com/ngtcp2/ngtcp2/blob/390b4e6f0eb1d10bc7a6430c539b8ee136196146/lib/ngtcp2_bbr.c#L385-L386) are removed?

I removed the code, and cause the same behaviors.
![image](https://user-images.githubusercontent.com/8449258/135383989-b6fdd33a-10ac-47c8-ac8f-1fdf74dd77ca.png)

**Comment by xiaozhihong** [comment]
I found some codes potential cause the problem.

### The deliver rate maybe too high.
https://github.com/ngtcp2/ngtcp2/blob/c50e0576f9b6c7e50a77adf6927597b29e5ec38b/lib/ngtcp2_rst.c#L98-L101

### The implement of window_filter seems different from win_minmax in Linux kernel.
https://github.com/ngtcp2/ngtcp2/blob/c50e0576f9b6c7e50a77adf6927597b29e5ec38b/lib/ngtcp2_window_filter.c

**Comment by tatsuhiro-t** [comment]
What if these lines are changed to something like this:

```diff
diff --git a/lib/ngtcp2_rst.c b/lib/ngtcp2_rst.c
index 5ade90e8..bc309b36 100644
--- a/lib/ngtcp2_rst.c
+++ b/lib/ngtcp2_rst.c
@@ -95,7 +95,7 @@ int ngtcp2_rst_on_ack_recv(ngtcp2_rst *rst, ngtcp2_conn_stat *cstat,
 
   rate = rs->delivered * NGTCP2_SECONDS / rs->interval;
 
-  if (rate > ngtcp2_window_filter_get_best(&rst->wf) || !rst->app_limited) {
+  if (!rst->app_limited) {
     ngtcp2_window_filter_update(&rst->wf, rate, rst->round_count);
     cstat->delivery_rate_sec = ngtcp2_window_filter_get_best(&rst->wf);
   }
```

The max filter is originated from google quiche.  I really do not know Linux TCP BBR behaviour is correct one or not.  That is one aspect that BBR development is quite difficult to get it right.

**Comment by tatsuhiro-t** [comment]
Do you use `ngtcp2_conn_update_pkt_tx_time` to pace packets transmission rate?

**Comment by xiaozhihong** [comment]
> Do you use `ngtcp2_conn_update_pkt_tx_time` to pace packets transmission rate?

I call `ngtcp2_conn_update_pkt_tx_time`  when `ngtcp2_conn_write_stream` return 0 before.
```
int ret = ngtcp2_conn_write_stream();
if (ret == 0) {
    ngtcp2_conn_update_pkt_tx_time();
}
```

And I modify call it after function `ngtcp2_conn_write_stream` returned, the problem solved!
```
int ret = ngtcp2_conn_write_stream();
ngtcp2_conn_update_pkt_tx_time();
```

And I have 2 doubts.
1.  Can `ngtcp2_conn_update_pkt_tx_time` call internal in ngtcp2_conn_write_stream instead of call by user?
2. I draw the new graph of the receiver side fps
![ngtcp2_bbr](https://user-images.githubusercontent.com/8449258/135711170-37b3f549-c044-482f-b83b-6a19d1029d6f.png)
"quic_mod" is the code in my repository which commit in https://github.com/xiaozhihong/ngtcp2/commit/9b6d372085904bf4f7a26ef2521e0c5162efbf33
It's better than "quic" and close to "tcp bbr", so the problem I mentioned in https://github.com/ngtcp2/ngtcp2/issues/327#issuecomment-930760134
is still exists.

**Comment by tatsuhiro-t** [comment]
ngtcp2_conn_update_pkt_tx_time must be called by application (user).
It should be called after sending ngtcp2_conn_get_send_quantum() bytes of data.
If you send data but runs out of data before reaching ngtcp2_conn_get_send_quantum() bytes, ngtcp2_conn_update_pkt_tx_time should also be called.
It should not be called if you do not send data at all.

**Comment by xiaozhihong** [comment]
> [9384513](https://github.com/ngtcp2/ngtcp2/commit/9384513151ccc647015b68c31a1c14350e46ef47) fixes spurious loss detection which previously considered most losses spurious.
