### ISSUE TITLE
on_stream_stop_sending and on_reset_stream are doing the same thing

### ISSUE THREAD

**Issue by JunqiWang** [ngtcp2/ngtcp2#328]
They both call `nghttp3_conn_shutdown_stream_read`. Should we consolidate the 2 callbacks?

client: https://github.com/ngtcp2/ngtcp2/blob/main/examples/client.cc#L1521-L1546
server: https://github.com/ngtcp2/ngtcp2/blob/main/examples/server.cc#L849-L886

**Comment by tatsuhiro-t** [comment]
I think what we have now is good enough for the purpose of example code.
