### ISSUE TITLE
Failing in stream_open causes a double-free

### ISSUE THREAD

**Issue by jpboivin** [ngtcp2/ngtcp2#332]
When a stream is discovered, ngtcp2 will trigger the `stream_open` callback. If for some reason this callback fails, `ngtcp2_conn_init_stream` will free the content of the internal stream object with `ngtcp2_strm_free`. As the init is failing, the caller (`conn_recv_stream`) will also free the internal stream object itself (failed to initialize, no need for it). The issue is that the stream is at that point registered inside the connection, and when the connection is destroyed, it will be freed again. I think the root issue is that `ngtcp2_conn_init_stream` do not rollback its insertion on failure.

**Comment by tatsuhiro-t** [comment]
Thank you for telling me.  Fix committed via fdfd2c3196b6fbc2e79c8087e92bd57e5e32450d
