### ISSUE TITLE
BBR Quic Support Lags Behind Cubic

### ISSUE THREAD

**Issue by Matthew7758** [ngtcp2/ngtcp2#333]
![image](https://user-images.githubusercontent.com/6288286/139942131-d1ef6996-603f-4a7a-b6e1-5d47c65a3873.png)
As you can see, the quic BBR server using NGTCP2 lags behind the cubic one, and never reaches max throughput. For clarification, our client is running on a separate server and routes traffic through a machine configured as a router. It uses these settings for modifying traffic to emulate a satellite network before forwarding it to the server:

tc qdisc del dev enp2s0 root

tc qdisc add dev enp2s0 root handle 1:0 netem limit 1000mbit delay 300ms 15ms distribution normal
tc qdisc add dev enp2s0 parent 1:1 handle 10: tbf rate 144mbit buffer 1mbit limit 1000mbit
tc qdisc add dev enp2s0 parent 10:1 handle 100: tbf rate 144mbit burst .05mbit limit 1000mbit
# sudo tc qdisc add dev enp3s0 parent 100:1 handle 1000: tbf rate 80mbit burst .05mbit limit 1000mbit

tc -s qdisc ls dev enp2s0

tc qdisc del dev eno1 root

tc qdisc add dev eno1 root handle 1:0 netem limit 1000mbit delay 300ms 15ms distribution normal
tc qdisc add dev eno1 parent 1:1 handle 10: tbf rate 144mbit buffer 1mbit limit 1000mbit
tc qdisc add dev eno1 parent 10:1 handle 100: tbf rate 144mbit burst .05mbit limit 1000mbit
# sudo tc qdisc add dev enp3s0 parent 100:1 handle 1000: tbf rate 80mbit burst .05mbit limit 1000mbit

tc -s qdisc ls dev eno1

Any advice on getting NGTCP2 to scale at maximum throughput would be excellent. Thank you.

**Comment by tatsuhiro-t** [comment]
It looks like packet loss handling has some bug in ngtcp2 bbr.  1787b6fd277ee97bdee60ed0cee48ab481179f9c fixes it.

**Comment by Matthew7758** [comment]
Ok that bug seems to have been rectified, but for some odd reason it doesn't handle high RTT well. We are running a satellite emulation script that makes RTT around a constant 600ms and limits throughput to 144mbps. 
![image](https://user-images.githubusercontent.com/6288286/143080381-23a7120e-89d6-4062-bf22-4b55a20388e9.png)
![image](https://user-images.githubusercontent.com/6288286/143080423-51107682-fe02-4c20-a50f-62c393a8e90d.png)
Any ideas as to why this could be the case?

**Comment by tatsuhiro-t** [comment]
It looks like the shape of chart is quite different from the one you have first presented.  Have you changed network conditions or how to run client/server or their settings?

**Comment by Matthew7758** [comment]
The only thing we changed was the RTT I believe. First run was with ~50MS latest was with 600RTT. Thinking it might be a CWIN issue... Is there a way to enable a deeper debug print level?

**Comment by tatsuhiro-t** [comment]
qlog is handy.  See --qlog-dir option.  There is web based visualization tool: https://qvis.quictools.info/#/files

**Comment by Matthew7758** [comment]
Ok this is a 600MS RTT link with a 144mbps bandwith limit.
![Capture](https://user-images.githubusercontent.com/6288286/144113140-d806074c-ff9c-41e6-a955-463130527477.PNG)
The CWND is about half of what it should be. Throughput is still low. For a normal TCP connection we get roughly double this throughput. Is there a receiver window limit or cwnd limit or sender window limit on these we can adjust?

**Comment by tatsuhiro-t** [comment]
I do not think there are nobs for these limits.  They are adjusted according to the protocol or cc spec.
I setup 600ms delay and 144mbit rate with tc on loopback and measured the perf with client and server on a single machine.  The result is QUIC takes 60% less time to download 100MiB content, so QUIC is faster than TCP.  I think your setup is different.  Perhaps, loss is involved.  Earlier loss might result in lower number in CWND growth.
Could you share how to setup the tc command on loopback interface to reproduce this issue on a single machine, so that I can dig into it a bit more?

**Comment by Matthew7758** [comment]
Upon further analyzing of the graphs and data, we determined it was the default set congestion window. By using the max-stream-window and max-window flags we were able to achieve similar throughput to our satellite TCP setup which is configured to use a window of 60M to account for high RTT.
