### ISSUE TITLE
Alignment specifier does not work as expected

### ISSUE THREAD

**Issue by jpboivin** [ngtcp2/ngtcp2#337]
Hello,

This commit (https://github.com/ngtcp2/ngtcp2/commit/00713cb932f7d55f17aa6bfdfbc2de813e7b5494) introduced alignment specifiers on some structures. It seems that it does not work as expected when combined with the `auto` keyword in C++ on GCC and Clang. It would silently compile with earlier versions of Clang, but Clang 13 introduced a new warning so at least it is detected at compile-time now (`-Walign-mismatch`) instead of being UB.

If you write the following code, the alignment of the variable will be the natural alignment (4) even if the alignment of the type seems to be 8.
```
const auto packetInfo2 = ngtcp2_pkt_info{};
```

Digging a bit around, I think the issue is that the alignment is applied to the type alias, and not the underlying structure. `auto` probably uses the underlying structure when doing type deduction. In C++, `alignas` is prohibited in type aliases (both `using` and `typedef`), so it seems to be a corner case that isn't properly supported by the `__attribute__` even if it compiles fine. I made a small code snippet that reproduce the issue: https://godbolt.org/z/19h41qncq

The fix would be to add the alignment specifier before, like for MSVC. With that said, I'm no C expert, so I'm not sure if is right or wrong in that language. I'd tend to say it should be right too, but I might be missing something.

Note. Behavior is the same with GCC or earlier Clang versions. `auto` variables will not respect the alignment specifier if it is after the type. It just happens that misaligned pointer params are not detected at compile-time with a warning.

**Comment by tatsuhiro-t** [comment]
Thank you for letting me know.  The behaviour around auto is quite interesting.  I missed the text in gcc documentation that attribute can be put after struct keyword.  All the examples put it after the '}'.  Will fix it.

**Comment by tatsuhiro-t** [comment]
Fix committed via cc97643c3ce32e5f2c84270fd878ab324cde9600

**Comment by AhmedShah63** [comment]
cc97643
