### ISSUE TITLE
Question about stream IDs

### ISSUE THREAD

**Issue by pavelxdd** [ngtcp2/ngtcp2#340]
Hello. I'm trying to establish a QUIC connection with https://nghttp2.org via ngtcp2 in my application.
After a successful handhsake, my `stream_open` callback is being called 3 times with 3 streams opened in that order (always the same): 3, 11, 7

As per RFC9000 from 2.1: 

- The stream space for each type begins at the minimum value (0x00 through 0x03, respectively); successive streams of each type are created with numerically increasing stream IDs. **A stream ID that is used out of order results in all streams of that type with lower-numbered stream IDs also being opened.**

But when my `stream_open` callback is called with stream_id 11, I try calling `ngtcp2_conn_set_stream_user_data` for stream_id 7, and I get `NGTCP2_ERR_STREAM_NOT_FOUND`, which means that stream with ID 7 has not been opened yet.

Could ngtcp2 for example buffer STREAM frames and call it in successive order, like it does for other data and calls user callbacks with correct data offsets?
Or for example ngtcp2 could automatically open streams with lower-numbered IDs of the same type, like RFC requires, and call 'stream_open' callbacks in successive order?

**Comment by tatsuhiro-t** [comment]
The statement of RFC exists in order to cap the number of concurrent streams without gaps.
ngtcp2 implementation normally creates a stream when it receives the stream data.  So in this case, when stream_open callback for stream 11 is called, stream 7 is not created yet.  That is why you get NGTCP2_ERR_STREAM_NOT_FOUND error.
As for the data in one particular stream, ngtcp2 buffers the data as necessary to deliver the data to application in-order without gaps.

**Comment by pavelxdd** [comment]
I see, thanks.

I'm implementing a MITM application, which delivers data between two endpoints (client and server).

The problem is, when I receive `stream_open` event on one end with stream_id 11, and try to call `ngtcp2_conn_open_uni_stream` for the other end, it results in opening stream with id 7, which is logical and correct.

Does it mean, that I should successively call `ngtcp2_conn_open_uni_stream` for the other end, until it returns stream_id 11 ? Because I have no other way to tell ngtcp2 which stream_id to use when opening a stream, and I want the stream_id be the same for two endpoints.

**Comment by tatsuhiro-t** [comment]
Yes.  There is no way to get a specific stream ID.
