### ISSUE TITLE
error compiling curl with ngtcp2 support

### ISSUE THREAD

**Issue by konkhra** [ngtcp2/ngtcp2#341]
After I run `make` to compile curl in Ubuntu 20.04.3 LTS I am facing this error

`Making all in lib
make[1]: Entering directory '/usr/local/src/curl/lib'
make  all-am
make[2]: Entering directory '/usr/local/src/curl/lib'
  CC       vquic/libcurl_la-ngtcp2.lo
vquic/ngtcp2.c:27:10: fatal error: ngtcp2/ngtcp2_crypto.h: No such file or directory
   27 | #include <ngtcp2/ngtcp2_crypto.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:3013: vquic/libcurl_la-ngtcp2.lo] Error 1
make[2]: Leaving directory '/usr/local/src/curl/lib'
make[1]: *** [Makefile:1359: all] Error 2
make[1]: Leaving directory '/usr/local/src/curl/lib'
make: *** [Makefile:1261: all-recursive] Error 1`

Any workarounds to get rig of this?

**Comment by tatsuhiro-t** [comment]
I think one of the supported libngtcp2_crypto libraries are not built or installed.
curl supports libngtcp2_crypto_openssl and libngtcp2_crypto_gnutls.

**Comment by bagder** [comment]
We build curl with ngtcp2 fine in CI jobs all the time, this was likely either a temporary problem back then or something we have since fixed. I think you can close.

**Comment by tatsuhiro-t** [comment]
Agreed.  Closing the issue.
