### ISSUE TITLE
ngtcp2_conn_initiate_immediate_migration returns NGTCP2_ERR_CONN_ID_BLOCKED

### ISSUE THREAD

**Issue by gangwn** [ngtcp2/ngtcp2#342]
I switch the network interface multi times, so did connection migration multi times, the last migration returns NGTCP2_ERR_CONN_ID_BLOCKED. It seems no unused connection ID is available.

In this case can I retire the old connection id and issue new connection id to continue do connection migration? If it works, how to achieve that?

**Comment by tatsuhiro-t** [comment]
If you call ngtcp2_conn_initiate_immediate_migration multiple times in short duration, you end up having no connection ID available.  The function retires the current Destination Connection ID, but you need to wait for new Connection ID from a remote endpoint.

**Comment by gangwn** [comment]
@tatsuhiro-t thanks for your explanation! How long will an old connection id be retired and a new connection id be issued?

**Comment by tatsuhiro-t** [comment]
ngtcp2_conn_initiate_immediate_migration immediately retires Connection ID.  It sends that message to the remote endpoint and waits for the replacement.  It takes at least 1RTT to get new one.

**Comment by gangwn** [comment]
got it! Thanks!
