### ISSUE TITLE
Accessing reason phrase of CONNECTION_CLOSE frames

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#345]
We're investigating an issue where the peer sporadically closes the connection with transport error code 0x01. The reason phrase contains more information on why the connection was closed but there is currently no easy way to access it for structured logging. Is it possible to add an API similar to `ngtcp2_conn_get_connection_close_error_code()` to access the reason phrase?

**Comment by tatsuhiro-t** [comment]
Thank you for bringing up this issue.
I'm thinking about extending  ngtcp2_connection_close_error_code to include reason phrase.
It might be nice to rename it since it would then include more than just error code.

**Comment by tatsuhiro-t** [comment]
3df13459af221f80d4d34a0709e1c9359ace6d7e adds reason and reasonlen fields to ngtcp2_connection_close_error struct.

**Comment by amirlivneh** [comment]
Thank you!
