### ISSUE TITLE
Documentation of ngtcp2_conn_on_loss_detection_timer() mentions non-existing ngtcp2_conn_earliest_expiry and ngtcp2_conn_handshake

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#346]
https://github.com/ngtcp2/ngtcp2/blob/cbdc336aa488950cf0e5ab5de3697a65d73db478/lib/includes/ngtcp2/ngtcp2.h#L4398-L4404

Also neither client.cc nor server.cc call `ngtcp2_conn_on_loss_detection_timer()`. Should it be part of the public API?

**Comment by tatsuhiro-t** [comment]
This documentation is outdated.  Application should call `ngtcp2_conn_handle_expiry` instead of `ngtcp2_conn_on_loss_detection_timer`.  https://nghttp2.org/ngtcp2/programmers-guide.html#timers

I will hide ngtcp2_conn_on_loss_detection_timer from public API surface.

**Comment by tatsuhiro-t** [comment]
a6ea9bb4d05dda50b015a32e2c81a98199d3c962 hid ngtcp2_conn_on_loss_detection_timer from public API surface.
