### ISSUE TITLE
Documentation | Rough Architectural overview

### ISSUE THREAD

**Issue by Aderinom** [ngtcp2/ngtcp2#349]
Hi ngtcp2 Team! 

Thank you for your hard work, looking forward to seeing the lib done.
I'm currently trying it out to use in one of our companies projects.

It would be very useful to have a rough overview over the Architecture. 
So f.e. do you start any threads your lib starts (from what i've seen i'd assume no) 
and are there any buffers one should be aware off like send/recv buffers of sockets.

Looking forward to your answer!

**Comment by tatsuhiro-t** [comment]
This library is basically QUIC stack implementation without any threads and no I/O stuff(e.g., sockets, event loop).  It does not even depend on any particular TLS library.  The integration with TLS lib is a bit tedious, so we provide helper libraries for some well-known TLS libraries.

Choosing whether to use threads or any particular event loop, or TLS library is up to you.  ngtcp2_conn object is not thread-safe, so interacting it must be serialized if multiple threads are involved.

**Comment by Aderinom** [comment]
Great! That was the confirmation I needed. 
Thank you!
