### ISSUE TITLE
client.cc doesn't resend datagrams that cannot be sent due to EAGAIN or EWOULDBLOCK

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#359]
After https://github.com/ngtcp2/ngtcp2/commit/ef6322e9b9c2de5568fd7763bed23b82d2d3ce78, a datagram that cannot be sent by `sendmsg()` due to `EAGAIN` or `EWOULDBLOCK` will be lost.

**Comment by tatsuhiro-t** [comment]
Thank you.  I'll add per-endpoint buffer to resend blocked data.

**Comment by tatsuhiro-t** [comment]
I glanced at some QUIC implementations' code and have not seen any treatment of EAGAIN and EWOULDBLOCK.  Not sure they are just toy or WIP, but interesting.

**Comment by amirlivneh** [comment]
This is one example of such treatment: https://github.com/cloudflare/quiche/blob/bbe6e2ab22126773bb63e4605ac4c8e7594f002a/apps/src/client.rs#L202

**Comment by tatsuhiro-t** [comment]
#361 adds EAGAIN/EWOULDBLOCK handling to ngtcp2 client.  I'll make similar changes against h09client.
