### ISSUE TITLE
In Library access violation on ngtcp2_conn_writev_stream_versioned

### ISSUE THREAD

**Issue by Aderinom** [ngtcp2/ngtcp2#364]
Hi ngtcp2 Team! 

I'm having some trouble getting the Library work for me.

The attached test code bit causes a Access Violation inside the Lib.
From what I've seen the Access Violation seems to happen after:

1. ngtcp2_conn_writev_stream() returned ERR_WRITE_MORE for this packet
2. other data was or waas not added to the same packet with ngtcp2_conn_writev_stream
3. then ngtcp2_conn_writev_stream is called with streamid -1 to finish the package which then fails

If I've seen correctly the following structure (starting at the conn_write_pkt function) is pointing into unassigned memory:
ngtcp2_frame_chain nfrc;
nfrc.fr.stream.data[0].base;

Stacktrace:

> test_client.exe!memcpy_repmovs() Line 40	Unknown
test_client.exe!ngtcp2_cpymem(void * dest, const void * src, unsigned __int64 n) Line 33	C
test_client.exe!ngtcp2_pkt_encode_stream_frame(unsigned char * out, unsigned __int64 outlen, ngtcp2_stream * fr) Line 1594	C
test_client.exe!ngtcp2_pkt_encode_frame(unsigned char * out, unsigned __int64 outlen, ngtcp2_frame * fr) Line 1487	C
test_client.exe!ngtcp2_ppe_encode_frame(ngtcp2_ppe * ppe, ngtcp2_frame * fr) Line 93	C
test_client.exe!conn_ppe_write_frame_hd_log(ngtcp2_conn * conn, ngtcp2_ppe * ppe, int * hd_logged, const ngtcp2_pkt_hd * hd, ngtcp2_frame * fr) Line 1602	C
test_client.exe!conn_write_pkt(ngtcp2_conn * conn, ngtcp2_pkt_info * pi, unsigned char * dest, unsigned __int64 destlen, ngtcp2_vmsg * vmsg, unsigned char type, unsigned char flags, unsigned __int64 ts) Line 3716	C
test_client.exe!ngtcp2_conn_write_vmsg(ngtcp2_conn * conn, ngtcp2_path * path, int pkt_info_version, ngtcp2_pkt_info * pi, unsigned char * dest, unsigned __int64 destlen, ngtcp2_vmsg * vmsg, unsigned __int64 ts) Line 10982	C
test_client.exe!conn_write_vmsg_wrapper(ngtcp2_conn * conn, ngtcp2_path * path, int pkt_info_version, ngtcp2_pkt_info * pi, unsigned char * dest, unsigned __int64 destlen, ngtcp2_vmsg * vmsg, unsigned __int64 ts) Line 10615	C
test_client.exe!ngtcp2_conn_writev_stream_versioned(ngtcp2_conn * conn, ngtcp2_path * path, int pkt_info_version, ngtcp2_pkt_info * pi, unsigned char * dest, unsigned __int64 destlen, __int64 * pdatalen, unsigned int flags, __int64 stream_id, const ngtcp2_vec * datav, unsigned __int64 datavcnt, unsigned __int64 ts) Line 10683	C

Following are my settings on client and server side: 

Client:

 		ngtcp2_settings settings;
		ngtcp2_settings_default(&settings);
		settings.log_printf                  = log_t::ngtcp2;
		settings.initial_ts                  = get_timestamp();
		settings.cc_algo                     = NGTCP2_CC_ALGO_CUBIC;
		settings.max_stream_window           = 1024 * 1024;
		settings.max_window                  = 1024 * 1024;
		settings.no_udp_payload_size_shaping = true;
		settings.assume_symmetric_path       = false;
		settings.ack_thresh                  = 10;
		settings.max_udp_payload_size        = 15 * 1024;
		

		ngtcp2_transport_params params;
		ngtcp2_transport_params_default(&params);
		params.initial_max_streams_bidi            = 3;
		params.initial_max_streams_uni             = 3;
		params.initial_max_stream_data_bidi_local  = 128 * 1024;
		params.initial_max_stream_data_bidi_remote = 128 * 1024;
		params.initial_max_data                    = 1024 * 1024;
		params.max_udp_payload_size                = 15 * 1024;

Server:

> 
		ngtcp2_settings settings;
		ngtcp2_settings_default(&settings);
		settings.log_printf                  = log_t::ngtcp2;
		settings.initial_ts                  = get_timestamp();
		settings.cc_algo                     = NGTCP2_CC_ALGO_CUBIC;
		settings.max_stream_window           = 1024 * 1024;
		settings.max_window                  = 1024 * 1024;
		settings.no_udp_payload_size_shaping = true;
		settings.assume_symmetric_path       = true;
		settings.ack_thresh                  = 10;
		settings.max_udp_payload_size        = 15 * 1024;

		ngtcp2_transport_params params;
		ngtcp2_transport_params_default(&params);
		params.initial_max_streams_bidi            = 3;
		params.initial_max_streams_uni             = 3;
		params.initial_max_stream_data_bidi_local  = 128 * 1024;
		params.initial_max_stream_data_bidi_remote = 128 * 1024;
		params.initial_max_data                    = 1024 * 1024;
		params.max_udp_payload_size                = 15 * 1024;
		params.original_dcid                       = client_dcid;

Outside of the attached code all i'm doing with the lib is:

```
while(true)
{
    ngtcp2_conn_read_pkt();
    sleep(100)
    ngtcp2_conn_handle_expiry(...);
    do_send();
}
```

Other info : 

> Microsoft Windows [Version 10.0.19042.868]
Using [ngtcp2 v0.1.0](https://github.com/ngtcp2/ngtcp2/releases/tag/v0.1.0)
Package version: 0.1.0
Library version: 0:0:0
Install prefix:  C:/Users/user/_MyStuff/_Projects/anydesk-udp/out/install/x64-Debug
Target system:   Windows
Compiler:
  Build type:     Debug
  C compiler:     C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe
  CFLAGS:         /MTd /Zi /Ob0 /Od /RTC1 /DWIN32 /D_WINDOWS /W3
  C++ compiler:   C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe
  CXXFLAGS:       /MTd /Zi /Ob0 /Od /RTC1 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /EHsc
  WARNCFLAGS:     
  WARNCXXFLAGS:   
Library:
  Shared:         False
  Static:         ON
Test:
  CUnit:          FALSE (LIBS='')
Libs:
  OpenSSL:        TRUE (LIBS='C:/Users/user/_MyStuff/_Projects/anydesk-udp/external/openssl/msvc-64x-debug/lib/libssl.lib;C:/Users/user/_MyStuff/_Projects/anydesk-udp/external/openssl/msvc-64x-debug/lib/libcrypto.lib')
  Libev:          FALSE (LIBS='')
  Libnghttp3:     FALSE (LIBS='')
  GnuTLS:         FALSE (LIBS='')
  BoringSSL:      FALSE (LIBS='')

[Send_Code.txt](https://github.com/ngtcp2/ngtcp2/files/8001929/Send_Code.txt)
[log.txt](https://github.com/ngtcp2/ngtcp2/files/8001930/log.txt)

**Comment by tatsuhiro-t** [comment]
It looks like the crash was happened when retransmitting stream data.  Do you keep stream data until ngtcp2_acked_stream_data_offset callback is called?

**Comment by Aderinom** [comment]
And that is the solution to the problem. I even remember reading that somewhere in the docs and thinking I'll worry about that at a later point. 🤦‍♂️ Thank you very much!
