### ISSUE TITLE
Flowcontrol blocking stream even though acks are received and repeating NEW_CONNECTION_ID & HANDSHAKE_DONE packets

### ISSUE THREAD

**Issue by Aderinom** [ngtcp2/ngtcp2#368]
Hello once again,

two problems I'm facing right now you might be able to help me with. (+ some questions)

1. I'm currently sending some data over the lib. However after the Initial congestion window was filled the stream just stops. 
This even thought the sender receives acks from the receiver and ngtcp2 logs them to console. What am I missing?
2. I'm seeing repeating packets with  NEW_CONNECTION_ID & HANDSHAKE_DONE Packets - which I assume shouldn't be there? 

Questions : 
1. the max UDP Payload size is capped at 16kb. Anything higher causes an assert in the library. Is there a reason for that?
2. Something I don't have too much experience in. But from what I understood the default UDP Payload size for Quic is adapted to best fit the typical MTU in network traffic - what reasons would be there to adapt this to a higher Payload size (other than knowing this is f.e. only used in a private network with higher MTU)
3. Does Quic have a MTU discovery function? Or is that a static value?

Attached are the Logs from Client and Server and the pcap of the connection.

[Blocking_Problem.pcap.zip](https://github.com/ngtcp2/ngtcp2/files/8014368/Blocking_Problem.zip)
[client.log](https://github.com/ngtcp2/ngtcp2/files/8014369/client.log)
[pcap_as_text.log](https://github.com/ngtcp2/ngtcp2/files/8014370/pcap_as_text.log)
[server.log](https://github.com/ngtcp2/ngtcp2/files/8014371/server.log)

The code I wrote boils down to:

```
/// Sender 

ngtcp2_conn_client_new()
wait for handshake_complete()
while(true)
{
    ngtcp2_conn_read_pkt();
    sleep(100)
    ngtcp2_conn_handle_expiry(get_ts());
    
    while(!packet_write_done & data_left_to_write)
    {
        flags f = WRITE_MORE;
        int res = ngtcp2_conn_writev_stream(streamid=1); // Stream ofc was opened beforehand
        check if  wants more data or error
        if does not want more data then packet_write_done=true
    }

    ngtcp2_conn_writev_stream(streamid=-1)
}
```

```
// Receiver
SOCKET sock = socket();
ngtcp2_conn con;
while(true)
{
    select(socket, 100ms);
    if(socket_selected)
    {
        data = recv(socket)
        if(!conn_created)
        {
            ngtcp2_pkt_decode_version_cid(data);
            //check if error
            ngtcp2_accept();
            //check if error
            con =  ngtcp2_conn_server_new()
            ngtcp2_conn_read_pkt(con, data)
        }else
        {
            ngtcp2_conn_read_pkt(con, data)
        }
    }

    ngtcp2_conn_handle_expiry(con, get_ts())

    ngtcp2_conn_writev_stream(streamid=-1)

    if(data_to_send)
    {
        sendto(socket..);
        ngtcp2_conn_update_pkt_tx_time(con, get_ts());
    }
}
```

**Comment by tatsuhiro-t** [comment]
If there are some retransmissions, it indicates that something wrong in transmission or reception unless you intentionally induce packet losses.  That might affect ACK reception which might stop releasing congestion window or flow control budget.

As for max UDP payload size, limiting to 16383 is oversight in earlier development phase.  Will extend the length to allow larger MTU.

https://datatracker.ietf.org/doc/html/rfc9000#section-14 discusses MTU discovery.  ngtcp2 does not implement MTU discovery at the moment.

**Comment by Aderinom** [comment]
Thank you for the Link! 

There shouldn't be anything wrong with transmission/reception. Both sides of the programm log that they have received packets and ACKs. I can only send the ammount of data which I defined in initial_max_stream_data_bidi_local/remote, after that the stream is just dead.

> |02/07/22|10:44:35-INFO | Recv ack for Stream 0 offset 91922 to 107248 - already send 131072 - acked ammount 107248
|02/07/22|10:44:35-INFO | Recv ack for Stream 0 offset 107248 to 122561 - already send 131072 - acked ammount 122561
|02/07/22|10:44:35-QUIC | I00002501 0x434c49454e540000 rcv cubic-ca epoch_start=13288700675719528200 k=1 origin_point=37207
|02/07/22|10:44:35-QUIC | I00002501 0x434c49454e540000 rcv pkn=26 acked, cubic-ca cwnd=34560 t=3816200 k=1 time_delta=1 delta=6144 target=31063 w_tcp=38400
|02/07/22|10:44:35-QUIC | I00002501 0x434c49454e540000 rcv target_cwnd=88780 max_delivery_rate_sec=3455334 min_rtt=3816200
|02/07/22|10:44:35-QUIC | I00002501 0x434c49454e540000 rcv loss_detection_timer=13288700677213569772 timeout=1494
|02/07/22|10:44:35-QUIC | I00002501 0x434c49454e540000 pkt read packet 32 left 0
|02/07/22|10:44:35-INFO | Writing msg 2 with 64000/0 complete added -1
|02/07/22|10:44:36-ERROR| Packaging data for stream 0 failed: ERR_STREAM_DATA_BLOCKED
|02/07/22|10:44:36-INFO | Finishing packet
|02/07/22|10:44:36-DEBUG| Handling posted read
|02/07/22|10:44:36-QUIC | I00003014 0x434c49454e540000 con recv packet len=32
|02/07/22|10:44:36-QUIC | I00003014 0x434c49454e540000 pkt rx pkn=16 dcid=0x434c49454e540000 scid=0x type=Short(0x40) len=0 k=0
|02/07/22|10:44:36-QUIC | I00003014 0x434c49454e540000 frm rx 16 Short(0x40) ACK(0x02) largest_ack=27 ack_delay=13(1711) ack_block_count=0
|02/07/22|10:44:36-QUIC | I00003014 0x434c49454e540000 frm rx 16 Short(0x40) ACK(0x02) block=[27..26] block_count=1
|02/07/22|10:44:36-QUIC | I00003014 0x434c49454e540000 rcv latest_rtt=1024 min_rtt=3 smoothed_rtt=377 rttvar=498 ack_delay=13
|02/07/22|10:44:36-INFO | Recv ack for Stream 0 offset 122561 to 131072 - already send 131072 - acked ammount 131072

So there has to be something I'm missing, but I have no clue what. 
Is there some setting or something which might cause this behaviour?

**Comment by tatsuhiro-t** [comment]
ERR_STREAM_DATA_BLOCKED indicates that flow control window is depleted.  The flow control is a different mechanism from congestion window, and the receiver needs to send a signal to sender that the amount of data that sender can send.
Please make sure that the following functions are called on receiver side with the amount of data received:

- https://nghttp2.org/ngtcp2/ngtcp2_conn_extend_max_stream_offset.html
- https://nghttp2.org/ngtcp2/ngtcp2_conn_extend_max_offset.html

**Comment by Aderinom** [comment]
Yep, That's what was missing in my code. Once again Thank you very much!
