### ISSUE TITLE
docs: ngtcp2_conn_write_connection_close

### ISSUE THREAD

**Issue by bagder** [ngtcp2/ngtcp2#380]
I assume the function returns the size in bytes of the packet it writes into the buffer, but I'm missing text explaining the return value in [the docs](https://nghttp2.org/ngtcp2/ngtcp2_conn_write_connection_close.html).

Also, the docs currently lists 9 arguments in the prototype while the current header file actually only lists 7. The reason plus reason_len seem to have been dropped.

**Comment by bagder** [comment]
> As for reason and reasonlen, the ngtcp2.h in main branch has them:

Oh, sorry for that noise. For some reason my local build failed `make install` so it had an old version of the file lingering around which I looked at! After I reran configure and a build it installed fine and I see the correct version.

**Comment by tatsuhiro-t** [comment]
12db75d38a0d1e82b8a88869e0575e2ddea1ca53 adds text about the return values.
