### ISSUE TITLE
any benchmark with tcp

### ISSUE THREAD

**Issue by notedit** [ngtcp2/ngtcp2#40]
hi,  i did not see any chat group about this project,  i just ask here.  

1, is there any benchmark with tcp?
2, is project is stable now?  

thanks for your hard work.

**Comment by tatsuhiro-t** [comment]
1.  No.  I think IETF QUIC is under heavy development, and is not the condition to compare against TCP in performance wise.
2.  Not entirely stable.   API will change time to time.

**Comment by notedit** [comment]
thanks  i will keep an eye on this project.
