### ISSUE TITLE
Using instructions in the README, when I configure ngtcp2, it says openssl does not have QUIC

### ISSUE THREAD

**Issue by elyograg** [ngtcp2/ngtcp2#411]
I'm using the list of instructions in the "Build from git" section of the main readme.  On the last step, configuring ngtcp2, it has this output:

```
checking for SSL_is_quic... no
configure: openssl does not have QUIC interface, disabling it
```

What are those instructions missing?  I'm trying to build curl with http3 support, and that requires ngtcp2 and nghttp3.

**Comment by tatsuhiro-t** [comment]
It is most likely caused by a vanilla openssl installation path spilt into configure flags (e.g., PKG_CONFIG_PATH) that prevents configure script to detect quictls.  Try clean fresh environment like docker.
