### ISSUE TITLE
how to build and install ngtcp2

### ISSUE THREAD

**Issue by ShawnBian** [ngtcp2/ngtcp2#427]
Hello, 
I am just following this link https://github.com/ngtcp2/ngtcp2/blob/main/README.rst to install ngtcp2 ,I am pretty confusing about what this links say:

==============================================================
$ git clone --depth 1 -b OpenSSL_1_1_1n+quic https://github.com/quictls/openssl
$ cd openssl
$ # For Linux
$ ./config enable-tls1_3 --prefix=$PWD/build
$ make -j$(nproc)
$ make install_sw
$ cd ..
$ git clone https://github.com/ngtcp2/nghttp3
$ cd nghttp3
$ autoreconf -i
$ ./configure --prefix=$PWD/build --enable-lib-only
$ make -j$(nproc) check
$ make install
$ cd ..
$ git clone https://github.com/ngtcp2/ngtcp2
$ cd ngtcp2
$ autoreconf -i
$ # For Mac users who have installed libev with MacPorts, append
$ # ',-L/opt/local/lib' to LDFLAGS, and also pass
$ # CPPFLAGS="-I/opt/local/include" to ./configure.
$ # For OpenSSL >= v3.0.0, replace "openssl/build/lib" with
$ # "openssl/build/lib64".
$ ./configure PKG_CONFIG_PATH=$PWD/../openssl/build/lib/pkgconfig:$PWD/../nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,$PWD/../openssl/build/lib"
$ make -j$(nproc) check

==============================================================

question1: what is the meaning of "$PWD/../openssl/build/lib/pkgconfig", if the openssl is installed under the directory of "/usr/locall/openssl" ,what should be filled in  here exactly ?

question2 : what is the meaning of "$PWD" ,why using "/../" ?  "/../" should represent the parent fold .I can not really understand here 

thank you for the answer .

**Comment by tatsuhiro-t** [comment]
> question1

if you install openssl 1.1.1n+quic under /usr/local/openssl, `PKG_CONFIG_PATH=/usr/local/openssl/lib/pkgconfig:$PWD/../nghttp3/build/lib/pkgconfig`

> question2

$PWD is the current working directory.  As long as the result is the same, it is fine to use whatever.

**Comment by ShawnBian** [comment]
thank you for the reply . but I am still confused about it .
let us just be very particular, for this part:
$ git clone https://github.com/ngtcp2/ngtcp2
$ cd ngtcp2
$ autoreconf -i
$ # For Mac users who have installed libev with MacPorts, append
$ # ',-L/opt/local/lib' to LDFLAGS, and also pass
$ # CPPFLAGS="-I/opt/local/include" to ./configure.
$ # For OpenSSL >= v3.0.0, replace "openssl/build/lib" with
$ # "openssl/build/lib64".
$ ./configure PKG_CONFIG_PATH=$PWD/../openssl/build/lib/pkgconfig:$PWD/../nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,$PWD/../openssl/build/lib"
$ make -j$(nproc) check

if openssl is installed under the /usr/local/openssl , nghttp3 is installed under the /usr/local/nghttp3.
I intend to install ngtcp2 under the /usr/local/ngtcp2

can you help to verify the configure part like below is correct? 

$ ./configure PKG_CONFIG_PATH=/usr/local/openssl/build/lib/pkgconfig:/usr/local/nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/build/lib"

really appreciated the help.

**Comment by tatsuhiro-t** [comment]
./configure PKG_CONFIG_PATH=/usr/local/openssl/lib/pkgconfig:/usr/local/nghttp3/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/lib" --prefix=/usr/local/ngtcp2

**Comment by ShawnBian** [comment]
thank you very much .
