### ISSUE TITLE
ngtcp2_conn_set_initial_key() in the doc

### ISSUE THREAD

**Issue by YunanZhu** [ngtcp2/ngtcp2#429]
In the doc of these two function pointers:
- [ngtcp2_client_initial](https://nghttp2.org/ngtcp2/types.html?highlight=set_initial_key#c.ngtcp2_client_initial)
- [ngtcp2_recv_client_initial](https://nghttp2.org/ngtcp2/types.html?highlight=set_initial_key#c.ngtcp2_recv_client_initial)

Mention `ngtcp2_conn_set_initial_key()` but there is no such function in the lib. Has it been renamed as [`ngtcp2_conn_install_initial_key`](https://nghttp2.org/ngtcp2/ngtcp2_conn_install_initial_key.html#ngtcp2-conn-install-initial-key)?

And Incomplete sentence: 
> client application must create initial packet protection keys and IVs, and provide them to ngtcp2 library using ngtcp2_conn_set_initial_key() and

**Comment by tatsuhiro-t** [comment]
It looks like the documentation is outdated.  Will fix it.

**Comment by tatsuhiro-t** [comment]
Fix committed via 12a30c596bed1c6890fcf401b0904848158276af
