### ISSUE TITLE
Add a more explanatory examples

### ISSUE THREAD

**Issue by evilmonkey19** [ngtcp2/ngtcp2#431]
Hi! 

First of all, congrats for your hard work! I had some trouble trying to use/understand the _examples/server_ and _examples/client_. I suggest to add the following code (extracted from bbc/nghq) which will help a lot creating the certs easily. 

[NGHQ file](https://github.com/bbc/nghq/blob/master/examples/create_cert.sh)

I propose the following example for _examples/server_ so anyone can understand how to do it (suppose server IP 192.168.0.1 and add a file stored on examples/server-files like [quijote.txt](https://gist.github.com/jsdario/6d6c69398cb0c73111e49f1218960f79)
`examples/server 192.168.0.1 12345 sender.key sender.pem --htdocs=examples/server-files -q`

Example for _examples/client_:
`examples/client 192.168.0.1 12345 https://192.168.0.1:12345/quijote.txt -q download="examples/client-files" --exit-on-all-streams-close`

**Comment by aquarter147** [comment]
Hello! I'm trying to send a file from a server to client but I can't find the received file.

**Comment by evilmonkey19** [comment]
You should see the client-side files in the download folder you put in the _download_ option. Can you tell me the commands you use on the client and server sides?

**Comment by aquarter147** [comment]
Thank you a lot! Finally, I found it.

**Comment by aquarter147** [comment]
Hi! Now I have a problem sending a folder to the client. Could you please tell me the way to do it?

**Comment by evilmonkey19** [comment]
Heeey!! I had the same problem. As you may already realize, the script is only a demo to show what you can do. I strongly recommend building a new script that suits your needs, in this case sending a folder, or in the worst but the easiest case, using this script multiple times, sending only one file at a time. I hope I helped you :)

**Comment by aquarter147** [comment]
Thank you, I wish I could do it the right way <3

**Comment by aquarter147** [comment]
Hi! I've found a way to send multiple files in 1 folder but i am having problem that once the file has been transferred all the contents are lost. 
`namespace {
  int TA1_parse_requests(char **argv) {//set uri 
      //there is a need to add the filename to uri here
    auto uri_tmp= argv[0];

    for (int i=1;i<4;++i){ //we have to define the number of loop for each request
      Request req;
      char temp[20];
      sprintf(temp,"text%d.txt",i);
      int bufferSize = strlen(temp)+strlen(uri_tmp)+1;
      char *uri = new char[bufferSize];
      strcpy(uri,uri_tmp);
      strcat(uri,temp);
      std::cout<<typeid(uri).name()<< std::endl;
      std::cout<<"this is the uri: "<<uri<<std::endl;
      if (parse_uri(req, uri) != 0) {
        std::cerr << "Could not parse URI: " << uri << std::endl;
        return -1;
      }
      config.requests.emplace_back(std::move(req));
      delete[] uri;
    }
    return 0;
  }
} // namespace
`
By replacing parse_requests (original) = TA1_parse_requests(), I wrote the command for client like this:
`sudo ./client 192.168.11.118 12345 https://192.168.11.118:12345/ -q --download=/home/fil/ngtcp2/examples/client-file --exit-on-all-streams-close`
