### ISSUE TITLE
Cache in server.cc

### ISSUE THREAD

**Issue by evilmonkey19** [ngtcp2/ngtcp2#434]
Hello everyone!

I am currently trying to use examples/server to send a live-streaming via QUIC. The problem I am facing is that there is some sort of cache (is commit [cache fd](https://github.com/ngtcp2/ngtcp2/commit/8cd22a8d1406c1c3917e3d386d9285c861f249a7) related?). I want the client to get a file with the indication of the new file (like .m3u8) that server the in a background process is changing all the time so it can point to the good url.

I have tried to compile cache fd commit but it does not compile because of nghttp3 commits I guess.

Thank you very much.

**Comment by evilmonkey19** [comment]
I already solved the problem. There were some changes in the nghttp3 library. If you want to delete the server cache you must go to commit [cleanup](https://github.com/ngtcp2/nghttp3/commit/bd73e2710377d5aea12f6d1bb0bedc955c45f610) in nghttp3 `git commit bd73e27103` in nghttp3. 

It would a good idea to add the option to disable the cache on server.cc. I can try to do it in mid-May if you like the idea. Please respond this comment. I leave it open to your response.

**Comment by tatsuhiro-t** [comment]
It is just an example server, it never be meant to be designed for a particular purpose.  If you want it to behave what you like, then you can modify it locally.

**Comment by evilmonkey19** [comment]
Thank you for your comment! I think if someone else have to deal with a problem like mine (live-streaming server), maybe they will find this thread useful.
