### ISSUE TITLE
calling recvmsg, receive a zero byte

### ISSUE THREAD

**Issue by doraeqing** [ngtcp2/ngtcp2#435]
Hi
I'm not sure in which scenario the recvmsg function returns 0 and then I get the NGTCP2_ERR_INVALID_ARGUMENT error, causing the connection to be closed.
`
int ngtcp2_conn_read_pkt(xxxx) {
  if (pktlen == 0) {
    return NGTCP2_ERR_INVALID_ARGUMENT;
  }
`

**Comment by tatsuhiro-t** [comment]
UDP datagram payload can be empty.   Empty QUIC packet is always invalid.  Application can check the size and discard it if it is zero.

**Comment by doraeqing** [comment]
> 
ok thanks for your reply!
That means if the ngtcp2_conn_read_pkt function returns -201 error, Aapplication can not close the connection?

**Comment by tatsuhiro-t** [comment]
No.  Just do not call ngtcp2_conn_read_pkt if payload is empty.

**Comment by doraeqing** [comment]
> Just do not call ngtcp2_conn_read_pkt if payload is empty. Then application can close connection on NGTCP2_ERR_INVALID_ARGUMENT.

ok, thanks a lot
