### ISSUE TITLE
API to set custom QUIC version

### ISSUE THREAD

**Issue by JunqiWang** [ngtcp2/ngtcp2#448]
In some scenarios, we would like to set a custom QUIC version (but reusing exactly same implementation of QUIC_V1) to achieve granular control between different clients, e.g. mobile vs browser.

Currently, if we specify a custom QUIC version in ngtcp2, it seems to be working automatically. It uses the QUIC draft initial salt by default though: https://github.com/ngtcp2/ngtcp2/blob/main/crypto/shared.c#L99.

On server side, this doesn't work because it expects the version to be in the supported list: https://github.com/ngtcp2/ngtcp2/blob/main/lib/ngtcp2_pkt.c#L2474-L2483

Can we have an API to support this need that allows client and server to specify custom QUIC version (and maybe salt)?

**Comment by tatsuhiro-t** [comment]
I have no plan to allow application to set custom version and salt.  Version is important part of version negotiation and allowing more flexibility could open a can of worms.
