### ISSUE TITLE
Pointer type in ngtcp2_transport_params: ngtcp2_version_info.other_versions

### ISSUE THREAD

**Issue by JunqiWang** [ngtcp2/ngtcp2#449]
Hi, the other_versions field in ngtcp2_transport_params is a pointer type, which makes it difficult to serialize/deserialize/copy when caching along with TLS session ticket. Would it be possible to make ngtcp2_transport_params a trivial POD type by changing other_versions to an array with some MAX_OTHER_VERSIONS size?

**Comment by tatsuhiro-t** [comment]
ngtcp2_encode_transport_params correctly serializes ngtcp2_transport_params into byte string and you can store them in anyway.
If it is not enough, I can add a function that makes a copy of ngtcp2_transport_params, which dynamically allocate memory as necessary for example.

**Comment by tatsuhiro-t** [comment]
If we have fixed length other_versions in struct, it is in most cases too long or too short and in former case, it wastes memory.  I'd like to avoid that.

https://github.com/ngtcp2/ngtcp2/pull/455 adds ngtcp2_decode_transport_params_new which decodes QUIC transport parameters from byte array, and stores the result into the dynamically allocated object.  All direct and indirect fields are dynamically allocated if needed.

**Comment by tatsuhiro-t** [comment]
It might be better to add a function to copy ngtcp2_transport_params instead.  Actually ngtcp2_decode_transport_params_new uses it internally.
