### ISSUE TITLE
Build issues 

### ISSUE THREAD

**Issue by vinothchandar** [ngtcp2/ngtcp2#46]
(hey.. this is so cool to see.  We are also actively looking into c based quic client ) 

Getting some errors like 

```
server.cc:2222:25: error: ‘ssl_ctx’ was not declared in this scope
   Server s4(EV_DEFAULT, ssl_ctx);
                         ^
server.cc:2223:27: error: ‘addr’ was not declared in this scope
   if (!util::numeric_host(addr, AF_INET6)) {
                           ^
server.cc:2225:7: error: ‘ready’ was not declared in this scope
       ready = true;
       ^
server.cc:2230:27: error: ‘addr’ was not declared in this scope
   if (!util::numeric_host(addr, AF_INET)) {
                           ^
server.cc:2232:7: error: ‘ready’ was not declared in this scope
       ready = true;
       ^
server.cc:2236:8: error: ‘ready’ was not declared in this scope
   if (!ready) {
        ^
make[1]: *** [server.o] Error 1
make: *** [check-recursive] Error 1
```

after I did the following to prep my machine.. 

```
sudo apt-get install automake autoconf libtool autotools-dev
sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
sudo apt-get install libev-dev
sudo apt-get install cunit=2.1
```

any ideas?  Love to try this out and see..

**Comment by tatsuhiro-t** [comment]
This is strange, but it probably means that C++ compiler is not capable of C++14 feature set.
Which version of compiler are you using?  clang-4.0 or gcc-6 or later should work.

**Comment by vinothchandar** [comment]
With gcc6, those go away and now realized have trouble building openssl to being with.. Will keep at it.. closing this issue for now 

meantime, would you be able to share how large the client library currently is?

**Comment by tatsuhiro-t** [comment]
Are you asking source line of code, or size of binary?  At this stage of QUIC development, I think they are not so important metrics.  In the end, the size of binary might be important for particular area, like embedded devices which has low memory foot print.

**Comment by vinothchandar** [comment]
I was talking about size of binary, which kind of becomes important to use this in an app. For eg. with cronet/quic library, its 3MB+ per architecture, which is a lot.

**Comment by tatsuhiro-t** [comment]
The binary size probably depends on the platform, and for my pc, it is 71KiB at the moment.  But it probably grows more if we add more APIs, or features.
