### ISSUE TITLE
Error code that is not used

### ISSUE THREAD

**Issue by JunqiWang** [ngtcp2/ngtcp2#464]
In https://github.com/ngtcp2/ngtcp2/blob/de964e2a8c5766d6174218f567d4524c695edca6/crypto/openssl/openssl.c#L616-L618, we return NGTCP2_CRYPTO_OPENSSL_ERR_TLS_WANT_CLIENT_HELLO_CB or NGTCP2_CRYPTO_OPENSSL_ERR_TLS_WANT_X509_LOOKUP. However, by searching the codebase, it looks like these 2 error codes are not consumed anywhere. Can we remove them then?

**Comment by tatsuhiro-t** [comment]
These special error code is expected to be handled by an application which defers certificate lookup.
