### ISSUE TITLE
How to pass libev header directory?

### ISSUE THREAD

**Issue by paulmenzel** [ngtcp2/ngtcp2#469]
The libev header `ev.h` is installed in `/usr/include/ev` on my system.

    $ ./configure --with-gnutls --with-libev

does not `ev.h`.

    checking for SSL_is_quic... no
    configure: openssl does not have QUIC interface, disabling it
    checking for gnutls >= 3.7.2... yes
    checking for libnghttp3 >= 0.2.0... yes
    checking for ev_time in -lev... yes
    checking for ev.h... no

[Adding the include directory to `CPPFLAGS`](https://lists.gnu.org/archive/html/automake/2001-05/msg00014.html) works around the issue:

    CPPFLAGS="-I/usr/include/ev/" ./configure --with-gnutls --with-libev

**Comment by tatsuhiro-t** [comment]
By default, configure script only looks up the standard location of header files and libraries, like /usr/include and /usr/lib.
For libev, LIBEV_CFLAGS and LIBEV_LIBS variables are available.
