### ISSUE TITLE
Mandatoriness of storing transport parameter for 0-RTT

### ISSUE THREAD

**Issue by JunqiWang** [ngtcp2/ngtcp2#470]
[This section in RFC9000](https://datatracker.ietf.org/doc/html/rfc9000#section-7.4.1) list for each transport parameter whether it should be remembered for 0-RTT resumption.

Currently in ngtcp2, whether to save a transport parameter is controlled in [example client](https://fburl.com/dm3hyjkm). Would it be possible to implement this part of RFC in the main library? For example, maybe the main library can provide a pair of functions `serialize/deserialize_0rtt_transport_params`.

**Comment by tatsuhiro-t** [comment]
ngtcp2_conn_set_early_remote_transport_params only copies the set of parameters that client should/can remember from the previous session.  So other than the extra space, the current API can be safely used for this purpose.
