### ISSUE TITLE
Prioritization support

### ISSUE THREAD

**Issue by NooshinEghbal** [ngtcp2/ngtcp2#475]
Does ngtcp2 have any prioritization support? Either the tree-based ones or the recent [Extensible Prioritization Scheme](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-priority-03.txt)?

**Comment by tatsuhiro-t** [comment]
Prioritization is implemented in HTTP layer.  For instance, https://github.com/ngtcp2/nghttp3 implements RFC 9218 priorities.

**Comment by NooshinEghbal** [comment]
Great. Thanks.

**Comment by NooshinEghbal** [comment]
When we are running the client in the example folder, how can we set priority scores for each UDI?
