### ISSUE TITLE
Required files for server

### ISSUE THREAD

**Issue by NooshinEghbal** [ngtcp2/ngtcp2#476]
Hello,

I wanted to run "server" in the example section and the two last arguments are the path to private key file and the path to certificate file.
How can I generate these two files?

Thanks.

**Comment by NooshinEghbal** [comment]
I could find the gen_certificate.sh file in the ci folder.
Sorry, I could not delete the issue.

**Comment by Karthikdasari0423** [comment]
To create key and certificate using openssl on ubuntu

cd /root/openssl/
openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out example.crt -keyout example.key

Start ngtcp server with 8443 or 443

cd /root/ngtcp2/examples/
./server --timeout=100h --show-secret 172.16.2.1 4434 /root/openssl/example.key /root/openssl/example.crt

Hope this helps
