### ISSUE TITLE
Receiving index.html text but not the other resource files

### ISSUE THREAD

**Issue by NooshinEghbal** [ngtcp2/ngtcp2#477]
Hello,

I used the following commands to run the HTTP server and client:

./server --htdocs=/home/nooshin/Desktop/webroot-test 127.0.0.1 4444 ../ci/cert/server.key ../ci/cert/server.crt
./client 127.0.0.1 4444 https://127.0.0.1:4444

There was an index.html in the root directory (i.e. webroot-test). So, the client received the index.html text but not the image file required for loading the page:
[
![Screenshot from 2022-06-27 23-55-14](https://user-images.githubusercontent.com/7840517/176050692-158e7d19-d550-4690-a055-17869664b082.png)

**Comment by tatsuhiro-t** [comment]
examples/client only accesses the provided URIs.  It does not parse html and get assets.

**Comment by aquarter147** [comment]
hi! How can I read the received file when the client sends it to the server? where is it?
