### ISSUE TITLE
Cannot reach QUIC server from external address

### ISSUE THREAD

**Issue by Henrocker** [ngtcp2/ngtcp2#48]
When running quic Server on my debian 9 x86_64 system with the following command:

`screen ./server example.com 4433 /etc/nginx/example.key /etc/nginx/example.crt --htdocs=/etc/nginx/html`

And I start the client on the same machine with:

`./client example.com 4433 -i`

then I can perform GET requests in the console successfully, because I see the Hexa encoded html Output.

However when starting the client on another machine with the same setup, it says:

```
t=2.803593 TX Initial(0x7f) CID=0xed376d72ef55ad10 PKN=1187533146 V=0xff000008
           STREAM(0x12) FIN=0 LEN=1 OFF=0
           stream_id=0x0 fin=0 offset=0 data_length=314
           ; BIDI
           PADDING(0x00)
           length=881
recvfrom: Connection refused
ngtcp2_conn_write_pkt: ERR_PKT_TIMEOUT
ngtcp2_conn_write_connection_close: ERR_INVALID_STATE
ngtcp2_conn_write_connection_close: ERR_INVALID_STATE
ngtcp2_conn_write_connection_close: ERR_INVALID_STATE
```

What I also tried was to set iptable rules: 

```
iptables -A INPUT -p udp --dport 4433 -j ACCEPT
iptables -A OUTPUT -p udp --dport 4433 -j ACCEPT
```

And removing my Hostname/Domain from the hosts file, where it was definded as localhost.

But both did not fix the issue. So my question is: How do I get my quic server to be reachable from outside like the nghttp2.org:4433 page?

**Comment by tatsuhiro-t** [comment]
First check that the server listens on the address that the other machine can connect to.
For example:
```
$ ss -uanl|grep 4433
UNCONN     0      0            *:4433                     *:*                  
UNCONN     0      0           :::4433                    :::*                  
```

**Comment by Henrocker** [comment]
When checking with the command, I get this output:

```
# ss -uanl|grep 4433
UNCONN      0      0      127.0.0.1:4433               0.0.0.0:*                
UNCONN      0      0        [::1]:4433                  [::]:*
```

Maybe the error is, that it binds to localhost?

**Comment by tatsuhiro-t** [comment]
I think so.

**Comment by Henrocker** [comment]
Alright, fixed it by removing my domain name from the hosts file of my system where it was declared as localhost apparently. Now my external IP Addresses bind to the ports. 

Also added my site to the public servers section at ngtcp2 of the implementations page at quicwg.

Thank you for your help.
