### ISSUE TITLE
Using Unreliable Datagram Extension

### ISSUE THREAD

**Issue by nEghbal** [ngtcp2/ngtcp2#482]
Hi,

How I can use the unreliable datagram extension for some of the URIs?
I learned that we need to set "max_datagram_frame_size" but I could not find it the option list of client/server.

**Comment by tatsuhiro-t** [comment]
examples/client and server do not use Datagram at the time of this writing.

**Comment by tatsuhiro-t** [comment]
See https://github.com/ngtcp2/nghttp3/issues/46
