### ISSUE TITLE
Setting QUIC packet size

### ISSUE THREAD

**Issue by nEghbal** [ngtcp2/ngtcp2#496]
Hi,

I noticed that the QUIC packet size is about 1400 bytes running examples/client and server.
How can I set it to 200 bytes for example?
I tried using --max-udp-payload-size option on client/server but it did not work for 200. 
It worked for 1200 but when I tried 1100 on both server and client, the server did not receive any packets.
Is there any minimum for --max-udp-payload-size option?

**Comment by tatsuhiro-t** [comment]
Some packets need minimum 1200 bytes.  There is no way to know which packets the ngtcp2_conn writes next, therefore, better to use at least 1200 minimum.
