### ISSUE TITLE
'app_error_code' is not always set on stream when handling stream error

### ISSUE THREAD

**Issue by zg-8** [ngtcp2/ngtcp2#502]
## Question

Following the behavior change introduced in [nghttp3 commit 615b47](https://github.com/ngtcp2/nghttp3/commit/615b470700e4938ce2f1eb4254f6e33cb283cecd) and [ngtcp2 commit 1cc219](https://github.com/ngtcp2/ngtcp2/commit/1cc219b93c747c577de7569808ead234b013b357), regarding the definition of [`conn_shutdown_stream_write` function in `ngtcp2_conn.c`](https://github.com/ngtcp2/ngtcp2/blob/5c95556ddcfcac105a572c48baa6125203f5152b/lib/ngtcp2_conn.c#L12273), would it be reasonable to consider always setting the `app_error_code` field of `ngtcp2_strm` with the `app_error_code` value passed in through function parameters?

```diff
static int conn_shutdown_stream_write(ngtcp2_conn *conn, ngtcp2_strm *strm,
                                      uint64_t app_error_code) {
+ ngtcp2_strm_set_app_error_code(strm, app_error_code);

  if ((strm->flags & NGTCP2_STRM_FLAG_SENT_RST) ||
      ngtcp2_strm_is_all_tx_data_fin_acked(strm)) {
    return 0;
  }

  /* Set this flag so that we don't accidentally send DATA to this
     stream. */
  strm->flags |= NGTCP2_STRM_FLAG_SHUT_WR | NGTCP2_STRM_FLAG_SENT_RST;
- ngtcp2_strm_set_app_error_code(strm, app_error_code);

  ngtcp2_strm_streamfrq_clear(strm);

  return conn_reset_stream(conn, strm, app_error_code);
}
```

That way, we would have more consistent error handling by ngtcp2, and the `app_error_code` field would be able to indicate error like `NGHTTP3_H3_MESSAGE_ERROR` when [`NGHTTP3_ERR_MALFORMED_HTTP_HEADER` is detected at higher level of the call stack](https://github.com/ngtcp2/nghttp3/blob/e1e5093013d7e3ef7e55a57994154e76b2981173/lib/nghttp3_conn.c#L1342).

We understand that the intention of recent commits is to treat `NGHTTP3_ERR_MALFORMED_HTTP_HEADER` as an error on stream instead of an error on connection as per PR comment in https://github.com/ngtcp2/nghttp3/pull/72. 

However, if we look at the code snippet above, we noticed that a stream error is sometimes reflected in both `flags` and `app_error_code` of stream (e.g. [when we need to schedule `RESET_STREAM` frame](https://github.com/ngtcp2/ngtcp2/blob/5c95556ddcfcac105a572c48baa6125203f5152b/lib/ngtcp2_conn.c#L12283)), whereas it is [only reflected in the `flags` when handling `NGHTTP3_ERR_MALFORMED_HTTP_HEADER`](https://github.com/ngtcp2/nghttp3/blob/e1e5093013d7e3ef7e55a57994154e76b2981173/lib/nghttp3_conn.c#L1432). In other words, `conn_shutdown_stream_write` function will swallow the `app_error_code` [in the case where we don't send `RESET_STREAM` frame](https://github.com/ngtcp2/ngtcp2/blob/5c95556ddcfcac105a572c48baa6125203f5152b/lib/ngtcp2_conn.c#L12277).

## Issues we are facing

We have previously followed [the example in `client.cc`](https://github.com/ngtcp2/ngtcp2/pull/488/commits/a410c31f18dc9bf54fb7cd2dee577cbf983b44ff) to implement the `reset_stream` callback (of `nghttp3_callbacks`). Given that `conn_shutdown_stream_write` function will now swallow the `app_error_code` [in the case where we don't send `RESET_STREAM` frame](https://github.com/ngtcp2/ngtcp2/blob/5c95556ddcfcac105a572c48baa6125203f5152b/lib/ngtcp2_conn.c#L12277), we currently can no longer only depend on the [`app_error_code`](https://github.com/ngtcp2/nghttp3/blob/e1e5093013d7e3ef7e55a57994154e76b2981173/lib/nghttp3_conn.c#L1035) to populate the error message in our `stream_close` callback definition when [`NGHTTP3_ERR_MALFORMED_HTTP_HEADER`/`NGHTTP3_H3_MESSAGE_ERROR` happens](https://github.com/ngtcp2/nghttp3/blob/e1e5093013d7e3ef7e55a57994154e76b2981173/lib/nghttp3_conn.c#L1442). The [below code snippet from `client.cc`](https://github.com/ngtcp2/ngtcp2/blob/dfe88dcd675ef4722e17f5d11a8d4f960b4cbd50/examples/client.cc#L1985) would also explain the specific issue that we are referring to.

```cpp
int Client::http_stream_close(int64_t stream_id, uint64_t app_error_code) {

  ...

  if (auto it = streams_.find(stream_id); it != std::end(streams_)) {
    if (!config.quiet) {
      std::cerr << "HTTP stream " << stream_id << " closed with error code "
                << app_error_code << std::endl;
    }
    streams_.erase(it);
  }

  return 0;
}
```

We could technically check stream `flags` through [`stream_user_data` passed to the `reset_stream` nghttp3 callback](https://github.com/ngtcp2/nghttp3/blob/e1e5093013d7e3ef7e55a57994154e76b2981173/lib/nghttp3_conn.c#L1035), but that would introduce additional complexity and seems to be a bit inconsistent error handling behavior by the `conn_shutdown_stream_write` function in ngtcp2.

Would you feel the code change suggested at the top of this message makes sense, or would you have any suggestions on the error handling logic that we talked about please? Thanks!

CC: @JunqiWang @amirlivneh

**Comment by tatsuhiro-t** [comment]
I think it is a reasonable.  I assume you are referring to the specific condition that  NGTCP2_STRM_FLAG_SENT_RST is not set but ngtcp2_strm_is_all_tx_data_fin_acked(strm) is true.  Not setting error code to stream in this situation is unintentional.
Will fix this.

**Comment by zg-8** [comment]
> I assume you are referring to the specific condition that NGTCP2_STRM_FLAG_SENT_RST is not set but ngtcp2_strm_is_all_tx_data_fin_acked(strm) is true.

Yes, that's exactly what we were thinking about. Thanks for looking into this, @tatsuhiro-t.
