### ISSUE TITLE
Determining if a stream was affected by retransmissions

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#508]
We're investigating an issue where HTTP/3 requests take longer to complete in certain situations. We would like to check if there is a correlation between these slow requests and retransmissions.

On the surface, logging the difference of `ngtcp2_conn_stat.pto_count` between the stream start and end could be a good proxy, but this field is reset in certain conditions.

Can the API be extended to allow determining if a stream was affected by retransmissions? Adding a `total_pto_count`to `ngtcp2_conn_stat` may also work, but probably not ideal.

**Comment by tatsuhiro-t** [comment]
If I understand this correctly, you are observing this on the sender side.
If it is correct, I think we can increment a counter when the library declares loss of packet which includes a STREAM frame and provide an API to get the counter value.

**Comment by amirlivneh** [comment]
We're observing this on the client. Specifically the latency is mostly in the interval between sending the request and receiving the response headers. We're not sure if the culprit is in sending the request or receiving the response headers, but having better instrumentation of the sender side is a good start.

**Comment by tatsuhiro-t** [comment]
The retransmission/PTO is sender only signal that is only sender knows that they happened.  For receiver side, it can check whether packet reordering happened which might be a signal of packet loss and causes PTO and finally retransmission.  Reordering does not always suggest loss, it might happen frequently in some environment.

**Comment by amirlivneh** [comment]
Yes, we would like to know on the sender side if any packets were deemed lost and had to be retransmitted.

**Comment by tatsuhiro-t** [comment]
#516 adds ngtcp2_conn_get_stream_loss_count function which returns the number of lost packets that contain STREAM frame for a given stream.
