### ISSUE TITLE
Creating own apache server at the server side.

### ISSUE THREAD

**Issue by ytxing** [ngtcp2/ngtcp2#52]
Hi. I am a college student trying to make the client and server in the examples directory my own ones.
I use apache2 to build a server in a ubuntu virtual box. The server contains only 1 .png image. Then I try to connect the client in the same virtual box to my own server using the giving _examples/client_ and _examples/server_. I succeed in visiting my server in browser but not with the _client_. The log information shows that the connection between _client_ and _server_ is ok and received the "hello world!" successfully. But it is always 404 when I enter "GET /" in _client_ with the -i parameter. 
Can anyone tell me how to build my server correctly? I am trying to read the code of the whole thing and I am so confused. I will be so appreciated for your help.
By the way, when I use the command _client nghttp2.org 4433 -i _ and then enter "GET /" the source can be got successfully.

**Comment by tatsuhiro-t** [comment]
If I understand it correctly, you are trying to run examples/server, right?  404 error indicates that server could not find the request resource, so check that the document root is specified by `-d` option of examples/server.

**Comment by ytxing** [comment]
Yes that's the problem. Thank you so much for your help!
