### ISSUE TITLE
Consider renaming ngtcp2_settings.max_udp_payload_size

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#527]
I find it confusing that `ngtcp2_settings.max_udp_payload_size` and `ngtcp2_transport_params.max_udp_payload_size` have identical names but opposite meanings. I suggest renaming `ngtcp2_settings.max_udp_payload_size` to make the difference clear.

**Comment by tatsuhiro-t** [comment]
I will rename it to something like ngtcp2_settings.max_tx_udp_payload_size to convey that it is the limit of outgoing UDP datagram.

**Comment by tatsuhiro-t** [comment]
Will do this next time we break the backward compatibility (soname bump).

**Comment by tatsuhiro-t** [comment]
Fixed by #598
