### ISSUE TITLE
ngtcp2_conn_get_stream_loss_count() cannot be used in stream_close() callback

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#528]
We're trying to use `ngtcp2_conn_get_stream_loss_count()` to gather network performance metrics. The most natural place to do it is in the `stream_close()` callback. But since [`conn_call_stream_close()` is called after `ngtcp2_map_remove()`](https://github.com/ngtcp2/ngtcp2/blob/main/lib/ngtcp2_conn.c#L12235-L12244), the stream ID passed to `ngtcp2_conn_get_stream_loss_count()` is never found and the function returns 0. Is it possible to swap the calls to `conn_call_stream_close()` and `ngtcp2_map_remove()` or solve it in a different way?

**Comment by tatsuhiro-t** [comment]
I will make a change so that ngtcp2_conn_get_stream_loss_count is available inside stream_close callback.
