### ISSUE TITLE
The first bytes of the first frame in a stream

### ISSUE THREAD

**Issue by nEghbal** [ngtcp2/ngtcp2#530]
I realized that the first bytes of the first frame of a stream (fr->offset = 0) are not the data. It seems a header. And its size gets bigger as the resource size grows.
What this header contains and what is the relation between its size and the resource size?

Thanks.

**Comment by tatsuhiro-t** [comment]
If you are asking QUIC frame specification, please read RFC 9000.

**Comment by nEghbal** [comment]
I am asking about the first bytes of the **data part** of the first frame of a stream. 
When I am looking into fr->data[0].base in conn_recv_stream() of ngtcp2_conn.c, for the first 15-18 bytes of the first frame of stream they are not the resource file data, I was wondering what they are.

Thanks.

**Comment by tatsuhiro-t** [comment]
If you are asking about the contents of STREAM frame, it is application data.  I do not know which application protocol you are running on QUIC.  If it is HTTP/3, refer to HTTP/3 protocol specification.
