### ISSUE TITLE
Suggestion: can we set app_error_code even if STOP_SENDING is not going to be sent?

### ISSUE THREAD

**Issue by zg-8** [ngtcp2/ngtcp2#552]
Similar to previous issue https://github.com/ngtcp2/ngtcp2/issues/502, would it be reasonable to always set the `app_error_code` field of `ngtcp2_strm` at the beginning of [`conn_shutdown_stream_read`](https://github.com/ngtcp2/ngtcp2/blob/b1bd7f05567259e952106b4881b2907dd90382d8/lib/ngtcp2_conn.c#L12313) function (as shown below)?
```diff
static int conn_shutdown_stream_read(ngtcp2_conn *conn, ngtcp2_strm *strm,
                                     uint64_t app_error_code) {
+ ngtcp2_strm_set_app_error_code(strm, app_error_code);

  if (strm->flags & NGTCP2_STRM_FLAG_STOP_SENDING) {
    return 0;
  }
  if ((strm->flags & NGTCP2_STRM_FLAG_SHUT_RD) &&
      ngtcp2_strm_rx_offset(strm) == strm->rx.last_offset) {
    return 0;
  }

  /* Extend connection flow control window for the amount of data
     which are not passed to application. */
  if (!(strm->flags &
        (NGTCP2_STRM_FLAG_STOP_SENDING | NGTCP2_STRM_FLAG_RECV_RST))) {
    ngtcp2_conn_extend_max_offset(conn, strm->rx.last_offset -
                                            ngtcp2_strm_rx_offset(strm));
  }

  strm->flags |= NGTCP2_STRM_FLAG_STOP_SENDING;
- ngtcp2_strm_set_app_error_code(strm, app_error_code);

  return conn_stop_sending(conn, strm, app_error_code);
}
```
The specific code path that we looked into is the same as the one mentioned in issue https://github.com/ngtcp2/ngtcp2/issues/502. Particularly, when [`NGHTTP3_ERR_MALFORMED_HTTP_HEADER` is detected at higher level of the call stack](https://github.com/ngtcp2/nghttp3/blob/635a532c8ff98cdbd6c141f85583632919102912/lib/nghttp3_conn.c#L1342), we felt that we should probably set the [`NGHTTP3_H3_MESSAGE_ERROR`](https://github.com/ngtcp2/nghttp3/blob/635a532c8ff98cdbd6c141f85583632919102912/lib/nghttp3_conn.c#L1437) `app_error_code` to stream regardless whether a `STOP_SENDING` frame needs to be scheduled or not.

Thanks!

CC: @JunqiWang @amirlivneh

**Comment by tatsuhiro-t** [comment]
I think we should do this because STOP_SENDING is much like RESET_STREAM but in the opposite direction.  Will make a PR.
