### ISSUE TITLE
Version Negotiation: don't random unused field

### ISSUE THREAD

**Issue by alagoutte** [ngtcp2/ngtcp2#56]
in section 5.3 (https://tools.ietf.org/html/draft-ietf-quic-transport-08#section-5.3= about unused field in Version Negotiation packet

it is say 

> The value in the Unused field is selected randomly by the server.

But actually it is always 0x00 on all packet

```
QUIC (Quick UDP Internet Connections) IETF
    1... .... = Header Form: Long Header (1)
    .000 0000 = Unused: 0x00
    Connection ID: 0x8d6f4cca909c3202
    Version: Version Negotiation (0x00000000)
    Supported Version: Unknown (0x5e5cbb6a)
    Supported Version: Unknown (0x7aba6a4a)
    Supported Version: draft-08 (0xff000008)
```

**Comment by tatsuhiro-t** [comment]
35475539db575f1c674e1b387c2311ff795ccb2a fixes this issue.

**Comment by alagoutte** [comment]
Thanks !
