### ISSUE TITLE
ngtcp2_conn_get_expiry() will never return NGTCP2_ERR_IDLE_CLOSE

### ISSUE THREAD

**Issue by Blankwonder** [ngtcp2/ngtcp2#600]
The document says that: 

> After calling these functions, new expiry will be set. The application should call ngtcp2_conn_get_expiry() to restart timer. If ngtcp2_conn_get_expiry() returned NGTCP2_ERR_IDLE_CLOSE, it means that an idle timer has expired for this particular connection. In this case, drop the connection without calling ngtcp2_conn_write_connection_close().

But ngtcp2_conn_get_expiry() returns `ngtcp2_tstamp`, which is alias to `uint64_t`. And NGTCP2_ERR_IDLE_CLOSE is defined as `#define NGTCP2_ERR_IDLE_CLOSE -248`, which is negative.

**Comment by tatsuhiro-t** [comment]
I think it is a documentation bug.  The function which returns NGTCP2_ERR_IDLE_CLOSE is ngtcp2_conn_handle_expiry.
