### ISSUE TITLE
Example server and client stop after sometime

### ISSUE THREAD

**Issue by ShashiKiranMR** [ngtcp2/ngtcp2#602]
I am running the example server (server.cc) and client (client.cc) given in the examples folder.
After sometime they stop because the timer expires. Server received a packet from the client, and while creating the response I think it is stuck because ngtcp2_conn_writev_stream() is returning 0 indicating congestion and asking the application to wait.

Is this expected? Any inputs are highly appreciated!
(Server output on the left and client on the right in the image below)

![image](https://user-images.githubusercontent.com/13312710/196821709-38d8f286-c4c0-4297-baa8-b81c468fd478.png)

**Comment by tatsuhiro-t** [comment]
It is hard to tell from the image which only shows partial log lines.
Could you share the command line of both client and server?

**Comment by ShashiKiranMR** [comment]
Thanks for the response. Please find the commands I used below:
Server: ./server <server_ip> <server_port> <server.key> <server.crt>
Client: ./client <server_ip> <server_port>

**Comment by tatsuhiro-t** [comment]
I think you missed URI to a resource from the server.
Try: ./client <server_ip> <server_port> https://<server_ip>:<server_port>/

**Comment by ShashiKiranMR** [comment]
I am seeing same behavior even after mentioning a resource from the server.
It works for sometime and then the communication stops.

**Comment by tatsuhiro-t** [comment]
Could you share the complete command-line options and logs of both client and server?
It should work.  We have lots of interop testing every day.

**Comment by ShashiKiranMR** [comment]
Sure. These are the exact commands I am using:
server: ./server --qlog-dir=/tmp/ 128.110.218.44 10080 server.key server.crt
client: ./client 128.110.218.44 10080 https://128.110.218.44:10080/

Please find the attached log files.

[server.log](https://github.com/ngtcp2/ngtcp2/files/9831286/server.log)
[client.log](https://github.com/ngtcp2/ngtcp2/files/9831288/client.log)

**Comment by tatsuhiro-t** [comment]
Thank you.  I think client got response from server:

```
http: stream 0x0 response headers started
http: stream 0x0 [:status: 404]
http: stream 0x0 [server: nghttp3/ngtcp2 server]
http: stream 0x0 [content-type: text/html; charset=utf-8]
http: stream 0x0 [content-length: 147]
http: stream 0x0 headers ended
http: stream 0x0 body 147 bytes
```

**Comment by ShashiKiranMR** [comment]
Thanks for looking at the logs. Yes it gets the response but my question is more about the expected behavior of the client and server.

Does the client request for one http req and stop, or it keeps requesting as long as it is running?
I am trying to understand the reason why it stopped (in the end of the log file).

**Comment by tatsuhiro-t** [comment]
By default, client sends just the given requests, then it just sits there until idle timeout fires.

**Comment by ShashiKiranMR** [comment]
I see, is there an option on the client to keep making requests as long as it is running?

**Comment by tatsuhiro-t** [comment]
No, there is no such option.

**Comment by ShashiKiranMR** [comment]
Thank you for the response. I have one follow up question.
The client makes one request to the server and on every response, readcb() is invoking c->on_write() as well.
So shouldn't it be a continuous communication between the client and the server?

**Comment by tatsuhiro-t** [comment]
I'm not sure I follow your question.  Both party send some packets if needed as long as QUIC connection is alive.

**Comment by ShashiKiranMR** [comment]
My question is, if I want the client to keep making requests back to back (instead of one) could you suggest me where to change it?
I just want the client and server to be communicating continuously as long as they are running.

**Comment by tatsuhiro-t** [comment]
Check the handling of --streams client option which species the number of requests that client makes.

**Comment by ShashiKiranMR** [comment]
Got it. I will check, thank you for the info till now.
I shall close this issue now, and get back in case I need more info.
