### ISSUE TITLE
Understanding qlog of the example client and server

### ISSUE THREAD

**Issue by ShashiKiranMR** [ngtcp2/ngtcp2#613]
Hi,

I have one question related to the qlog of the example client and server. I captured this qlog on the server (examples/server.cc).
This is how the qvis graph looks like for the sqlog file generated. My question is about the packets that I have highlighted with black lines. Could someone please explain why these data streams are opened by the server first and then the client? And why before handshake is completed?

![image](https://user-images.githubusercontent.com/13312710/198113865-ddf9c9ae-82bf-4cba-b067-53811664b066.png)

Thanks in advance!

**Comment by tatsuhiro-t** [comment]
These streams are HTTP/3 and QPACK unidirectional streams.  Server can send 1RTT packets before handshake completion.

**Comment by ShashiKiranMR** [comment]
I see, thanks for the information. Could you please tell me what these unidirectional streams are used for (since it is before handshake completion) and which event in the code is triggering this?

**Comment by tatsuhiro-t** [comment]
Please read https://www.rfc-editor.org/rfc/rfc9114.html and https://www.rfc-editor.org/rfc/rfc9204.html

**Comment by ShashiKiranMR** [comment]
Thanks for the links, it was useful. 
One more question, does the qlog framework in ngtcp2 capture bidirectional streams carrying data or it is excluded for security reasons? I was unable to find a bidirectional stream carrying the http request and response.

**Comment by tatsuhiro-t** [comment]
qlog file should contain bidirectional streams.

**Comment by ShashiKiranMR** [comment]
Thanks for the information!
