### ISSUE TITLE
Running ngtcp2 on picotls

### ISSUE THREAD

**Issue by ShashiKiranMR** [ngtcp2/ngtcp2#627]
Hi,
I am trying to run the example server and client on picotls instead of openssl. I have cloned Picotls (commit 67ba66e91728316152fc2c2172710ca4c2236027) and have built it.

Could anyone please suggest me how to rebuild the example server and client to use picotls libraries?

Thanks in advance!

**Comment by tatsuhiro-t** [comment]
Pass --with-picotls, and PICOTLS_CFLAGS and PICOTLS_LIBS variables to configure script.

Check how it is built and configured in workflow:
https://github.com/ngtcp2/ngtcp2/blob/c891919abb89c5ae333c243ea9ba7138df88767c/ci/build_picotls.sh
https://github.com/ngtcp2/ngtcp2/blob/c891919abb89c5ae333c243ea9ba7138df88767c/.github/workflows/build.yml#L108-L109

**Comment by ShashiKiranMR** [comment]
Thanks for sharing the details, they were really useful. I followed the steps you suggested, but I am seeing that the examples are not being built when I run make.

This is the configure command I am using,
./configure --with-picotls PICOTLS_CFLAGS="-I$PWD/picotls/include/" PICOTLS_LIBS="-L$PWD/picotls/build -lpicotls-openssl -lpicotls-core" PKG_CONFIG_PATH=$PWD/../nghttp3/build/lib/pkgconfig

I removed openssl part from the default configure command example listed in the Readme. I do see that picotls is being built, below is the output at the end of the configure script. It also says Examples: yes.

Could you please let me know if I am using the wrong configure options?

**Comment by tatsuhiro-t** [comment]
I think it should work. The binaries you are looking for are ptlsclient and ptlsserver in examples directory.

**Comment by ShashiKiranMR** [comment]
Got it, yes it is working fine.
Thanks a lot for the help!
