### ISSUE TITLE
Should not use RST_STREAM frame to terminate stream

### ISSUE THREAD

**Issue by scw00** [ngtcp2/ngtcp2#64]
>8.3. RST_STREAM Frame
>After sending a RST_STREAM, an endpoint ceases transmission and retransmission of STREAM frames on the identified stream.

There is no guarantee that client can receive all packets after receive RST_STREAM frame.

**Comment by tatsuhiro-t** [comment]
Yes. Do you see ngtcp2 sends RST_STREAM, and expects that stream goes away?

**Comment by tatsuhiro-t** [comment]
Closing without action because we have not got new information since then.
