### ISSUE TITLE
Check ngtcp2_conn want write or read

### ISSUE THREAD

**Issue by flx413** [ngtcp2/ngtcp2#640]
Hi, I want to check ngtcp2_conn is active or idle, is there a function like nghttp2: 
```
nghttp2_session_want_read
nghttp2_session_want_write
```

**Comment by tatsuhiro-t** [comment]
If ngtcp2_conn_writev_stream produces nothing, it means ngtcp2_conn currently has nothing to send.
ngtcp2_conn is always reading unless it is in closing or draining state.
https://nghttp2.org/ngtcp2/ngtcp2_conn_is_in_closing_period.html
https://nghttp2.org/ngtcp2/ngtcp2_conn_is_in_draining_period.html

**Comment by flx413** [comment]
thanks a lot
