### ISSUE TITLE
lost bytes   when loss timeout happen

### ISSUE THREAD

**Issue by pamleft** [ngtcp2/ngtcp2#646]
Why does loss detection only when receiving packets increase the number of lost bytes

`
int ngtcp2_rtb_detect_lost_pkt(ngtcp2_rtb *rtb, ngtcp2_conn *conn,
                               ngtcp2_pktns *pktns, ngtcp2_conn_stat *cstat,
                               ngtcp2_tstamp ts) {
  return rtb_detect_lost_pkt(rtb, /* ppkt_lost = */ NULL, conn, pktns, cstat,
                             ts);
}
`
https://github.com/ngtcp2/ngtcp2/blob/main/lib/ngtcp2_rtb.c#L1333
`
  if (conn && num_acked > 0) {
    rv = rtb_detect_lost_pkt(rtb, &cc_ack.bytes_lost, conn, pktns, cstat, ts);
    if (rv != 0) {
      return rv;
    }
  }

  rtb->rst->lost += cc_ack.bytes_lost;
`
https://github.com/ngtcp2/ngtcp2/blob/main/lib/ngtcp2_rtb.c#L1109

And I found that the current version will have an assertion failure on the following line
`
static uint64_t bbr_inflight_hi_from_lost_packet(ngtcp2_bbr2_cc *bbr,
                                                 const ngtcp2_rs *rs,
                                                 const ngtcp2_cc_pkt *pkt) {
  uint64_t inflight_prev, lost_prefix;
  (void)bbr;

  assert(rs->tx_in_flight >= pkt->pktlen);

  inflight_prev = rs->tx_in_flight - pkt->pktlen;

  assert(rs->lost >= pkt->pktlen);

  /* bbr->rst->lost is not incremented for pkt yet */

  if (inflight_prev * NGTCP2_BBR_LOSS_THRESH_NUMER <
      rs->lost * NGTCP2_BBR_LOSS_THRESH_DENOM) {
    return inflight_prev;
  }

  lost_prefix = (inflight_prev * NGTCP2_BBR_LOSS_THRESH_NUMER -
                 rs->lost * NGTCP2_BBR_LOSS_THRESH_DENOM) /
                (NGTCP2_BBR_LOSS_THRESH_DENOM - NGTCP2_BBR_LOSS_THRESH_NUMER);

  return inflight_prev + lost_prefix;
}
`
https://github.com/ngtcp2/ngtcp2/blob/7b55b0ae632c1079cab8eccdba0032b2c8daabe4/lib/ngtcp2_bbr2.c#L987

**Comment by tatsuhiro-t** [comment]
> Why does loss detection only when receiving packets increase the number of lost bytes

Not sure I understand your question, but the loss detection is performed when ACK frame acknowledges new packets as per
https://datatracker.ietf.org/doc/html/rfc9002#section-6.2

> When an acknowledgment is received that newly acknowledges packets, loss detection proceeds as dictated by the packet and time threshold mechanisms

As for assertion failure, I will look into it.  It might be a false assertion for the old implementation.

**Comment by pamleft** [comment]
ありがとうございます


I'll read the paper, and think. Thank you so much!


assert false，I made rst lost += lost bytes before on pkt lost，I'm not sure that is right.



---Original---
From: "Tatsuhiro ***@***.***&gt;
Date: Fri, Dec 30, 2022 09:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ngtcp2/ngtcp2] lost bytes   when loss timeout happen (Issue #646)




  
Why does loss detection only when receiving packets increase the number of lost bytes
  
Not sure I understand your question, but the loss detection is performed when ACK frame acknowledges new packets as per
 https://datatracker.ietf.org/doc/html/rfc9002#section-6.2
  
When an acknowledgment is received that newly acknowledges packets, loss detection proceeds as dictated by the packet and time threshold mechanisms
  
As for assertion failure, I will look into it.  It might be a false assertion for the old implementation.

**Comment by tatsuhiro-t** [comment]
bbr_inflight_hi_from_lost_packet has a comment saying bbr->rst->lost is not updated for the very lost packet, so moving the line before loss detection causes trouble.  The reason is somewhat subtle.  #647  fixes this assertion failure without changing this assumption.
