### ISSUE TITLE
Running client issues

### ISSUE THREAD

**Issue by gholamw** [ngtcp2/ngtcp2#65]
Hi, 
I'm considering ngtcp2 library to be used for my final year college project. I'm trying to implement DNS/QUIC. I'm just starting my project, so I tried to run the code for the first time. ran both client and server executables under examples folder. The issue is that when I run the client I get the following error message: 
"TLS handshake error: error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available
ngtcp2_conn_write_pkt: ERR_CALLBACK_FAILURE
ngtcp2_conn_write_connection_close: ERR_INVALID_STATE
ngtcp2_conn_write_connection_close: ERR_INVALID_STATE"

If you can please point me to right direction, it would be really appreciated. Thanks.

-- Wessam Gholam

**Comment by tatsuhiro-t** [comment]
If I understand it correctly, you ran examples/client against examples/server, and got this error.
Could you check that OpenSSL latest master branch is used, and compiled with TLSv1.3 enabled?

**Comment by tatsuhiro-t** [comment]
Closing with no action because no new information has been received for quite a long time.
