### ISSUE TITLE
Unidirectional streams never closing on the remote side

### ISSUE THREAD

**Issue by dagf2101** [ngtcp2/ngtcp2#662]
Hello, we recently rebased our changes to the latest tag and had issues with unidirectional streams. (bidi are fine)

Basically the validation of ngtcp2_strm_is_all_tx_data_**fin**_acked is never true and the stream_close is never called on the remote side.

The issue is happening since this commit:
https://github.com/ngtcp2/ngtcp2/commit/d39baa1edf610e86a272747217dd7528935eb360#diff-856b98c6ca3e47b9e8a751bf2b67d7347c9a72babe1d30f97f578bbfeb4dce02

I did a workaround using part of previous code but I was wondering if you have an idea on it.
![image](https://user-images.githubusercontent.com/19212460/215788829-94a03f97-dd97-43ff-8795-5816b73448fc.png)

Regards.

**Comment by tatsuhiro-t** [comment]
Yes, the offending commit does not deal with the remote uni stream closure.
I'll fix this issue very soon.

**Comment by tatsuhiro-t** [comment]
https://github.com/ngtcp2/ngtcp2/pull/664 fixes this bug.  Thank you for reporting this issue.
