### ISSUE TITLE
Programmers Guide do not talk about NGTCP2_ERR_HANDSHAKE_TIMEOUT

### ISSUE THREAD

**Issue by jpboivin** [ngtcp2/ngtcp2#670]
Hello,

In the Programmers Guide's Timers section, it is mentioned that if `ngtcp2_conn_handle_expiry()` returns `NGTCP2_ERR_IDLE_CLOSE`, the connection timed out (an idle timer has fired). But this does not consider the part where the connection times out during the handshake (based on the `handshake_timeout` setting), which will make this function returns `NGTCP2_ERR_HANDSHAKE_TIMEOUT`. Should probably be mentioned in the Programmers Guide.

Best regards,
Jean-Philippe

**Comment by tatsuhiro-t** [comment]
General error handling is described in https://nghttp2.org/ngtcp2/programmers-guide.html#error-handling-in-general
The error not specifically mentioned, including NGTCP2_ERR_HANDSHAKE_TIMEOUT, should be dealt with by calling ngtcp2_conn_write_connection_close.

If it is not obvious, I can add some text to describe about NGTCP2_ERR_HANDSHAKE_TIMEOUT in Timers section.

**Comment by jpboivin** [comment]
Sounds good to me! I did not consider looking at this section, but it explains well the error handling for the whole library!
