### ISSUE TITLE
NGHTTP3_ERR_WOULDBLOCK and nghttp3_conn_resume_stream

### ISSUE THREAD

**Issue by GenadiBabenko** [ngtcp2/ngtcp2#678]
Hello

Thank you for your contributions to the community!
I am implementing  nghttp3_data_reader.read_data callback in the server.cc example, when the served data is only sometimes ready. If data is not prepared, the callback returns  NGHTTP3_ERR_WOULDBLOCK and posts an event whose handler calls nghttp3_conn_resume_stream. 
This approach works if the resume posting is called from the read
_data callback, but the running time increases from ten to a hundred times compared to the version which sends chunks(1350 bytes) when the data is always ready. After 2 or 3 consecutive calls that return NGHTTP3_ERR_WOULDBLOCK, the connection breaks.   
If the stream resume is posted from a different thread, it takes seconds to send a 10K file to Firefox or Chrome. If the client is curl, it outputs the error EAGAIN and terminates.
Another occasional issue is that the read_data callback called after WOULD_BLOCK, before nghttp3_conn_resume_stream. 

Any advice or suggestions would be greatly appreciated. Thank you for your time and help.
Genadi

**Comment by tatsuhiro-t** [comment]
I am quite not sure the situation, but if you are manipulating ngtcp2 or nghttp3 objects from multiple threads, those operations must be serialized with locks, otherwise the behavior is undefined.

**Comment by GenadiBabenko** [comment]
I do not manipulate ng objects from other threads; I called event post(using libevent API) from another thread to postpone calling nghttp3_conn_resume_stream(to emulate waiting for data ready), then nghttp3_conn_resume_stream called in corresponding event handler from ng event loop thread. All ng objects are processed in ng callbacks only. There are no blocking operations in ng callbacks. 
The problem is not with data race but with returning NGHTTP3_ERR_WOULDBLOCK from nghttp3_data_reader.read_data callback when data is not ready. The same problem occurred when I posted an event for nghttp3_conn_resume_stream from nghttp3_data_reader.read_data callback before returning NGHTTP3_ERR_WOULDBLOCK.

**Comment by tatsuhiro-t** [comment]
I am still unable to understand the issue.  It looks like you are calling (directly or indirectly, I do not know) nghttp3_conn_resume_stream from inside nghttp3_data_read_callback, if so it does not work.  nghttp3_conn_resume_stream should be called out side of  nghttp3_data_read_callback.
examples/server.cc has the correct use of these callbacks.

**Comment by tatsuhiro-t** [comment]
I think you do not trigger "write" after nghttp3_conn_resume_stream is called if it happens in the event independent from read or write packets.

**Comment by GenadiBabenko** [comment]
There is dyn_read_data function in the server.cc file. It does not implement cases when data is not ready. I
The nghttp3 programmer's guide says: 
"The nghttp3_data_reader.read_data is a callback function to generate HTTP payload. Application must retain the data passed to the library until those data are acknowledged by nghttp3_callbacks.acked_stream_data. When no data is available but will become available in the future, application returns NGHTTP3_ERR_WOULDBLOCK from this callback. Then the callback is not called for the particular stream until nghttp3_conn_resume_stream() is called."

I changed dyn_read_data to implement this approach the way I understanded it. 
In pseudocode, it looks like this:

dyn_read_data() 
{
if (data_ready) {
    start new thread {
    sleep some milliseconds to emulate data producer work
    set data_ready = true
    ev_async_send (servers_event_loop, ev_async_obj)
    /* handler of ev_async_obj is a callback that calls nghttp3_conn_resume_stream, 
       the callback running in the server's main loop thread */
   return NGHTTP3_ERR_WOULDBLOCK;
} else {
	data is ready, processing is the same as in the original example
    set data_ready = false
 }
}

Is there a problem with this code?

**Comment by tatsuhiro-t** [comment]
The pseudo code seems ok.  Make sure that after nghttp3_conn_resume_stream is called, "write" is performed, for example, by calling Handler::signal_write().

**Comment by GenadiBabenko** [comment]
Do you mean Handler::signal_write should be called immediately after nghttp3_conn_resume_stream when data is ready? I tried to do this. It partially helped. 
After this change, Firefox and Curl can download big files when the server's data_read returns small chunks or NGHTTP3_ERR_WOULDBLOCK each second call. The data transfer rate is proportional to the data producer delay, and I do not see any delay in the ng library, which is excellent!
There is still an issue opening complicated htmls in the same mode(chunked with sometimes data not ready); some streams failed with NGHTTP3_H3_REQUEST_CANCELLED. If read_data does not return NGHTTP3_ERR_WOULDBLOCK, opening the same htmls is always OK in chunked mode.
Is there a working code similar to what I did?
I tried to google NGHTTP3_ERR_WOULDBLOCK, but there is no such example.

**Comment by tatsuhiro-t** [comment]
Handler::signal_write is a part of examples, not API.  Closing this issue, because it has been resolved.
