### ISSUE TITLE
ngtcp2_conn_get_send_quantum() usage

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#693]
The programmer's guide says:

> After one or more calls of ngtcp2_conn_writev_stream() (it can be called multiple times to fill the buffer sized up to ngtcp2_conn_get_send_quantum() bytes), call ngtcp2_conn_update_pkt_tx_time() to set the timer when the next packet should be sent. The timer is integrated into ngtcp2_conn_get_expiry().

But after sending a quantum, client.cc not only waits for the timer to send the next packet, but also starts a socket writable watcher:
https://github.com/ngtcp2/ngtcp2/blob/694f3c4afc7d7b11161e003265e30420eba7f37a/examples/client.cc#L1086-L1090

Which one is the correct behavior?

**Comment by tatsuhiro-t** [comment]
I think start_wev_endpoint is unnecessary now because ngtcp2 enables pacing for all controllers.
It is required when it did not have pacing or partially enabled pacing for certain congestion controllers (e.g., BBR).

**Comment by tatsuhiro-t** [comment]
#693 fixes this issue.
