### ISSUE TITLE
Cannot fill the pipe!

### ISSUE THREAD

**Issue by nEghbal** [ngtcp2/ngtcp2#703]
Hello,

I captured the arrival time of QUIC frames at the client side. For a 15 KB file, I set RTT to 100ms using netem tc:

t0 = 1678263173694323 micro sec
[Nooshin] t0   fr->offset: 0, stream id: 0    	
[Nooshin] t0 + 79   fr->offset: 342, stream id: 0
[Nooshin] t0 + 125   fr->offset: 1501, stream id: 0
[Nooshin] t0 + 164   fr->offset: 2660, stream id: 0
[Nooshin] t0 + 225   fr->offset: 3819, stream id: 0
[Nooshin] t0 + 238   fr->offset: 4978, stream id: 0
[Nooshin] t0 + 277   fr->offset: 6137, stream id: 0
[Nooshin] t0 + 307   fr->offset: 7296, stream id: 0
[Nooshin] t0 + 338   fr->offset: 8455, stream id: 0
[Nooshin] t0 + 371   fr->offset: 9614, stream id: 0
[Nooshin] t0 + 444   fr->offset: 10773, stream id: 0
[Nooshin] t0 + 481   fr->offset: 11932, stream id: 0
**[Nooshin] t0 + 101960   fr->offset: 13091, stream id: 0**
[Nooshin] t0 + 102026   fr->offset: 14242, stream id: 0

And when I set RTT to 200ms, the results are:

t0 = 1678351629015469 micro sec
[Nooshin] t0   fr->offset: 0, stream id: 0  
[Nooshin] t0 + 95   fr->offset: 342, stream id: 0 
[Nooshin] t0 + 152   fr->offset: 1501, stream id: 0 
[Nooshin] t0 + 197   fr->offset: 2660, stream id: 0 
[Nooshin] t0 + 235   fr->offset: 3819, stream id: 0 
[Nooshin] t0 + 271   fr->offset: 4978, stream id: 0 
[Nooshin] t0 + 307   fr->offset: 6137, stream id: 0 
[Nooshin] t0 + 369   fr->offset: 7296, stream id: 0 
[Nooshin] t0 + 419   fr->offset: 8455, stream id: 0 
[Nooshin] t0 + 464   fr->offset: 9614, stream id: 0 
[Nooshin] t0 + 548   fr->offset: 10773, stream id: 0 
[Nooshin] t0 + 589   fr->offset: 11932, stream id: 0 
**[Nooshin] t0 + 201726   fr->offset: 13091, stream id: 0** 
[Nooshin] t0 + 201778   fr->offset: 14242, stream id: 0 

It seems that the buffer of the client is about 12 KB, that is why the QUIC frame with offset 13091 in both experiments, was received after one RTT.
I looked into the client options but all of them were in the order of MB. 

Do you know how I can increase the client buffer to be able to fill the pipe?

Thanks,
Nooshin

**Comment by tatsuhiro-t** [comment]
Try client --max-stream-data-bidi-local and  --max-data to increase flow control window.

**Comment by nEghbal** [comment]
I tried --max-stream-data-bidi-remote=50M at the server side, and --max-data=50M and --max-stream-data-bidi-local=50M and --max-stream-data-uni=50M at the client side but did not get any improvement.

**Comment by tatsuhiro-t** [comment]
If you are arguing that pipe is not filled in the first flight, it is because CWND is not extended.

**Comment by nEghbal** [comment]
I understand. But the output of client --help says that the default value of the buffers/windows is 6-16 M while in my experiments it is about 12-13 K.

**Comment by tatsuhiro-t** [comment]
You misunderstand flow control windows and cwnd.  They are completely different things.  All you can change are flow control stuff.  Even if you set larger flow control window, you cannot send that much if cwnd is smaller than that.  Basically, cwnd is increased when an endpoint receives acknowledgements from a remote endpoint, thus needs some round trips.

**Comment by nEghbal** [comment]
I see.
What is the variable for cwnd so I can increase its initial value?
