### ISSUE TITLE
Crash caused by NGTCP2_WRITE_STREAM_FLAG_MORE flag

### ISSUE THREAD

**Issue by Blankwonder** [ngtcp2/ngtcp2#707]
When using the function ngtcp2_conn_writev_stream() with the NGTCP2_WRITE_STREAM_FLAG_MORE flag, if NGTCP2_ERR_STREAM_DATA_BLOCKED is returned, the internal flag NGTCP2_CONN_FLAG_PPE_PENDING remains set. As a result, subsequent calls to ngtcp2_conn_write_pkt() will crash due to an assert failure. 

This does not look like an expected behavior. Please let me know if I miss something.

**Comment by tatsuhiro-t** [comment]
Could you share which assertion fails in this case?

**Comment by tatsuhiro-t** [comment]
After getting NGTCP2_ERR_STREAM_DATA_BLOCKED, ngtcp2_conn_writev_stream must be called until it returns 0 or positive value.  Did you do that?

**Comment by Blankwonder** [comment]
Oh, sorry, I missed that. I just upgraded from an old version, so I didn't read the new comment about NGTCP2_ERR_STREAM_DATA_BLOCKED.
