### ISSUE TITLE
What's the long-term plan for this project?

### ISSUE THREAD

**Issue by futan-yj** [ngtcp2/ngtcp2#726]
Dear authors,
    Thanks for your effort on the quic/http3 support, we have a project that have integrated ngtcp2/nghttp3/curl and quic work perfectly in local environment, now we're going to release more users, but have some questions before do that:
1. Do we have any data that tell who/what popular projects use this implementation to claims its stability?
2. Since http3 has released it's first RTC9114 / RFC9000 version, how many features may still not implemented on the two RFCs ?
3. Any further plan on the quic support?

And also, (not sure if it may offend you, but for us is very important), how to compare Cronet with curl(with nghttp2/nghttp3/ngtcp2) combination in your opinion, since they have many similar abilities.

Looking forward for your response, many many thanks in advance!!!

**Comment by tatsuhiro-t** [comment]
> 1. Do we have any data that tell who/what popular projects use this implementation to claims its stability?

I have no idea.  Curl at least uses ngtcp2 and nghttp3.

> 2. Since http3 has released it's first RTC9114 / RFC9000 version, how many features may still not implemented on the two RFCs ?

We have implemented all required features for QUIC and HTTP/3.  The exception is HTTP/3 server push, which is largely useless since the adoption by HTTP/2 (and even in spdy era).

For Cronet, I have absolutely no idea at all.

**Comment by futan-yj** [comment]
Many thanks.
