### ISSUE TITLE
When can the client open new streams?

### ISSUE THREAD

**Issue by ioquatix** [ngtcp2/ngtcp2#764]
(It might be a nice idea to enable GitHub Discussions for this project).

I'd like to understand a little more about the correct way to implement a client.

When the client negotiates the connection with the server, when is the first point at which the client can open a new stream?

Some code, e.g. `simpleclient.c` does it in `extend_max_local_streams_bidi`. In `client.cc` it's done in `Client::on_extend_max_streams`. Is this actually a logical place to implement stream creation?

From a developer point of view, it feels odd to create streams in a callback. I suppose the alternative is to create streams without a stream id, and then buffer the stream data until the stream can be actually created.

i.e. hypothetically speaking:

```c++
auto connection = Client(remote_address);
auto stream = connection.open_bidirectional_stream() // Should this effectively block until `extend_max_local_streams_bidi` is called?

stream->write(request_data);
stream->read(...); // etc
```

I suppose it's up to the library, but it's not clear to me what the logical design is. It might be nice to provide some guidance to users of `ngtcp2`.

**Comment by ioquatix** [comment]
That makes sense.

Regarding creating streams, I assume if the stream is blocked (due to lack of stream IDs), you must wait until `extend_max_local_streams_bidi` is invoked. In other words, stream creation looks like this:

```c++
Client::open_bidirectional_stream() {
  result = ngtcp2_open_stream_bidi();
  if (result == blocked) {
    condition.wait();
  }
}

auto connection = Client(remote_address);
auto stream = connection.open_bidirectional_stream()
```

**Comment by ioquatix** [comment]
> Because how quic is designed, application can open streams a bit earlier. I will describe it in the document.

This is only true when the early data is available right?

**Comment by tatsuhiro-t** [comment]
> This is only true when the early data is available right?

No, client can open streams when it gets 1RTT RX key, which is sequenced before handshake completion.
That is quite low level stuff you know, but that is how it works.

**Comment by tatsuhiro-t** [comment]
In #766, I added some texts about when application can start opening streams.  That is basically what I wrote here.

**Comment by ioquatix** [comment]
Okay, so in all cases, extend_max_local_streams_bidi would eventually be called, to indicate that streams can be created?

**Comment by tatsuhiro-t** [comment]
except for 0rtt, yes.

**Comment by ioquatix** [comment]
It would be nice to clarify that:

- For 0RTT, clients can try to create streams after processing early data via `ngtcp2_conn_decode_early_transport_params`.
- Otherwise, in all other cases, you can create streams in `extend_max_local_streams_bidi`.

**Comment by tatsuhiro-t** [comment]
We have this text:

> When sending early data, the remembered transport parameters should be set via [ngtcp2_conn_decode_early_transport_params()](https://nghttp2.org/ngtcp2/ngtcp2_conn_decode_early_transport_params.html#c.ngtcp2_conn_decode_early_transport_params). Then client can open streams with ngtcp2_conn_open_bidi_streams() or [ngtcp2_conn_open_uni_stream()](https://nghttp2.org/ngtcp2/ngtcp2_conn_open_uni_stream.html#c.ngtcp2_conn_open_uni_stream).

**Comment by ioquatix** [comment]
I would add a section "When can I create streams?" to this page: https://nghttp2.org/ngtcp2/programmers-guide.html

**Comment by tatsuhiro-t** [comment]
#766 added a text to describe when application can open streams and you reviewed that.

**Comment by ioquatix** [comment]
Yeah, maybe it's good enough.

Streams are a very central concept, and clearly explaining the life cycle can be very helpful.

**Comment by ioquatix** [comment]
Are you okay if I make some PRs to the documentation? Maybe I can help that way.

**Comment by tatsuhiro-t** [comment]
That is welcome.  Note that I have no plan to add images or diagrams at the moment because that is hard to maintain.

**Comment by tatsuhiro-t** [comment]
For bidi stream closure, send-side stream is closed when you call ngtcp2_conn_writev_stream with NGTCP2_WRITE_STREAM_FLAG_FIN flag set and all data are acknowledged.
Receive-side stream is when a local endpoint receives fin from remote endpoint and all data are received.
And then stream_close callback is invoked.

You can close stream early abruptly by calling ngtcp2_conn_shutdown_stream.
It has ngtcp2_conn_shutdown_stream_write and ngtcp2_conn_shutdown_stream_read variants that close the individual side of a stream.

**Comment by ioquatix** [comment]
Mermaid diagrams are text based so they are quite easy to maintain. But I don't know if it's supported by RST.

```mermaid
stateDiagram-v2
    [*] --> Handshake: recv_rx_key
    [*] --> Connected: ngtcp2_conn_decode_early_transport_params
    Handshake --> Connected: handshake_completed
    Connected --> Stream: extend_max_local_streams_bidi
    Connected --> Stream: extend_max_local_streams_uni
```

In any case, I'll close this issue and if I think of PRs to improve the documentation, I'll open them.
