### ISSUE TITLE
Assert failed in ngtcp2_rtb.c

### ISSUE THREAD

**Issue by Blankwonder** [ngtcp2/ngtcp2#770]
Hi

I received several random crash reports from my users. At present, no commonality has been found among these crashes.

Version: ngtcp2-0.13.1. Call stack:

```
SIGABRT: 

0  libsystem_kernel.dylib +0x81f2  __pthread_kill
1  libsystem_c.dylib +0x7fb42      abort
2  libsystem_c.dylib +0x7ee5a      __assert_rtn
3  Surge +0x413912                 ngtcp2_rtb_recv_ack.cold.1 (ngtcp2_rtb.c:1067:7)
4  Surge +0x3a568e                 ngtcp2_rtb_recv_ack (ngtcp2_rtb.c:1067:7)
5  Surge +0x39ed00                 conn_recv_ack (ngtcp2_conn.c:5454:15)
6  Surge +0x39b8f0                 conn_recv_pkt (ngtcp2_conn.c:9188:12)
7  Surge +0x390be6                 conn_recv_cpkt (ngtcp2_conn.c:9599:13)
8  Surge +0x178ee8                 -[SGQUICClientSession udpSocket:didReceiveData:fromAddress:] (SGQUICClientSession.m:425:14)
```

The corresponding assert code is

`
      assert(largest_acked_sent_ts == UINT64_MAX ||
             largest_acked_sent_ts <= ent->ts);
`

May I ask if this is a bug or an issue with my usage? If more information is needed, please let me know. Thank you very much.

**Comment by tatsuhiro-t** [comment]
If you call ngtcp2 API against a single ngtcp2_conn instance from multiple threads without locks, anything bad happens.
Also make sure that you provide non-decreasing timestamp.  Passing system clock is not good because it can go backward.

**Comment by Blankwonder** [comment]
Thank you for the very prompt response. I do use `clock_gettime(CLOCK_MONOTONIC, &tp)` to provide non-decreasing timestamp. I will further confirm whether there is a race condition issue.

**Comment by Blankwonder** [comment]
After adding some assertions, I confirmed that the problem was caused by timestamp rollback. Shockingly, clock_gettime(CLOCK_MONOTONIC, &tp) cannot guarantee monotonic increase in Darwin (iOS/macOS).
