### ISSUE TITLE
Test coverage of conn_create_ack_frame() 

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#773]
Is there a plan to add test coverage of `conn_create_ack_frame()`? I'm experimenting with some changes and noticed that it is currently not exercised in tests.

**Comment by tatsuhiro-t** [comment]
It is always a good idea to add tests for functions not tested that much.  Will expose the function internally and add the tests.

**Comment by tatsuhiro-t** [comment]
#774 adds tests for ngtcp2_conn_create_ack_frame.

**Comment by amirlivneh** [comment]
Thank you.
