### ISSUE TITLE
./configure: line 3795: syntax error near unexpected token`2.2.6'

### ISSUE THREAD

**Issue by purplehorse** [ngtcp2/ngtcp2#78]
When I make

$ ./configure PKG_CONFIG_PATH=$PWD/../openssl/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,$PWD/../openssl/build/lib"

I get 
```

./configure: line 3795: syntax error near unexpected token`2.2.6'
./configure: line 3795: `LT_PREREQ(2.2.6)'
```

**Comment by tatsuhiro-t** [comment]
I think you need libtool.

**Comment by purplehorse** [comment]
I installed "sudo apt install libtool-bin" and the problem persists.

**Comment by tatsuhiro-t** [comment]
Did you re-run `autoreconf -i`?

**Comment by purplehorse** [comment]
That solved the "configure" problem! Now the problem comes when I run "make..."

```
In file included from client.cc:45:00
client.h:40:10 fatal error: ev.h: No such file or directory
  #include <ev.h>
           ^~~~~~
compilation terminated.
```

**Comment by LPardue** [comment]
Sounds like you need libev developer package.

**Comment by rmarx** [comment]
I just did a full new install (Ubuntu 16.04) and needed:
```
sudo apt-get install -y pkg-config autoconf automake autotools-dev libtool libev-dev
```
Other than that, the instructions in the current README just work.

**Comment by Citrullin** [comment]
> I just did a full new install (Ubuntu 16.04) and needed:
> 
> ```
> sudo apt-get install -y pkg-config autoconf automake autotools-dev libtool libev-dev
> ```
> 
> Other than that, the instructions in the current README just work.

Thanks, this fixed it for me.
