### ISSUE TITLE
Malformed frames are decoded as STREAM frames

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#781]
If `ngtcp2_pkt_decode_frame()` is passed the payload {0xff, 0x01, 0x01, 0x01, 0x01} it returns 5 and sets `dest->type` to `NGTCP2_FRAME_STREAM`.

The condition 
https://github.com/ngtcp2/ngtcp2/blob/61b3cea2e5e52d0da9ec3d48c50bc00c94aefccb/lib/ngtcp2_pkt.c#L545
may be too relaxed.

**Comment by tatsuhiro-t** [comment]
Thank you.  So it should be `(type & 0xf8) == NGTCP2_FRAME_STREAM`.

**Comment by amirlivneh** [comment]
Thank you.
