### ISSUE TITLE
Max input data size of ngtcp2_conn_writev_datagram()

### ISSUE THREAD

**Issue by Blankwonder** [ngtcp2/ngtcp2#811]
Call ngtcp2_conn_writev_datagram() with an oversize input data buffer (1209 bytes during the test) will fail with paccepted == 0 and nwrite == 0. Is there a way to calculate the maximum length of QUIC datagrams that can be sent? 

Thanks.

**Comment by tatsuhiro-t** [comment]
It depends on the length of Destination Connection ID, and packet number encoding, and buffer size you give to the function.
Roughly, subtracting QUIC packet header, DATAGRAM frame header, and AEAD tag (which is 16 bytes for defined cipher suites) from ngtcp2_conn_get_path_max_tx_udp_payload_size gives you the available payload size.

But if you have data which is larger than that, DATAGRAM cannot be split, so you cannot send it.  Are you padding data to somewhat hide the length, like described in DNS over QUIC?

**Comment by Blankwonder** [comment]
Thank you for your explanation. It would be great if a built-in function could provide the calculated result.

I am implementing a QUIC-based UDP proxy relay. It is because DATAGRAM cannot be split that the data packets need to be segmented in the upper-layer proxy protocol, similar to IP fragmentation. Therefore, it is necessary to know the maximum data segment length in advance for segmentation.

**Comment by tatsuhiro-t** [comment]
For now, it would be something like ngtcp2_conn_get_path_max_tx_udp_payload_size() - 44.
where
1 + dcidlen(20) + packetnum(4) + aeadtag(16) + frametype(1) + dgramlen(2) = 44
assuming that the maximum DATAGRAM to send is up to 16383.
