### ISSUE TITLE
Connection Migration

### ISSUE THREAD

**Issue by Claireecf** [ngtcp2/ngtcp2#816]
Hello,
I am testing QUIC with and without connection migration. Is there a way to enable or disable the connection feature in Ngtcp2? I am using the client provided in the example. Thanks in advance.

**Comment by tatsuhiro-t** [comment]
ngtcp2 client starts migration if one of the following functions are used:

- https://nghttp2.org/ngtcp2/ngtcp2_conn_initiate_immediate_migration.html
- https://nghttp2.org/ngtcp2/ngtcp2_conn_initiate_migration.html

Without these functions, ngtcp2 does not start active migration.
