### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by suenway** [ngtcp2/ngtcp2#83]
I compiled the latest master against https://github.com/tatsuhiro-t/openssl.git(quic-draft-13) and encountered the following crash when starting the example client. Pls take a look.

> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff76363a5 in OPENSSL_sk_num () from /data/web_server/project/ats/lib/libcrypto.so.1.1
> (gdb) bt
> #0  0x00007ffff76363a5 in OPENSSL_sk_num () from /data/web_server/project/ats/lib/libcrypto.so.1.1
> #1  0x00007ffff7971dd9 in tls_construct_ctos_use_srtp () from /data/web_server/project/ats/lib/libssl.so.1.1
> #2  0x00007ffff7970983 in tls_construct_extensions () from /data/web_server/project/ats/lib/libssl.so.1.1
> #3  0x00007ffff797a8ee in tls_construct_client_hello () from /data/web_server/project/ats/lib/libssl.so.1.1
> #4  0x00007ffff7979807 in state_machine () from /data/web_server/project/ats/lib/libssl.so.1.1
> #5  0x00007ffff7965f40 in SSL_do_handshake () from /data/web_server/project/ats/lib/libssl.so.1.1
> #6  0x00000000004096da in Client::tls_handshake(bool) ()
> #7  0x0000000000408027 in (anonymous namespace)::client_initial(ngtcp2_conn*, void*) ()
> #8  0x00007ffff7bc86f3 in conn_write_client_initial (ts=1534491610446095104, require_padding=1, destlen=<optimized out>, dest=0x65a6d0 "", conn=0x65cc10)
>     at ngtcp2_conn.c:1486
> #9  conn_handshake (conn=0x65cc10, dest=0x65a6d0 "", destlen=<optimized out>, pkt=0x0, pktlen=<optimized out>, require_padding=1, ts=1534491610446095104)
>     at ngtcp2_conn.c:4311
> #10 0x00007ffff7bc8a5d in ngtcp2_conn_handshake (conn=<optimized out>, dest=<optimized out>, destlen=<optimized out>, pkt=<optimized out>, 
>     pktlen=<optimized out>, ts=<optimized out>) at ngtcp2_conn.c:4518
> #11 0x0000000000409ba8 in Client::do_handshake_once(unsigned char const*, unsigned long) ()
> #12 0x000000000040cb9c in (anonymous namespace)::run(Client&, char const*, char const*) ()
> #13 0x000000000040d31a in main ()

**Comment by tatsuhiro-t** [comment]
I think the latest version might fix this issue.  Try the latest version and reopen the issue if it still persists.
