### ISSUE TITLE
client/server examples using unreliable datagram extension

### ISSUE THREAD

**Issue by nEghbal** [ngtcp2/ngtcp2#845]
Hello,

Although ngtcp2 has the implementation of the unreliable datagram QUIC extension, is there any example that uses that extension?
Is it easy to convert the current HTTP3 client/server to use that extension or I need to modify several part?

For example, in server.cc if I change ngtcp2_conn_writev_stream() in write_streams() to ngtcp2_conn_writev_datagram(), then the server would send datagram frames?

Thanks,
Nooshin

**Comment by tatsuhiro-t** [comment]
It would send DATAGRAM, but it does not work because HTTP/3 is not designed in such a way.  DATAGRAM also needs to be fit within one packet on the other hand, regular stream can span multiple packets.

**Comment by nEghbal** [comment]
My goal is using the unreliable QUIC datagram only for sending resources (not control frames) and then support reliability at HTTP layer.
However, I am still not being able to replace ngtcp2_conn_writev_stream() with ngtcp2_conn_writev_datagram() in server.cc properly.
The return value of ngtcp2_conn_writev_datagram()  is NGTCP2_ERR_WRITE_MORE.

Here is the new call of writev_datagram() in my code when both max-udp-payload-size and max-datagram-frame-size were set to 1200:

auto nwrite2 = ngtcp2_conn_writev_datagram(
        conn_, &ps.path, &pi, bufpos, max_udp_payload_size, NULL, flags,
        dgram_id, reinterpret_cast<const ngtcp2_vec *>(v), vcnt, ts);
        dgram_id += 1; 

Am I doing anything wrong? 
Any help would be great.

Bests,
Nooshin

**Comment by nEghbal** [comment]
Hello,

I could manage replacing ngtcp2_conn_writev_stream() in server.cc with ngtcp2_conn_writev_datagram() to send the first resource that we wanted to send over stream_id = 0 using unreliable datagrams.
I also implemented the recv_datagram callback to receive them and write them in a file.

The only problem is that the dgram_id of all received datagram frames is **7** although in server.cc I started from id=0 and increase it for the next one.

Any idea?

**Comment by tatsuhiro-t** [comment]
dgram_id is an identifier to be passed to ack_datagram or lost_datagram callbacks.  It never be sent to a remote endpoint.  datagram is not associated to any stream unless you define a protocol over QUIC.

**Comment by nEghbal** [comment]
if it won't be sent to the remote endpoint, why we have it as a parameter for ngtcp2_conn_writev_datagram()? 
I thought that ack_datagram/lost_datagram callbacks are used at the client side and the only way of knowing that a datagram frame got lost is by checking the dgram_ids.

Am I wrong?

**Comment by tatsuhiro-t** [comment]
It is used solely in a local endpoint that sends datagram to identify datagram in callbacks.  Without that, you never know which one is acknowledged or lost.

**Comment by nEghbal** [comment]
Ok, I see.
So, if I want to let the receiver (client) know the ID, I need to use the first part of the data for that.
Thanks.

**Comment by nEghbal** [comment]
Hello,

I am comparing the performance/latency of using STREAM frames v.s. DATAGRAM frames.
I realize that sending the same 10KB resource from server using datagram took more time than stream to get received at client:

[Nooshin] 1690094483888721   datagram_id: 0 
[Nooshin] 1690094483889464   datagram_id: 1 
[Nooshin] 1690094483890272   datagram_id: 2 
[Nooshin] 1690094483891064   datagram_id: 3 
[Nooshin] 1690094483891842   datagram_id: 4 
[Nooshin] 1690094483892588   datagram_id: 5 
[Nooshin] 1690094483893282   datagram_id: 6 
[Nooshin] 1690094483894000   datagram_id: 7 
[Nooshin] 1690094483894764   datagram_id: 8 
[Nooshin] 1690094483895460   datagram_id: 9
1690094483895460 - 1690094483888721 = **6739**

[Nooshin] 1690094826199826   fr->offset: 0, stream id: 0 
[Nooshin] 1690094826199887   fr->offset: 342, stream id: 0 
[Nooshin] 1690094826199923   fr->offset: 1501, stream id: 0 
[Nooshin] 1690094826199955   fr->offset: 2660, stream id: 0 
[Nooshin] 1690094826199984   fr->offset: 3819, stream id: 0 
[Nooshin] 1690094826200015   fr->offset: 4978, stream id: 0 
[Nooshin] 1690094826200045   fr->offset: 6137, stream id: 0 
[Nooshin] 1690094826200076   fr->offset: 7296, stream id: 0 
[Nooshin] 1690094826200107   fr->offset: 8455, stream id: 0 
[Nooshin] 1690094826200129   fr->offset: 9614, stream id: 0  
1690094826200129 - 1690094826199826 = **303**

Any idea on the reasons for this difference?

Thanks,
Nooshin

**Comment by nEghbal** [comment]
Hello,

I have a general question about DATAGRAM v.s. STREAM frames.

Based on the current implementation, if we want to compare using DATAGRAM frames for sending a resource (e.g., with size 100 KB) v.s. using STREAM frames in a network with packet loss, do you expect more than one RTT difference in the completion time?
Assumption: we do not care about the lost frames using DATAGRAMs.

**Comment by tatsuhiro-t** [comment]
DATAGRAM is not subject to any flow control limits.

**Comment by nEghbal** [comment]
Great.

So, if I want to implement a function (let's call it write_datagrams()) in server.cc to read from a file and send it using DATAGRAMs, what should I do?

I looked into the write_streams() function of server.cc and realized that this part

if (httpconn_ && **ngtcp2_conn_get_max_data_left(conn_)**) {
      sveccnt = nghttp3_conn_writev_stream(httpconn_, &stream_id, &fin,
                                           vec.data(), vec.size());

is for applying flow control. 
So, I do not need to check that in write_datagrams(). Is there any other conditions that I should check for sending DATAGRAMs?

Thanks.
