### ISSUE TITLE
SSL_CTX_use_PrivateKey_file: error

### ISSUE THREAD

**Issue by asingh1984** [ngtcp2/ngtcp2#86]
Hi ,
I tried running following server command , it gives following error.
Any suggestions ?
thanks !
asingh@asingh-server1:~/ngtcp2$ examples/server 127.0.0.1 4433 server.key server.crt
SSL_CTX_use_PrivateKey_file: error:02001002:system library:fopen:No such file or directory
asingh@asingh-server1:~/ngtcp2$

**Comment by alagoutte** [comment]
Hi,

Because missing certificate for server (server.key and servert.crt)
you can use gen-certificate.sh (on ci folder) for generate "demo" certificate

**Comment by alagoutte** [comment]
Hi,

You can use for QUIC draft-13 (or draft-14 with dedicated branch)

you can use client or server executable for generate traffic
