### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by NKTelnet** [ngtcp2/ngtcp2#88]
ngtcp2_ksl.c:455: ngtcp2_ksl_remove: Assertion `i < blk->n' failed.
Aborted (core dumped)

**Comment by NKTelnet** [comment]
#0  0x00007f19865ff1f7 in raise () from /lib64/libc.so.6
#1  0x00007f19866008e8 in abort () from /lib64/libc.so.6
#2  0x00007f19865f8266 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f19865f8312 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000428300 in ngtcp2_ksl_remove (ksl=ksl@entry=0x70677b0, it=it@entry=0x7ffe0d03a450, key=5233) at ngtcp2_ksl.c:455
#5  0x0000000000420e16 in ngtcp2_rtb_detect_lost_pkt (rtb=rtb@entry=0x70677b0, pfrc=pfrc@entry=0x7ffe0d03a4d0, rcs=rcs@entry=0x7067a38, 
    largest_ack=<optimized out>, last_tx_pkt_num=5303, ts=ts@entry=163024282445005) at ngtcp2_rtb.c:548
#6  0x0000000000416400 in ngtcp2_conn_detect_lost_pkt (ts=163024282445005, largest_ack=<optimized out>, rcs=0x7067a38, pktns=0x70676e0, conn=0x70672e0)
    at ngtcp2_conn.c:2415
#7  conn_recv_ack (conn=conn@entry=0x70672e0, pktns=pktns@entry=0x70676e0, hd=hd@entry=0x7ffe0d03a5e0, fr=fr@entry=0x7ffe0d03ac30, ts=ts@entry=163024282445005)
    at ngtcp2_conn.c:2501
#8  0x000000000041725a in conn_recv_pkt (conn=conn@entry=0x70672e0, pkt=pkt@entry=0x7ffe0d03bd30 "0\235\325L\"\206dH", pktlen=pktlen@entry=39, 
    ts=ts@entry=163024282445005) at ngtcp2_conn.c:4334
#9  0x0000000000417eb1 in conn_recv_cpkt (ts=<optimized out>, pktlen=39, pkt=0x7ffe0d03bd30 "0\235\325L\"\206dH", conn=<optimized out>) at ngtcp2_conn.c:4514
#10 ngtcp2_conn_recv (conn=conn@entry=0x70672e0, pkt=pkt@entry=0x7ffe0d03bd30 "0\235\325L\"\206dH", pktlen=pktlen@entry=39, ts=ts@entry=163024282445005)
    at ngtcp2_conn.c:4566

**Comment by tatsuhiro-t** [comment]
Are you using latest draft-15 branch?

**Comment by NKTelnet** [comment]
this one

commit d0e09dd5e43fbd8e44bc2f80db75bd1ec9ee0b95
Author: Tatsuhiro Tsujikawa <tatsuhiro.t@gmail.com>
Date:   Fri Nov 2 18:00:43 2018 +0900

    Update travis toolchain

**Comment by tatsuhiro-t** [comment]
Thank you.  Will look into it.

**Comment by tatsuhiro-t** [comment]
At the moment, I could not reproduce this.

**Comment by NKTelnet** [comment]
It is hard to reproduce this issue. It only happens once on my testbed under stress

**Comment by tatsuhiro-t** [comment]
What kind of stress test?

**Comment by tatsuhiro-t** [comment]
Right, I could reproduce this with unit test.

**Comment by tatsuhiro-t** [comment]
I think 40d9a02a4d18b8c8bdfa9dcd0b70c4b4def7e2b3 fixes this issue.
