### ISSUE TITLE
Question about handle_remote_stream_id_extension()

### ISSUE THREAD

**Issue by NKTelnet** [ngtcp2/ngtcp2#89]
I found an issue, for example:
1. the initial value of unsent_max_remote_stream_id_bidi is 8 on server
2. client used stream id 4 and 8 to communicate with server and closed  stream id 4 and 8
3. server also closed stream id 4 and 8.
4. In this case, unsent_max_remote_stream_id_bidi will not be updated on server, because stream 0 has not been closed. Now client can not create new stream. 

Is it reasonable ? Maybe the unsent_max_remote_stream_id_bidi should be added by 4 once a remote stream has been closed.

**Comment by tatsuhiro-t** [comment]
I think this is because I haven't fully implemented implicit stream open rule.

>    A QUIC endpoint MUST NOT reuse a Stream ID.  Streams of each type are
   created in numeric order.  Streams that are used out of order result
   in opening all lower-numbered streams of the same type in the same
   direction.

**Comment by NKTelnet** [comment]
Thanks a lot for your response.

**Comment by tatsuhiro-t** [comment]
This particular issue has been fixed by d8ad891
