### ISSUE TITLE
Support for the OpenSSL 3.2 QUIC API

### ISSUE THREAD

**Issue by MichalPetryka** [ngtcp2/ngtcp2#898]
Looking at the OpenSSL news:
```
Major changes between OpenSSL 3.1 and OpenSSL 3.2 [under development]:
Added client side support for QUIC.
Added multiple tutorials on the OpenSSL library and in particular on writing various clients (using TLS and QUIC protocols) with libssl.
```
It seems like OpenSSL 3.2 will finally have an official QUIC API.
Seeing the roadmap:
```
OpenSSL is taking a multi-staged approach to the implementation of the [QUIC](https://datatracker.ietf.org/doc/html/rfc9000) transport protocol:

For OpenSSL 3.2, the focus is on providing a client side single stream QUIC implementation.

OpenSSL 3.3 will follow approximately six months later implementing more of the protocol.

OpenSSL 3.4 aims to complete the implementation a further six months later.
```
it looks it'll initially be limited in functionality, but ngtcp2 should still look into adding a backend for it since OpenSSL is still the industry standard crypto library.

**Comment by tatsuhiro-t** [comment]
As far as I know, OpenSSL has no explicit plan to provide an API for an external QUIC library (like ngtcp2) to use its TLS handshake state.  That means OpenSSL is useless for us.
