### ISSUE TITLE
assertion in ngtcp2_ppe_final while sending 0-RTT packet during handshake

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#901]
I'm running a client with a server that purposely doesn't answer, as a test to see if the initial packet retransmits.

Indeed it sends the Initial packet (with the client hello), retransmits it after 1 second, then again after 2 seconds.  So far so good.

But then ngtcp2 decides to send a 0-RTT packet and it asserts inside ngtcp2_ppe_final:
```
lib/ngtcp2_ppe.c:135: ngtcp2_ppe_final: Assertion `ppe->sample_offset + NGTCP2_HP_SAMPLELEN <= ngtcp2_buf_len(buf)' failed.
```

It appears the buffer is 2 bytes too small:
* ppe->sample_offset = 55
* NGTCP2_HP_SAMPLELEN = 16
* ngtcp2_buf_len(buf) = 69

If I comment out the assert, although not the correct solution of course, it is able to continue on enough so that I can capture the packets and see them in wireshark.  Not surprisingly, wireshark is unable to fully decode the 0-RTT packet.

![Screenshot 2023-08-25 at 2 51 51 PM](https://github.com/ngtcp2/ngtcp2/assets/1693761/adb9e645-0676-4fa9-88da-dbe2af513199)

I'm not sure what I might be doing wrong, but I ran into this in both in my own code and in a sample cli tool called quic-echo.  I'm confused as to why it's even sending a 0-RTT packet, because I haven't specified any early data.

I'm trying to understand the code, but I'm pretty lost; any help would be greatly appreciated!

**Comment by tatsuhiro-t** [comment]
I could not reproduce this.
examples/qtlsclient and examples/qtlssimpleclient just keep resending Initial packet, and then the former gets idle timeout (the latter has no idle timeout).
In order to send 0RTT packet, it needs resuming TLS session, that requires set TLS session to TLS object etc, and install early key into ngtcp2_conn.
There may be something wrong around ngtcp2_conn_writev_stream (or its family functions like ngtcp2_conn_write_pkt), for example, ignoring error code, etc.

**Comment by sshock** [comment]
Ok, I just tried `ptlsclient` and `ptlsserver` and sure enough, I could not reproduce the problem with those.

I'll have to take a closer look at my code.  Thank you for the advice and also for confirming that it shouldn't be sending 0-RTT packet (I'm not doing a resumption).

**Comment by sshock** [comment]
I found the problem.  Right after creating the connection I was calling `ngtcp2_conn_set_keep_alive_timeout` to set keep-alive to 2 seconds.

I guess I should not set keep-alive until after handshake is complete.

**Comment by tatsuhiro-t** [comment]
When I call ngtcp2_conn_set_keep_alive_timeout after ngtcp2_conn_client_new, it still does not reproduce the issue.
If client does resumption, 0RTT packet is regularly sent for keeping connection alive, but that does not cause any assertion failure.  However, I think keep-alive should be started only after handshake completes, so I will change the code accordingly.

**Comment by sshock** [comment]
Yeah, I tried the same thing with `ptlsclient` and also still could not reproduce it there.

Yet in my own code the problem is there and definitely goes away if I wait and do that after handshake.

Not sure if this might explain it, but one key difference right now between my code vs the example client is I'm using (external) PSK authentication (whereas the sample app is using cert-based).

**Comment by tatsuhiro-t** [comment]
PSK is basically something like 0RTT.  I checked several TLS backends, but PSK is really not supported very much all typical usecases.  If picotls installs early key when using PSK, then it is possible that ngtcp2 sends 0RTT packet.
Now I think that assertion is not correct.  Will look into it.

**Comment by tatsuhiro-t** [comment]
Right, assertion is correct, and there is a bug in ngtcp2 that we have not pad enough bytes when sending 0RTT packet.
example client does not reproduce this by default because it randomizes the initial packet number, which does not require padding.

**Comment by tatsuhiro-t** [comment]
#904 fixes the assertion failure bug.

**Comment by tatsuhiro-t** [comment]
All issues reported here have been fixed.
