### ISSUE TITLE
ngtcp2 bypass openssl record layer and implement it itself

### ISSUE THREAD

**Issue by huowa222** [ngtcp2/ngtcp2#91]
I'm deploying ngtcp2 and running the c/s examples. I found ngtcp2 integrated with a modified openssl (described in IETF TLS). therefore we failed to use a dynamic link official openssl (it is bad)
as i know google quic is developing gquic implementing both the openssl record layer and the handshake layer by itself, so is it possible for us to that like google's , because we don't want to use " IETF draft defined openssl" at this moment.

**Comment by tatsuhiro-t** [comment]
TLS required by QUIC is actually not TLSv1.3 and requires special interface and EndOfEarlyData message must be removed.  The latter is quite significant and we cannot simply use official openssl.
The current situation is not good for openssl users.  Most of the quic working group participants have their own TLS stack and it is not a problem, but we are in different situation.  The best thing is ask openssl community to implement the required interface, but I guess that they might refuse it until QUIC is standardized.

**Comment by huowa222** [comment]
yes. as i mentioned above, google implemented it's TLS stack by itself, so it is possible for google to use official openssl though they still use boringssl (google customized) in current situation.
anyway, i'm still hoping that you release another version of no-modifed openssl. i'm quite into this topic and thinking about doing it. were i a participant in this project, it would be great.

**Comment by tatsuhiro-t** [comment]
Please read RFC9001 why EOED is removed.
OpenSSL still has no quic support.  Since it is their issue, we do not need to track it here.
