### ISSUE TITLE
Invalid write of size 8 

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#915]
I'm running my code with valgrind and it's showing an "Invalid write of size 8" where picotls writes to the client.max_early_data_size in ptls_handshake_properties_t.

In ngtcp2/crypto/picotls/picotls.c in the `ngtcp2_crypto_picotls_configure_client_session` method it allocates space to hold the max_early_data_size:

```
hsprops->client.max_early_data_size = calloc(1, sizeof(uint32_t));
```

Maybe this changed, but in picotls that field is a [pointer to a size_t](https://github.com/h2o/picotls/blob/master/include/picotls.h#L965) not a uint32, so I think ngtcp2 should be changed to this:

```
hsprops->client.max_early_data_size = calloc(1, sizeof(size_t));
```

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  Will fix it.
