### ISSUE TITLE
Handshake timeout becomes PROTOCOL_VIOLATION

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#916]
When `ngtcp2_conn_handle_expiry()` returns NGTCP2_ERR_HANDSHAKE_TIMEOUT, I call `ngtcp2_ccerr_set_liberr()` to set the last error before disconnecting.

Although this method handles turning NGTCP2_ERR_IDLE_CLOSE into an NGTCP2_CCERR_TYPE_IDLE_CLOSE, it doesn't have anything similar to that for handshake timeout, so it ends up getting the error code from `ngtcp2_err_infer_quic_transport_error_code(liberr)`, which just returns NGTCP2_PROTOCOL_VIOLATION since there is no mapping for NGTCP2_ERR_HANDSHAKE_TIMEOUT.

I understand why this is happening, but I'm wondering if we could do better, since it's not really a protocol violation.

I might suggest adding like an NGTCP2_CCERR_TYPE_HANDSHAKE_TIMEOUT to the ngtcp2_ccerr_type enum, but I think adding to that technically counts as a breaking API change, so I'm quite hesitant about the idea...

Maybe we will have to just let this fall under "applications need to check for and handle that one specifically in their own way if desired", but I'm wondering if maybe you have a better idea?

**Comment by tatsuhiro-t** [comment]
PROTOCOL_VIOLATION is defined as a generic error code (see https://datatracker.ietf.org/doc/html/rfc9000#name-error-handling), and can be used where more specific error code is not found.
If PROTOCOL_VIOLATION sounds unnatural here, the another option is INTERNAL_ERROR which is also a generic error code.

**Comment by sshock** [comment]
Yeah, I think internal error is at least slightly more appropriate.

I'm still just kinda curious though why handshake timeout was not given the same treatment as idle timeout, given how similar they are.

**Comment by tatsuhiro-t** [comment]
We do not send any CONNECTION_CLOSE on idle timeout, but do that on handshake timeout.

**Comment by sshock** [comment]
Oh, I thought handshake timeout also just disconnected without sending a CONNECTION_CLOSE, but I see now that I was not reading the example code closely enough.
