### ISSUE TITLE
0rtt issue in the newest code

### ISSUE THREAD

**Issue by NKTelnet** [ngtcp2/ngtcp2#92]
In the newest draft-15 code, when server receives 0rtt request, the recv_stream_data callback will be triggered before handshake_completed. If server sends  more than 11k data to client in the first recv_stream_data callback before handshake_completed, the subsequent call ngtcp2_conn_write_handshake() will return -203(NGTCP2_ERR_NOBUF).

The code of last week has not this issue.

**Comment by tatsuhiro-t** [comment]
According to https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#rfc.section.4.1.3, it is OK to pass stream data to application before handshake completes.
I haven't check my server, it should probably call ngtcp2_conn_write_handshake() before calling any ngtcp2_conn_write_stream().

**Comment by NKTelnet** [comment]
why does it work for the previous code(last week) ? The example server may call ngtcp2_conn_write_stream() before ngtcp2_conn_write_handshake() too

**Comment by tatsuhiro-t** [comment]
I couldn't reproduce this issue with examples/server.
For resumed session, server only send ~120 bytes Initial and ~150 bytes Handshake packets.  Then it can send bunch of 1RTT packets.
Note that you cannot call ngtcp2_conn_write_stream inside the callback functions.

**Comment by tatsuhiro-t** [comment]
According to https://tools.ietf.org/html/draft-ietf-quic-recovery-16#section-4.5.5, handshake_count (crypto_count) is reset on incoming ACK frame.

**Comment by tatsuhiro-t** [comment]
Closing with no action because no new information has been received for quite a long time.
