### ISSUE TITLE
rcs.loss_detection_timer is not updated in some cases

### ISSUE THREAD

**Issue by NKTelnet** [ngtcp2/ngtcp2#93]
When a client connects to a server at first time(no session file used),  client rcs.loss_detection_timer may be not update correctly when receiving server packets.

**Comment by NKTelnet** [comment]
I1029280599 0xe956531020a80300 rcv loss_detection_timer=1029280609931768 **last_hs_tx_pkt_ts=1029280599931768 timeout=10**
I1029280599 0xe956531020a80300 pkt tx pkt 0 dcid=0x5357531020a80300 scid=0xe956531020a80300 type=Short(0x00) len=0
I1029280599 0xe956531020a80300 frm tx 0 Short(0x00) STREAM(0x13) id=0x0 fin=1 offset=0 len=22 uni=0
I1029280599 0xe956531020a80300 rcv loss_detection_timer=1029280609931768 **last_hs_tx_pkt_ts=1029280599931768 timeout=10**
I1029280599 0xe956531020a80300 pkt tx pkt 1 dcid=0x5357531020a80300 scid=0xe956531020a80300 type=Short(0x00) len=0
I1029280599 0xe956531020a80300 pkt cancel tx pkt 1 type=Short(0x00)
I1029280600 0xe956531020a80300 con recv packet len=46
I1029280600 0xe956531020a80300 pkt rx pkt 2 dcid=0xe956531020a80300 scid=0x5357531020a80300 type=Handshake(0x7d) len=22
I1029280600 0xe956531020a80300 frm rx 2 Handshake(0x7d) ACK(0x1a) largest_ack=0 ack_delay=0(14) ack_block_count=0
I1029280600 0xe956531020a80300 frm rx 2 Handshake(0x7d) ACK(0x1a) block=[0..0] block_count=0
I1029280600 0xe956531020a80300 rcv latest_rtt=0 min_rtt=0 smoothed_rtt=2.334 rttvar=1.482 max_ack_delay=0
I1029280600 0xe956531020a80300 rcv packet 0 acked, slow start cwnd=13453
I1029280600 0xe956531020a80300 rcv loss_detection_timer=1029280609931768 **last_hs_tx_pkt_ts=1029280599931768 timeout=10**
I1029280600 0xe956531020a80300 pkt read packet 46 left 0
I1029280600 0xe956531020a80300 con recv packet len=165
I1029280600 0xe956531020a80300 pkt rx pkt 0 dcid=0xe956531020a80300 scid=0x type=Short(0x00) len=0
I1029280600 0xe956531020a80300 frm rx 0 Short(0x00) CRYPTO(0x18) offset=0 len=130
I1029280600 0xe956531020a80300 frm rx 0 Short(0x00) ACK(0x1a) largest_ack=0 ack_delay=0(14) ack_block_count=0
I1029280600 0xe956531020a80300 frm rx 0 Short(0x00) ACK(0x1a) block=[0..0] block_count=0
I1029280600 0xe956531020a80300 rcv latest_rtt=0 min_rtt=0 smoothed_rtt=2.108 rttvar=1.562 max_ack_delay=0
I1029280600 0xe956531020a80300 rcv loss_detection_timer=1029280609931768 **last_hs_tx_pkt_ts=1029280599931768 timeout=10**
I1029280600 0xe956531020a80300 pkt read packet 165 left 0
I1029280600 0xe956531020a80300 con recv packet len=53
I1029280600 0xe956531020a80300 pkt rx pkt 1 dcid=0xe956531020a80300 scid=0x type=Short(0x00) len=0
I1029280600 0xe956531020a80300 frm rx 1 Short(0x00) MAX_DATA(0x04) max_data=1048598
I1029280600 0xe956531020a80300 frm rx 1 Short(0x00) STREAM(0x12) id=0x0 fin=0 offset=0 len=19 uni=0
I1029280600 0xe956531020a80300 pkt read packet 53 left 0
I1029280600 0xe956531020a80300 con recv packet len=1352
I1029280600 0xe956531020a80300 pkt rx pkt 2 dcid=0xe956531020a80300 scid=0x type=Short(0x00) len=0
I1029280600 0xe956531020a80300 frm rx 2 Short(0x00) STREAM(0x16) id=0x0 fin=0 offset=19 len=1321 uni=0
I1029280600 0xe956531020a80300 pkt read packet 1352 left 0
I1029280600 0xe956531020a80300 con recv packet len=1352
I1029280600 0xe956531020a80300 pkt rx pkt 3 dcid=0xe956531020a80300 scid=0x type=Short(0x00) len=0
I1029280600 0xe956531020a80300 frm rx 3 Short(0x00) STREAM(0x16) id=0x0 fin=0 offset=1340 len=1320 uni=0
I1029280600 0xe956531020a80300 pkt read packet 1352 left 0
I1029280600 0xe956531020a80300 con recv packet len=1352
I1029280600 0xe956531020a80300 pkt rx pkt 4 dcid=0xe956531020a80300 scid=0x type=Short(0x00) len=0
I1029280600 0xe956531020a80300 frm rx 4 Short(0x00) STREAM(0x16) id=0x0 fin=0 offset=2660 len=1320 uni=0
I1029280600 0xe956531020a80300 pkt read packet 1352 left 0
I1029280600 0xe956531020a80300 con recv packet len=1191
I1029280600 0xe956531020a80300 pkt rx pkt 5 dcid=0xe956531020a80300 scid=0x type=Short(0x00) len=0
I1029280600 0xe956531020a80300 frm rx 5 Short(0x00) STREAM(0x17) id=0x0 fin=1 offset=3980 len=1159 uni=0

**Comment by tatsuhiro-t** [comment]
According to https://tools.ietf.org/html/draft-ietf-quic-recovery-16#section-4.5.5, handshake_count(crypto_count) is set to 0 upon acknowledgement of any in-flight packets.

**Comment by NKTelnet** [comment]
I checked this issue today and I found in_pktns->rtb will not be empty even the handshake has been completed for a long time.

**Comment by tatsuhiro-t** [comment]
There might be retransmission because peer doesn't acknowledge handshake packet.  In that case, there should be a retransmission.
Could you tell me how to reproduce it?

**Comment by NKTelnet** [comment]
It is easy to reproduce this issue. Client uses ngtcp2_conn_write_handshake() to connect to server without any session file, and server use ngtcp2_conn_read_handshake() and ngtcp2_conn_write_handshake() to respond the client. If you want, I can paste the complete client and server trace log

**Comment by NKTelnet** [comment]
The following is strace output for client:

**write(5, "\377\377\0\0\17U`\322P[l\303\3\0\373\321P[l\303\3\0\0E/Q\6LF\21-\251"..., 1352) = 1352**
client sends connection packet to server in this write


epoll_ctl(6, EPOLL_CTL_ADD, 5, {EPOLLIN, {u32=5, u64=5}}) = 0
epoll_wait(6, [{EPOLLIN, {u32=5, u64=5}}], 32, 199) = 1
read(5, "\377\377\0\0\17U\373\321P[l\303\3\0`\322P[l\303\3\0\0@u \306\351bK\367X"..., 1500) = 1352
client reads packet from server.


write(1, "**in rtb = 1**, hs rtb = 1, hs_pktns"..., 44in rtb = 1, hs rtb = 1, hs_pktns.tx_ckm = 0
) = 44
in_pktns rtb is empty now


stat("/root/openssl/build/ssl/certs/b0a925c3.0", 0x7fffe8cacb20) = -1 ENOENT (No such file or directory)
stat("/root/openssl/build/ssl/certs/b0a925c3.0", 0x7fffe8cacb20) = -1 ENOENT (No such file or directory)
write(1, "in rtb = 0, hs rtb = 1, hs_pktns"..., 44in rtb = 0, hs rtb = 1, hs_pktns.tx_ckm = 0
) = 44
in_pktns rtb is not empty now.


write(5, "\377\377\0\0\17U`\322P[l\303\3\0\373\321P[l\303\3\0\0E/\202O0\213\273\2459"..., 1352) = 1352
client sends connection packet to server the second time ? 



read(5, "\375\377\0\0\17U\373\321P[l\303\3\0`\322P[l\303\3\0@\311\370\332\206B2fA\370"..., 1500) = 225
client read2 225 bytes from server.


write(1, "in rtb = 0, hs rtb = 0, hs_pktns"..., 51in rtb = 0, hs rtb = 0, hs_pktns.tx_ckm = 29477296
) = 51
in_pktns rtb is not empty yet.

write(1, "handshake_completed\n", 20handshake_completed
handshake_completed

**Comment by tatsuhiro-t** [comment]
Thanks.  It looks like ngtcp2 has some issues in delayed ack.

**Comment by NKTelnet** [comment]
Wait ... I did not use delayed ack.
I1064454385 0x88a858991dc80300 rcv latest_rtt=2 min_rtt=2 smoothed_rtt=2.855 rttvar=1.427 max_ack_delay=0
I set ngtcp2_settings.max_ack_delay to 0 both server and client.
Is it the reason I triggered this issue ?

**Comment by NKTelnet** [comment]
Can you reproduce this issue on your testbed ?

**Comment by tatsuhiro-t** [comment]
Yes.  It looks like I overlooked it.

**Comment by tatsuhiro-t** [comment]
ACK is a bit complicated.  nodelay does not always produce acknowledgements.  Fixing it now.  We have now ACK per 2 received packet rule too.

**Comment by NKTelnet** [comment]
you mean I should not set max_ack_delay to 0 and I should always set delayed ack timer? In my current code, I set max_ack_delay to 0 and no delayed ack timer. 
Once more, could you please send an email to me? I want to discuss some ngtcp2 design issue with you, including recv stream data interface redesign. For some reason, for me it is better to use email not here

**Comment by NKTelnet** [comment]
This issue still exists in draft-15 branch. I think for different transport scenery, we should use different ack delay policy. Setting delayed ack timer may downgrade the whole performance of busy server. In a event driven program, there may be no use of delayed ack. I know google quic has the ACK per 2 received packet rule, but I do not know why. Maybe for mobile service, it is fine. But if you want quic to replace tcp, I think we need configurable ack delay policy.

**Comment by NKTelnet** [comment]
I have sent you an email just now. Could you please take a loot at it ? Thanks very much.

**Comment by tatsuhiro-t** [comment]
Application can set any sensible value to max_ack_delay setting.  I was just wondering that setting 0 really improves performance.
Let me check if the issue still persists if I set 0 to max_ack_delay.

**Comment by tatsuhiro-t** [comment]
We currently has something like this after handshake:

```
rcv loss detection timer fired
rcv packet lost type=Initial(0x7f) 1 sent_ts=1542891660347623936
rcv handshake_count=1 tlp_count=0 rto_count=0
```

Initial packet 1 contains ACK and PADDING.  While both are not retransmittable, but PADDING contributes to in-flight bytes.  The current mechanism of ngtcp2 to manage in-flight bytes is tied to retransmission machinery.  The receiver does not acknowledge retransmittable packets actively, so if that packet is the last one (typically, yes), the sender never get acknowledgement and the packet is considered lost.  As a result the sender reclaims the in-flight bytes accounted for PADDING.
I heard that the future QUIC draft will address this and drop Initial keys soon after Handshake key is obtained.  It will fix this.  Until then, this is what we can get.
