### ISSUE TITLE
compiler warnings with LibreSSL 3.7.3

### ISSUE THREAD

**Issue by vszakats** [ngtcp2/ngtcp2#935]
First warning is because `SSL_CIPHER_get_id` returns an `unsigned long` with LibreSSL (also in latest 3.8.1) and `uint32_t` with OpenSSL/quictls (latest 3.1.2) and BoringSSL.

The second one is due to an extra function pointer `set_read_secret`. This is missing from OpenSSL/quictls (latest 3.1.2), but present in LibreSSL (also in latest 3.8.1) and BoringSSL.

```
Linux llvm 16 and Apple clang 14:
ngtcp2/crypto/quictls/quictls.c:195:15: warning: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
ngtcp2/crypto/quictls/quictls.c:824:1: warning: missing field 'set_read_secret' initializer [-Wmissing-field-initializers]

mingw-64 llvm 16:
ngtcp2/crypto/quictls/quictls.c:824:1: warning: missing field 'set_read_secret' initializer [-Wmissing-field-initializers]

gcc 9:
ngtcp2/crypto/quictls/quictls.c:195:15: warning: conversion from 'long unsigned int' to 'uint32_t' {aka 'unsigned int'} may change value [-Wconversion]
ngtcp2/crypto/quictls/quictls.c:824:1: warning: missing initializer for field 'set_read_secret' of 'SSL_QUIC_METHOD' {aka 'struct ssl_quic_method_st'} [-Wmissing-field-initializers]
```

**Comment by tatsuhiro-t** [comment]
LibreSSL is not officially supported by ngtcp2.  It looks like LibreSSL implements BoringSSL style callbacks that quictls has not followed yet.

**Comment by vszakats** [comment]
I understand, LibreSSL 3.7.0 was the first release with QUIC support. It'd be nice to see it amongst the supported backends with ngtcp2.

I've been doing test builds with this combination for a while now and aside these warnings, builds are fine and basic HTTP/3 tests do work.

You can find test binaries here with curl, HTTP/3 and LibreSSL 3.7.3:
https://github.com/curl/curl-for-win/actions/runs/6098450816
(except bullseye, where CMake is old for ngtcp2)

**Comment by tatsuhiro-t** [comment]
I do not know the actual implementation in LibreSSL, but not specifying set_read_secret should fail handshake.
If I add LibreSSL to ngtcp2 supported backend, I create its own library just like we have separate library for BoringSSL in order to avoid lots of ifdefs.
Will do after ngtcp2 v1.0 release.

**Comment by vszakats** [comment]
That seems like the best approach indeed.

I don't know why, but the test build linked above, using `libngtcp2_crypto_quictls.a`, is able to download via H3:
```
$ ./curl -V
curl 8.2.1 (x86_64-apple-darwin) libcurl/8.2.1 (SecureTransport) LibreSSL/3.7.3 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.56.0 ngtcp2/0.19.0 nghttp3/0.15.0
Release-Date: 2023-07-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz MultiSSL NTLM SSL threadsafe UnixSockets zstd

$ ./curl --disable -v --http3-only https://curl.se/ --write-out '%{http_code}'
[...]
200
```

**Comment by botovq** [comment]
ngtcp2 should be able to use a shared backend for LibreSSL and OpenSSL. When @4a6f656c wrote the implementation, it was specifically designed to work with the then available version of ngtcp2 with the OpenSSL backend. See [for example][1]. One way of avoiding the warning would be to use named initializers.

In OpenBSD, we [enabled QUIC support in curl][2] to use ngtcp2/nghttp3 to have some easy way of testing.

The uint32_t vs long issue comes from an ABI break between OpenSSL 1.1 and OpenSSL 3. The returned value is a NID, and it is a non-negative integer between 0 and in the low thousands, so it is harmless.

[1]: https://github.com/openbsd/src/commit/7ef96453f18b482e76e5c1af640b10d1eac54c2e
[2]: https://github.com/openbsd/ports/commit/7c3daa5884eaa2afc4c3635730ae7d3ede2f3d5e

**Comment by tatsuhiro-t** [comment]
Currently, the difference between quictls and libressl is quite small, and patching quictls.c is easy gas stop solution.
But they are quite different when compiling client/server in examples.  And I am not sure libressl supports 0RTT in QUIC.

For now, I will fix this compile error so that people can do experiment with libressl, but not say anything officially it is supported in the documentation because examples do not compile.  I can make it compile with lots of ifdefs but I would like to avoid it because in the past I wrote the code that supports openssl, libressl, and boringssl and there are lots of ifdefs and that makes the codebase hard to maintain.

**Comment by talregev** [comment]
Can you add functionality to compile ngtcp2 with libressl with cmake?
Thank you!

**Comment by vszakats** [comment]
What is missing for CMake + LibreSSL? (I've been building this combination for a while without issues: https://github.com/curl/curl-for-win/blob/5176e8e694bafc28121ec879411d29ebfffb41fb/ngtcp2.sh

**Comment by talregev** [comment]
> What is missing for CMake + LibreSSL?
> 
> I've been building this combination for a while without issues: https://github.com/curl/curl-for-win/blob/5176e8e694bafc28121ec879411d29ebfffb41fb/ngtcp2.sh

The cmake of ngtcp2 is very confusing,
Do you add the flag ENABLE_OPENSSL for libressl?
https://github.com/ngtcp2/ngtcp2/blob/main/CMakeLists.txt#L123

Because it do `find_package(...)`,  and there no option for libressl.

**Comment by vszakats** [comment]
> The cmake of ngtcp2 is very confusing, Do you add the flag ENABLE_OPENSSL for libressl? https://github.com/ngtcp2/ngtcp2/blob/main/CMakeLists.txt#L123
> 
> Because it do `find_package(...)`, and there no option for libressl.

I do. The configuration for LibreSSL is the exact same as for OpenSSL
(or for _quictls_ to be precise, because mainline OpenSSL doesn't support
ngtcp2):
https://github.com/curl/curl-for-win/blob/5176e8e694bafc28121ec879411d29ebfffb41fb/ngtcp2.sh#L38-L40
