### ISSUE TITLE
Using multiple QUIC streams for incremental resources?

### ISSUE THREAD

**Issue by nEghbal** [ngtcp2/ngtcp2#978]
Hello,

I have a question if in the current implementation ngtcp2 would use multiple streams for an incremental resource (i=1) like an image or any resource will be sent over just ONE stream?

Thanks.

**Comment by tatsuhiro-t** [comment]
I do not understand the question. Could you elaborate on that?

**Comment by nEghbal** [comment]
If we want to send request for a CSS file with u=0 (high priority) and i=0 (non-incremental) and a request for an image file with u=3 and i=1 (incremental), how they would be sent? 
The server will use one stream for the CSS file and one stream for the image file? Or we can send the image file using 2-3 streams so losing one part of the image does not block the rest?

**Comment by tatsuhiro-t** [comment]
So you are talking about HTTP extensible priorities.  Typical HTTP uses 1 stream for each resource.  Send whatever the highest prioritized resource first.  Please use discussion for this kind of topic or ask in stackoverflow, and someone interested might find and answer it.
