### ISSUE TITLE
IETF draft 14 master failed to enable cipher suite negotiation.

### ISSUE THREAD

**Issue by huowa222** [ngtcp2/ngtcp2#98]
on the client side, ngtcp2 supply command line args to control cipher suite negotiation as below.
--ciphers=<CIPHERS>
Specify the cipher suite list to enable.

however, no matter what arguements set in --ciphers= , the server response only with a cipher suite "TLS_AES_256_GCM_SHA384", why ? is it a bug or my misuse in command line?

**Comment by tatsuhiro-t** [comment]
It works for me.  Try the latest version.
