### ISSUE TITLE
NGTCP2_PROTO_VER_MAX is set to NGTCP2_PROTO_VER_V1

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#989]
Shouldn't it be set to NGTCP2_PROTO_VER_V2?

Also, what is the intended use case for this, and will it work properly with non-consecutive version numbers (V1 = 1, V2 = 0x6b3343cf; maybe for V3 the value will go down not up?).

If it's not suitable for any use case, maybe we should just get rid of it?  I don't see NGTCP2_PROTO_VER_MIN or NGTCP2_PROTO_VER_MAX being used anywhere in the library itself.

**Comment by tatsuhiro-t** [comment]
Yeah, quic v2 codepoint is unexpected, and our macros can not deal with it.  I agree that they should be deprecated for now.
